### ISSUE TITLE
What do I need to do if I want to upload multiple pictures?

### ISSUE THREAD

**Issue by CollinsWalker** [parse-community/Parse-SDK-Android#1009]
What do I need to do if I want to upload multiple pictures?

Parsefile, do you support the coexistence of multiple pictures?

**Comment by Jawnnypoo** [comment]
You would just upload multiple `ParseFile`s, right?

**Comment by CollinsWalker** [comment]
> You would just upload multiple `ParseFile`s, right?

It seems that we need to create more parsefiles
