### ISSUE TITLE
Why do I not execute the real-time data when I use HTTPS domain name and the real-time data when I use IP address

### ISSUE THREAD

**Issue by CollinsWalker** [parse-community/Parse-SDK-Android#1015]
Why do I not execute the real-time data when I use HTTPS domain name and the real-time data when I use IP address

**Comment by TomWFox** [comment]
Cross-posted - https://community.parseplatform.org/t/why-do-i-not-execute-the-real-time-data-when-i-use-https-domain-name-and-the-real-time-data-when-i-use-ip-address/87/3

**Comment by Jawnnypoo** [comment]
Can you post this on https://github.com/parse-community/ParseLiveQuery-Android instead? Thank you 🙏
