### ISSUE TITLE
Cannot use coroutines extension function save 

### ISSUE THREAD

**Issue by LopsemPyier** [parse-community/Parse-SDK-Android#1016]
Hello,
I've import parse sdk and parse coroutines with 
``` gradle
//Parse SDK
implementation "com.github.parse-community.Parse-SDK-Android:parse:1.23.1"
//Parse coroutines
implementation "com.github.parse-community.Parse-SDK-Android:coroutines:1.23.1"
```

And when I try to save a `ParseObject` with a coroutine, it use the parse method `save` and not the extension one. This is because they have the same name so the method win over the extension.

If I made a mistake when add dependency in my android project, I apologize but I tried with the _README.md_ which isn't clear enought.

Thank you.

P.S: In the [README.md](https://github.com/parse-community/Parse-SDK-Android/tree/master/coroutines#parseuser) it says for `signUp` :

> ``` kotlin
> launch { // Coroutine builder
>     user = ParseUser().apply {
>         setUsername("my name")
>         setPassword("my pass")
>         setEmail("email@example.com")
>     }.also {
>         signUp()
>     }
> }
> ```

but in fact the function is `singUp`.

**Comment by Jawnnypoo** [comment]
@oliveiradev Do you have any info or experience with this? Maybe we need to changes the names of the extension methods?

**Comment by Jawnnypoo** [comment]
In the mean time, I think if you add the extension import manually to the class, it will work.

**Comment by oliveiradev** [comment]
I think that the manual import will solve it, but change the method signature name can be a better solution

**Comment by oliveiradev** [comment]
@Jawnnypoo I see that the IDE suggests the correct import, do you have some suggestion about the way that we need to solve this?

**Comment by Jawnnypoo** [comment]
I didn't try this out myself, just going off of what @LopsemPyier mentioned. If it shows the correct imports by the IDE, then I don't think there is an issue here.

**Comment by LopsemPyier** [comment]
The IDE doesn't show the import I only got the save method define in parse. 
I only got these suggestions whiwh are from the parse sdk and not from the extension
![screen](https://user-images.githubusercontent.com/32937655/79369017-99a41500-7f50-11ea-872a-fc66677a4b90.png)
And I manually import the save method from the extension like this
``` kotlin
import com.parse.coroutines.write.parse_object.save
```
It might not be an issue but I can't understand why it doesn't work

**Comment by oliveiradev** [comment]
@LopsemPyier I'll double check it, and if I got some problem I'll try to solve in the next days

**Comment by LopsemPyier** [comment]
OK thank you

**Comment by shlusiak** [comment]
Are there any updates on this? None of the couroutines seem usable to me, even when manually importing the function, the `save` of ParseObject is called, not the extension function. I suggest not shadowing the name but expose those functions using different names or parameters to be able to distinguish them when writing code.

**Comment by oliveiradev** [comment]
Hello guys,

I really would like that you guys take a look and left a comment if something should be better
