### ISSUE TITLE
Bolts Tasks jitpack repo requires authentication

### ISSUE THREAD

**Issue by DoctorLion** [parse-community/Parse-SDK-Android#1020]
I've just upgraded to Parse-SDK-Android:parse:1.24.0
I got this error, and when I click the link it asks for a username and password for Jitpack

Could not GET 'https://jitpack.io/com/github/parse-community/bolts-tasks/1.24.0/bolts-tasks-1.24.0.pom'. Received status code 401 from server: Unauthorized
Enable Gradle 'offline mode' and sync project

**Comment by Jawnnypoo** [comment]
Hmm @rogerhu I think maybe the dependency needs to change from `api` to `implementation`, but then users will have to add the `bolts` dependency themselves via `implementation "com.github.parse-community.Parse-SDK-Android:bolts-tasks:$parseVersion"`.

**Comment by rogerhu** [comment]
ok fixing!

**Comment by rogerhu** [comment]
Please try 1.24.1?

**Comment by DoctorLion** [comment]
Great Work, Thanks
