### ISSUE TITLE
1.24.0

### ISSUE THREAD

**Issue by muhammedvilla85** [parse-community/Parse-SDK-Android#1021]
i am getting this error  when implementing the dependency
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.parse-community:bolts-tasks:1.24.0.
Show Details
Affected Modules: app
![Capture](https://user-images.githubusercontent.com/22192833/79914528-14ef4600-83eb-11ea-96d6-806e909d0a64.PNG)

**Comment by Jawnnypoo** [comment]
Dupe https://github.com/parse-community/Parse-SDK-Android/issues/1020
