### ISSUE TITLE
Making subclasses

### ISSUE THREAD

**Issue by JorisGanne** [parse-community/Parse-SDK-Android#1023]
Hello, I am a beginner in programming. I have had some lessons about database structure on school and understand the principles of subclasses and inheritance etc. I'm now working on a project (voluntarily) to make an app for android. I have discovered already some nice functionalities of parse but now I want to create some subclasses of the standard class User. Is it possible? Can someone give me maybe an example code so that I can find hopefully how I can do it myself?
Thanks in advance!

**Comment by Jawnnypoo** [comment]
Sure, no problem. Here is an example in Kotlin:

```
package com.commit451.parsetests.api

import com.parse.ParseClassName
import com.parse.ParseUser

/**
 * A custom user
 */
@ParseClassName("_User")
class User : ParseUser() {

    companion object {
        const val KEY_BIO = "bio"
    }

    var bio: String?
        get() = getString(KEY_BIO)
        set(value) = put(KEY_BIO, value)

}
```
Don't forget to register it too:
```
ParseObject.registerSubclass(User::class.java)
```
