### ISSUE TITLE
Cannot get current GoogleSignInAcoount

### ISSUE THREAD

**Issue by ashprog** [parse-community/Parse-SDK-Android#1027]
Please remove the code where googleSignin.signout is written.
googleSignInClient?.signOut()?.addOnCompleteListener {}
As we may need to fetch user's information afterwards.

**Comment by Jawnnypoo** [comment]
The recommended approach would be that you use your own flow to sign in the user via the `googleSignInClient` and do that once the sign in via Parse is successful.

**Comment by ashprog** [comment]
> The recommended approach would be that you use your own flow to sign in the user via the `googleSignInClient` and do that once the sign in via Parse is successful.

Yeah..I have created my own MyParseGoogleUtils.
