### ISSUE TITLE
Login with facebook throws login error

### ISSUE THREAD

**Issue by SomeKoder** [parse-community/Parse-SDK-Android#1030]
I have been having this issue for a while now while trying
ParseFacebookUtils.logInWithReadPermissionsInBackground(). 

From what I've seen, this only happens on certain devices (Samsung S10 being one). The error reads

> "Login Error: There is an error in logging you into this application. Please try again later."

![facebook_error](https://user-images.githubusercontent.com/49205285/82927127-3a252600-9f4e-11ea-8bab-08a8fdbec0d5.jpg)

Unfortunately, there are no logs indicating what could be happening.

Here are the SDK versions I'm using, although the same error would happen using ParseFacebookUtilsV4.jar
'com.github.parse-community.Parse-SDK-Android:facebook:1.24.1' and 
'com.github.parse-community.Parse-SDK-Android:parse:1.24.1'

**Comment by Jawnnypoo** [comment]
I would suggest looking at the Facebook login SDK and try out some testing with that and leave out the Parse login/signup and see if you still see the same issues. I believe this has to do with your configuration of your app on the Facebook side of things and does not have to do with our library.

**Comment by SomeKoder** [comment]
You are 100% right, using the facebook SDK even without parse gives me the same thing. I will close the issue and take it up with facebook. Thanks!
