### ISSUE TITLE
Fix change log, release page, maintainance

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Android#1034]
### Issues

- [x] Fix change log
Change log does not reflect last 3 releases (fixed by https://github.com/parse-community/Parse-SDK-Android/pull/1035)
- [x] Fix release page and sync with change log
Release page should be corrected according to change log correction in https://github.com/parse-community/Parse-SDK-Android/pull/1035 
- [x] Add warning about broken releases 1.24.0-1.24.1
Releases are broken because of naming conflict with integrated bolts module
- [x] Fix incorrect note for release 1.24.2
Release breaks not only when integrating the FB Android SDK but also when using our own module
- [x] Agree on change log / release page style: add reference to issue / PR for each change as we already do in other Parse SDKs to track changes; the change log currently contains entries that I cannot trace to an issue or merge, adding proper references avoids this, syntax suggestion:

- FIX/ADD/REMOVE/CHANGE: _Description_ See [#_IssueNumber_](https://github.com/parse-community/Parse-SDK-Android/issues/_IssueNumber_) for details. Thanks to [_Name_](https://github.com/_name_).

- [ ] Add call for maintainers
The change log was not updated since 3 releases and the SDK was broken for 2 months, although it took me 30 mins to fix it. If we need more maintainers please pin a call to this repo to find some.

**Comment by Jawnnypoo** [comment]
I opted to point the releases to the CHANGELOG.md file directly so that there is no need for duplication and so that it is editable by others as well. Good idea on the new format. You now have write permission. Thanks for your contributions!
