### ISSUE TITLE
IO failure

### ISSUE THREAD

**Issue by shouri25** [parse-community/Parse-SDK-Android#1040]
When ever i try to create account or login i am getting io error.
Followed all instructions as in document.

**Comment by mtrezza** [comment]
`I/O failure` usually points to the Parse SDK not being able to communicate with Parse Server.

- Check the Parse Server URL that you use to initialize the Parse Android SDK.
- Check whether you can reach the server without using the Parse SDK, e.g. using a browser pointing to the `/health` endpoint.
- Post the full error message here as you see it in the logs in your Android IDE and check if you see any errors in Parse Server logs.

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved, feel free to comment if you have any questions and we can re-open this issue.
