### ISSUE TITLE
ParseUser.findInBackGround.result throws NullPointerException, even if the Query exists

### ISSUE THREAD

**Issue by Berki2021** [parse-community/Parse-SDK-Android#1043]
Hello,

I am trying to search my user database for a specific key e.g. name here. The problem is that findInBackground throws a NullPointerException even if the user exists AND the specific key is found. Using find or first works but blocks the main thread.

Here is my code:
` fun checkNameExistsNullPointer(value: Any) = ParseUser.getQuery().whereEqualTo("username", "User1").findInBackground().result.isNullOrEmpty()
`

` fun checkNameExistsWorksBlocking(value: Any) = !ParseUser.getQuery().whereEqualTo("username", "User1").find().isNullOrEmpty()
`

**Comment by Jawnnypoo** [comment]
That is because the bolts Task has not completed yet when you do `findInBackground`, therefore there is no `result` at the time that you are calling it. You would have to do something like `findInBackground` with a continuation to see the results. For example:
```
fun checkNameExistsNullPointer(value: Any) = ParseUser.getQuery().whereEqualTo("username", "User1").findInBackground().continueWithTask { 
   if (it.result.isNullOrEmpty())
       doSomething()
   if (it.isFaulted()) 
       doSomethingForTheError()
}
```

**Comment by Berki2021** [comment]
Yeah, it does not work... It says: 
" Type mismatch.
Required:
((Task<(Mutable)List<ParseUser!>!>!) → Task<(???..???)>!)!
Found:
(Task<(Mutable)List<ParseUser!>!>!) → Unit"

**Comment by Berki2021** [comment]
fun checkNameExistsNullPointer(value: Any) {
        ParseUser.getQuery().whereEqualTo("username", "value").findInBackground().continueWithTask {
            return@continueWithTask it.result.isNullOrEmpty()
        }
    }

Error:

Type mismatch.
Required:
((Task<(Mutable)List<ParseUser!>!>!) → Task<(???..???)>!)!
Found:
(Task<(Mutable)List<ParseUser!>!>!) → Boolean

**Comment by Jawnnypoo** [comment]
You cannot `return@continueWithTask` the boolean, since it is expecting a Task. You'll want to read more about Bolts tasks and how they work here: https://github.com/BoltsFramework/Bolts-Android

**Comment by Berki2021** [comment]
Okay I will, but couldn't you provide me the answer?

**Comment by Jawnnypoo** [comment]
This comment https://github.com/parse-community/Parse-SDK-Android/issues/1043#issuecomment-654349191 provides the answer you need. You cannot call async code, ie. a bolts task like this and expect it to return a synchronous result. You either need to change it to be `fun checkEmailExistsAsync(value: Any): Task<Boolean>` and transform the task from a list of users to the boolean you want, or you need to do the background threading yourself and use `find` instead of `findInBackground`.

**Comment by Berki2021** [comment]
Hmm okay,  thanks.

**Comment by Berki2021** [comment]
@Jawnnypoo I have another question. Couldn't I write a cloud function which checks, if the email aka user already exists and call this cloud function asynchronously within android?

**Comment by Jawnnypoo** [comment]
Yes, that would be a good solution. Something like this:
```
            val params = mutableMapOf<String, Any>()
            params["email"] = value
            ParseCloud.callFunctionInBackground<Void>("checkEmailExists", params) {
                  doSomethingBasedOnResult()
            }
```

**Comment by Berki2021** [comment]
Amazing, thank you very much. Using a cloud function will give me the ability to call it from ios as well
