### ISSUE TITLE
Facebook SDK wrong authData

### ISSUE THREAD

**Issue by pcegarra** [parse-community/Parse-SDK-Android#1052]
Im using the latest version of the parse fbk sdk.
And Im doing this:

`ParseFacebookUtils.logInWithReadPermissionsInBackground(getActivity(), Arrays.asList("public_profile","email"), new LogInCallback() {`

But the authData result is the following:

```
{
  "facebook": {
    "access_token": "...",
    "permissions": "public_profile,email",
    "id": "...",
    "expiration_date": "...",
    "last_refresh_date": "..."
  }
}
```

**Comment by Jawnnypoo** [comment]
Hmmm, so how is that information incorrect? That provides you with the access token, you would have to make additional calls to the Facebook API to retrieve things like email and public profile.

**Comment by pcegarra** [comment]
True, Im wrong thinking that the authData must have the email, but no, we need to call to the facebook api
