### ISSUE TITLE
Coroutine library support is not importing.

### ISSUE THREAD

**Issue by Kialagao** [parse-community/Parse-SDK-Android#1074]
Parse is getting imported but the Coroutine library support isn't.

**Comment by Jawnnypoo** [comment]
Can you paste what your dependencies looks like?

**Comment by Kialagao** [comment]
![App](https://user-images.githubusercontent.com/32660538/103737007-36f31d80-4fa6-11eb-8e4a-ba14ea7650f1.png)
![Module](https://user-images.githubusercontent.com/32660538/103737038-3fe3ef00-4fa6-11eb-9657-739ade414bc2.png)
![ErrorMsg](https://user-images.githubusercontent.com/32660538/103737050-45413980-4fa6-11eb-9dbd-b8a243b00277.png)

Hello. First image is app level. Second image is module. Last is the error message.

**Comment by Jawnnypoo** [comment]
That extension does not exist, you'll want to use `user. suspendSave` instead

**Comment by Kialagao** [comment]
I'm sorry, but it's still not working. 
![Err](https://user-images.githubusercontent.com/32660538/103811114-42c7f980-5011-11eb-850a-be82c7bb7455.png)

**Comment by Jawnnypoo** [comment]
`user.suspendSave()`, not `user.saveInBackground().suspendSave()`

**Comment by Kialagao** [comment]
Same thing. It's fine though. There's prolly something wrong on my end.
![Er](https://user-images.githubusercontent.com/32660538/103814452-88d38c00-5016-11eb-94a1-0e3face228d2.png)
