### ISSUE TITLE
Release a new version for full coroutines support

### ISSUE THREAD

**Issue by paolorotolo** [parse-community/Parse-SDK-Android#1079]
HI!
I'm using Parse with Kotlin in suspend functions and I was very glad to see coroutines support!
Anyway, latest parse version was released last summer, while some useful coroutine methods (like `suspendFind` and task extension functions) were only written in September.

If a stable version update is not possibile right now, I would at least make sure that in Coroutines README [1], it's clear that some of the showcased functionalities are still not available in stable (maybe add code to include jitpack dev builds).

[1] https://github.com/parse-community/Parse-SDK-Android/tree/master/coroutines

**Comment by Jawnnypoo** [comment]
Sounds good, 1.26.0 has been released 👍
