### ISSUE TITLE
Parse taking 20 to 25 seconds on first call with back4app

### ISSUE THREAD

**Issue by ark-dev-account** [parse-community/Parse-SDK-Android#1080]
Parse version: 1.25.0
Hi everyone
I using parse with back4app and its very easy to integrate and very good in overall response, but I am facing only one issue that when ever I do my first interaction with back4app either to get config or call first cloud function it took 20 to 25 seconds to response, after first call then every single call took less than a second, even call the config again or call the same cloud function, and its only happening in real device, its not happening in simulator. I tried many devices but get same response.

**Comment by ahmad-alkhatib** [comment]
You just need to use the default server URL:

https://parseapi.back4app.com

**Comment by davimacedo** [comment]
Would you mind to open a ticket at back4app web-site?
