### ISSUE TITLE
Error After Adding Dependencies to my android studio project

### ISSUE THREAD

**Issue by pythonistastic** [parse-community/Parse-SDK-Android#1081]
Hey guys,

I have added this dependencies according to what is mentioned in here (Prase-SDK-Android), but when I click the Sync it shows failure to resolve.

I added the lines for maven { url "https://jitpack.io" } also the ext{} with the latest version and the implementation line in the dependencies.

This is the error I get when I run the project:

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.parse-community.Parse-SDK-Android:parse:1.26.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/parse-community/Parse-SDK-Android/parse/1.26/parse-1.26.pom
       - https://jcenter.bintray.com/com/github/parse-community/Parse-SDK-Android/parse/1.26/parse-1.26.pom
       - https://jitpack.io/com/github/parse-community/Parse-SDK-Android/parse/1.26/parse-1.26.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Please help me with this error.

**Comment by Jawnnypoo** [comment]
Did you try it with 1.25.0 as well?

**Comment by pythonistastic** [comment]
> Did you try it with 1.25.0 as well?
Yes I have trief 1.25 but still the error shows up

**Comment by Jawnnypoo** [comment]
It needs to be 1.26.0 not just 1.26

**Comment by pythonistastic** [comment]
> It needs to be 1.26.0 not just 1.26

Thanks man .. that solved it 🙌
