### ISSUE TITLE
i / o failure to use parse sdk

### ISSUE THREAD

**Issue by fullstact69** [parse-community/Parse-SDK-Android#1085]
In China, there is the i / o failure exception to use sign up API. How to resolve it?

**Comment by Jawnnypoo** [comment]
It could be any number of things, but likely due to a server configuration issue. Please give more details.

**Comment by fullstact69** [comment]
what should I do more on server configuration for China? In addition, google is not allowed in China

**Comment by Jawnnypoo** [comment]
Does you server use HTTPS? That is likely the issue. If you add a logging interceptor https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor to your Parse instance you can see why it is failing.

**Comment by mtrezza** [comment]
Closing as this issue seems to be resolved.
