### ISSUE TITLE
Indirect dependency to jcenter

### ISSUE THREAD

**Issue by vernazza** [parse-community/Parse-SDK-Android#1089]
Package com.github.parse-community.Parse-SDK-Android:gcm:1.26.0 depends on com.firebase:firebase-jobdispatcher:0.8.6 that is deprecated and only available on Jcenter.
Jcenter is being dismissed, so since 1 February 2022, it will not be possible to use Parse-SDK-Android:gcm.

com.firebase:firebase-jobdispatcher should then be replaced with WorkManager (https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb)

**Comment by Jawnnypoo** [comment]
GCM is a legacy dependency that most should be moving off of anyways, but yeah, good callout.

**Comment by Jawnnypoo** [comment]
Actually yeah, based on https://developers.google.com/cloud-messaging/faq I am going to go ahead and delete this module entirely since it won't function properly anyways.
