### ISSUE TITLE
Add missing modules to API docs

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Android#1115]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of the Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/releases). 
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases).

### Issue Description
The API docs are missing some modules (FB, FCM, etc), they only contain the `parse` module.

### Solution
Adapt API docs generation (`javadoc`) to include the missing modules in a single doc.

**Comment by L3K0V** [comment]
@mtrezza this SDK is published via Jitpack. Actually Jitpack supports multi-module javadoc - see here: https://jitpack.io/docs/#javadoc-publishing
