### ISSUE TITLE
Define compatible Android API versions

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Android#1123]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).

### Current Limitation

There are no rules for:
- how long Android API versions should be supported
- which Android version should be targeted

### Feature / Enhancement Description

Define rules for how to increment:
- `minSdkVersion`
- `targetSdkVersion`

The `minSdkVersion` rule could be informed by which is the lowest Android version that received security patches. An Android platform that is out-of-support would likely not need to be supported by the Parse Android SDK.

Also evaluate whether it is possible - or makes sense - to test the SDK in different Android versions, similar to how we test Parse Server for different Node versions.

### Example Use Case

n/a

### Alternatives / Workarounds

n/a

**Comment by L3K0V** [comment]
This can be closed. 
API bump strategy was defined in [CONTRIBUTION.md]( https://github.com/parse-community/Parse-SDK-Android/blob/master/CONTRIBUTING.md#android-api-compatibility) and supported version into the [README.md](https://github.com/parse-community/Parse-SDK-Android/blob/master/README.md#compatibility)
