### ISSUE TITLE
Tracking push opens issue

### ISSUE THREAD

**Issue by ali-kosesakal** [parse-community/Parse-SDK-Android#1138]
Hi Parse;

We have been encountering the exact same problem in this [issue](https://github.com/parse-community/Parse-SDK-Android/issues/331) for a long time. Can you help about this? Thanks in advance.

Screenshot from our dashboard:
![Screenshot (74)](https://user-images.githubusercontent.com/6900802/139880487-1d626cdd-5563-4bf4-bd98-38bcea0ed594.png)

**Comment by mtrezza** [comment]
I'm closing this as it lacks essential information. Feel free to edit your question using the issue template and we can re-open this issue.
