### ISSUE TITLE
Outdated dependencies and using of deprecated code

### ISSUE THREAD

**Issue by L3K0V** [parse-community/Parse-SDK-Android#1142]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).

This Issue is continuation of #1095

### Current Limitation

Currently there are some dependencies which are outdated and some of the modules uses deprecated code.

### Feature / Enhancement Description

The idea is to update and keep all dependencies up-to-date and remove all deprecated code.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.2.0](https://github.com/parse-community/Parse-SDK-Android/releases/tag/2.2.0)
