### ISSUE TITLE
Gradle dependencies out of date

### ISSUE THREAD

**Issue by mobilekosmos** [parse-community/Parse-SDK-Android#1159]
### New Feature / Enhancement Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).

Mandy gradle dependencies are outdated, please update.

**Comment by mtrezza** [comment]
@mobilekosmos Do you want to open a PR for this?
