### ISSUE TITLE
Facebook login fails logging in to Facebook from an embedded browser

### ISSUE THREAD

**Issue by EAncis** [parse-community/Parse-SDK-Android#1164]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/releases). 

### Issue Description
I am part of the [removed] developer team, one of our apps is [removed]. Our Apps (iOS/Androd) include the authentication throughout the Facebook account that has always workred on each platform.

Now we have been contacted by the Facebook team beacuse a persiting issue on this feature douring these last mounths on Android. 

We have updates the Facebook SDK and your Parse-SDK-Android, che cked our existing implemetantion about the login flow from the [developer Facebook documentation](https://developers.facebook.com/docs/facebook-login/android) and the [your Parse Facebook Utils for Android](https://github.com/parse-community/Parse-SDK-Android/tree/master/facebook).

Everything appears correct, but the issue persists. 

Maybe Parse Facebook Utils for Android need to be update after any Facebook SDK Change? 
Anyway can you help us to fix our issue?

### Steps to reproduce
- Install Android Facebook app on your device;
- Login on facebbok;
- Download the [app removed]
- Follow the introdicing tutorial or skip it;
- Tap on the Facebook login button.

### Actual Outcome
Facebook login error view with **_For your account security, logging in to Facebook from an embedded browser is disabled. You may be able to continue by updating the app you're logging in from and trying again_** message.

### Expected Outcome
Proceed to login on the [removed] app and access the its homeview

### Environment
Developing on Android Studio Bumblebee 2021.1.1 Patch 3, Java Language, Gradle 7.2 and Gradle plugin 7.1.3
Tested on Android 10 (physical device) and 12 (emulated device)
Dependencies:
com.facebook.android:facebook-android-sdk:13.1.0:
com.facebook.android:facebook-login:13.1.0
com.github.parse-community.Parse-SDK-Android:parse:3.0.0
com.github.parse-community.Parse-SDK-Android:google:3.0.0
com.github.parse-community.Parse-SDK-Android:facebook:3.0.0
com.github.parse-community.Parse-SDK-Android:fcm:3.0.0
com.github.parse-community.Parse-SDK-Android:ktx:3.0.0
com.github.parse-community.Parse-SDK-Android:coroutines:3.0.0

Parse Android SDK
- SDK version: `3.0.0`
- Operating system version: `Android`

Server
- Parse Server version: `3.9.0`
- Operating system: Back4App does not provides that info
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `www.back4app.com`

Database
- System (MongoDB or Postgres):  Managed by Back4App
- Database version: Managed by Back4App
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Managed by Back4App

### Logs
Any long is retrived into theLogcat. 
On debugging mode we can check that after the FB Button onclick the flow passes into 

```ParseFacebookUtils.logInWithReadPermissionsInBackground(...)```
 
 then throught the 
 
```
 @Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
  super.onActivityResult(requestCode, resultCode, data);
  ParseFacebookUtils.onActivityResult(requestCode, resultCode, data);
} 
```
 but does not return from the callback into any case of
```
@Override
  public void done(ParseUser user, ParseException err) {
    if (user == null) {
      Log.d("MyApp", "Uh oh. The user cancelled the Facebook login.");
      ...
    } else if (user.isNew()) {
      Log.d("MyApp", "User signed up and logged in through Facebook!");
      ...
    } else {
      Log.d("MyApp", "User logged in through Facebook!");
      ...
    }
  }
```

**Comment by L3K0V** [comment]
@mtrezza thanks for the link. [Deprecating webviews](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews) page gives nice guide what to do in order to overcome the deprecation.

> In my understanding, upgrading to the newest FB SDK should fix the issue.

Here we use version v12 of the SDK which will be bumped to latest v13 in https://github.com/parse-community/Parse-SDK-Android/pull/1163 

@EAncis when login what happens - a web view appear to login or the Facebook app is opened? Will be strange if web view login is triggered when you have installed Facebook on the phone. Can you confirm that login is not working also without Facebook app?

**Comment by L3K0V** [comment]
From [Deprecating webviews](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews) it looks that the app should have configured CustomTabs something I think is not part of the Parse Facebook module right now.

@EAncis may you please follow these steps in the [Deprecating webviews](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews) and tell us the outcome:

- Ensure that your app has configured support for Custom Tabs properly. (For more information on Custom Tabs, see the [Custom Tabs documentation](https://developer.chrome.com/docs/android/custom-tabs/overview/).) To test your configuration:
    - Ensure that you have a browser compatible with Custom Tabs (example browsers that support Custom Tabs include Chrome, Samsung Browser, etc).
    - Delete the Facebook app from your device if you have it installed. Login from your app. You should see a window open in the external browser rather than in a native WebDialog.

**Comment by EAncis** [comment]
> @mtrezza thanks for the link. [Deprecating webviews](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews) page gives nice guide what to do in order to overcome the deprecation.
> 
> > In my understanding, upgrading to the newest FB SDK should fix the issue.
> 
> Here we use version v12 of the SDK which will be bumped to latest v13 in #1163
> 
> @EAncis when login what happens - a web view appear to login or the Facebook app is opened? Will be strange if web view login is triggered when you have installed Facebook on the phone. Can you confirm that login is not working also without Facebook app?

Hi @mtrezza, sorry for the delay in my reply, I describe 3 use cases: 
1) With Facebook app logged: user clicks on Facebook login button, somethings happens (a quick loader and a quick view appears) but my app does not proceed.

2) With Facebook app not logged: user clicks on Facebook login button, it's opened the Facebook app, user select his account, it's tried the login flow, the it's shown this error view inside my app
![Screenshot_20220511-150146](https://user-images.githubusercontent.com/78539439/167858681-42efc7d0-dc1a-43b1-97ef-0cb2fd4fef36.png)

3) Without facebook app: user clicks on Facebook login button, it's opened the chorme embedded broswer with the same message error
![Screenshot_20220511-151729](https://user-images.githubusercontent.com/78539439/167859309-63c0828f-9faf-4d16-9233-ebf1bcd274d5.png)

**Comment by EAncis** [comment]
In addition to what just written to @mtrezza a strange behavior that I have observed is that the login is successful only with the developer facebook account credentials

**Comment by L3K0V** [comment]
@EAncis did you try with older version of the Parse SDK for Android?

It will be important to know if it's failing with an older version. This will hint whenever this is issue in the SDK or misconfiguration in your app.

**Comment by EAncis** [comment]
> 
with this configuration the FB login was still working at the beginning of the year, then stops 

Gradle 4.1.1
Android API 31
 
dependences:
Parse SDK 1.23.1 
facebook-login 5.15.3
Parse SDK 1.23.1
facebook-android-sdk:4.42.0


Then I tried with this update:

Gradle 7.1.3
Parse SDK 3.0.0
facebook-login 13.1.0
facebook-android-sdk 13.1.0


but the issues is not fixed

**Comment by L3K0V** [comment]
And you did check if there are required adjustments to configure your app to the newer Facebook SDK? 

Jumping from:

facebook-login 5.15.3 -> facebook-login 13.1.0\
facebook-android-sdk:4.42.0 -> facebook-android-sdk 13.1.0

Is big leap...

When I update the Facebook SDK and the Facebook module on the Parse SDK for Android I did check for some breaking changes regarding the SDK itself and the way the code is organized, implemented etc and did not find anything.
