### ISSUE TITLE
logInWithReadPermissionsInBackground sends out an verification email

### ISSUE THREAD

**Issue by pallipavan** [parse-community/Parse-SDK-Android#1170]
- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/releases). 

### Issue Description
Verification email sends out for the users logged in via OAuth

### Steps to reproduce
Login with facebook
user will receive an mail verify the email

### Actual Outcome
when login type is OAuth (Facebook, Google+, Twitter) then user received an email to verify

### Expected Outcome
If login type is OAuth (Facebook, Google+, Twitter) then user should not receive email to verify

### Environment
in test and live environments

Parse Android SDK
parseSdkVersion            : "2.0.4",
parseBoltsVersion          : "1.4.0",
parseFacebookUtilsVersion  : "1.14.0",

There's 3 ways to register for my app

via mobile phone (my Parse app sends out a code to the number)
via email address ( my Parse app sends out an verification email that user has to click)
via facebook login
When users registers/logs in using FB account, it sends out a redundant verification email to the users because I fetch user's email from facebook and save it in the "email" column.

I believe this bug has been fixed in the Parse server (do not send out verification email when user logs in using OAuth).
I'm doing exactly the same thing in my iOS version of app and it has the correct behavior (no verification email);
however, using ParseFacebookUtils-Android I keep getting a verification email every time I log in via FB.

Is there a work around?

Much thanks in advance!

I am re-using one of the existing ticket in github under ParseFacebookUtils-Android repository which is archived
https://github.com/parse-community/ParseFacebookUtils-Android/issues/33

**Comment by mtrezza** [comment]
The repository  parse-community/ParseFacebookUtils-Android is archived because it has been deprecated. If you are still using it, you should migrate to the module that is now included in the Parse Android SDK.
