### ISSUE TITLE
 i/o failure

### ISSUE THREAD

**Issue by sjxuereb** [parse-community/Parse-SDK-Android#1184]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/releases). 

### Issue Description

With Android Parse SDK I am getting [ i/o failure ] when I try to upload an image file. I have also tried with a drawable converted to byte. I get the same result.  [ i/o failure ] 

However I manage to upload image [png/jpg] files with REST API successfully to my parse server. And I also manage to upload text files using Android Parse SDK Successfully. Just no image files etc.. The following works:

   byte[] data = "Working at Parse is great!".getBytes();
            ParseFile file = new ParseFile("resume.txt", data);

I have a very good internet connection and I have these in my manifest I can also create parse objects successfully.

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />

It is not a permissions issue as I manage to upload to text files to the same parse class via an authenticated user. 

### Steps to reproduce
 File dir = Environment.getExternalStorageDirectory();
            File yourFile = new File(dir, "DCIM/Camera/20181010_001137.png");

            if(yourFile != null) {
                Log.i("App Log", "File Found");
            } else {
                Log.i("App Error", "File NOT Found");
            }
            
            ParseFile file = new ParseFile(yourFile);

            // Upload the image into Parse Cloud
            file.saveInBackground(new SaveCallback() {
                public void done(ParseException e) {
                    if (e != null) {
                        Log.i("App Error", e.getMessage());
                    } else {
                        Log.i("App Log", "File Uploaded");
                    }
                }
            });

### Actual Outcome

With Android Parse SDK I am getting [ i/o failure ] when I try to upload an image file.  However I manage to upload PNG and JPG with REST API on the same server and associate them to Parse Objects successfully.

### Expected Outcome

I need a successful upload

### Environment

Parse Android SDK
- SDK version: Android Tiramisu (API LEVEL 33) Rev 2
- Parse-SDK-Android:parse:4.1.0"
- Operating system version: Android Studio Dolphin | 2021.3.1 Patch 1 On Windows 10 Home

Server
- Parse Server version: 5.4.0
- Operating system: -Ubuntu
- remote host on a url... via https

Database
- System (MongoDB or Postgres): MONGODB
- Database version: 6.0.3
- Local POD on same k8 cluster as parseserver

**Comment by mtrezza** [comment]
i/o failure points to a fundamental network issue between the app and the server, like a firewall or blocked connection / protocol / URL on your device.

**Comment by mtrezza** [comment]
i/o failure points to a fundamental network issue between the app and the server, like a firewall or blocked connection / protocol / URL on your device.
