### ISSUE TITLE
README Getting Started guide is out of date

### ISSUE THREAD

**Issue by edgarwideman** [parse-community/Parse-SDK-Android#1197]
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/releases).

### Issue Description
For Android Studio projects created in Android Studio Bumblebee | 2021.1.1 or newer, the JitPack repository needs to be added to the root level file `settings.gradle` instead of build.gradle. This has never been updated in the README, Getting Started section.

### Steps to reproduce
Create a new project in Android Studio Bumblebee | 2021.1.1 or newer. Follow the setup steps in the README. The steps don't match with what you need.

### Actual Outcome
A novice user will probably skip the jitpack dependency step when not able to make sense of the guide. The gradle sync will show success, but after digging in the Build output you will find error `Failed to resolve: com.github.parse-community.Parse-SDK-Android:parse:4.2.0`

### Expected Outcome
Gradle sync success with library imported

### Environment
Android Studio Flamingo | 2022.2.1 Patch 1

Parse Android SDK
- SDK version: `4.2.0`
- Operating system version: `Windows 11`

Server
- Parse Server version: ` #NotRelevant`
- Operating system: `NotRelevant`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `NotRelevant`

Database
- System (MongoDB or Postgres): `NotRelevant`
- Database version: `NotRelevant`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `NotRelevant`

### Logs
No logs, documents are incorrect, following the setup instructions in README will lead you nowhere.

This may be part of the problem with issue 1189 as well 
#1189

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.1](https://github.com/parse-community/Parse-SDK-Android/releases/tag/4.2.1)
