### ISSUE TITLE
Add support for uploading files from a content Uri

### ISSUE THREAD

**Issue by hej2010** [parse-community/Parse-SDK-Android#1206]
### New Feature / Enhancement Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).

### Current Limitation

Currently a ParseFile can only be created/uploaded using a `byte[]` or a `File`. 
When opening a file/document using an intent (https://developer.android.com/training/data-storage/shared/documents-files#open-file) the Uri can't always easily be converted into a File and it is often too large to store in a byte array.

### Feature / Enhancement Description

Add support for uploading files from a content/document Uri, e.g. with `new ParseFile(name, uri, contentType)`.

### Alternatives / Workarounds

Write the Uri data to a temp file and upload using `new ParseFile(file)`.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0](https://github.com/parse-community/Parse-SDK-Android/releases/tag/4.3.0)
