### ISSUE TITLE
Authenticate with Google

### ISSUE THREAD

**Issue by grumpy-dev** [parse-community/Parse-SDK-Android#185]
Hi,

I saw that some work has been done around login with third party authentication (logInWithInBackground and AuthData). But there is no example on how to perform a third party log-in. In my case, I would like to signup/signin user with Google account (makes sense for an Android SDK).

Is there a plan to have an equivalent of the ParseFacebookUtils but for Google,  or at least an example on how to implement a third party authentication ?

Thanks.

**Comment by grantland** [comment]
Right now we only support Facebook and Twitter authentication, but we're planning on opening up third party authentication soon!

**Comment by grumpy-dev** [comment]
Great news ! Eager to see that happen !

**Comment by jpventura** [comment]
Would it be OK submitting Google+ Authenticator for review?

**Comment by grumpy-dev** [comment]
any ETA ?

**Comment by grantland** [comment]
Sorry, but we don't have a public ETA :disappointed:

**Comment by Ralphilius** [comment]
Currently you can use Cloud code to achieve this. Check out my answer on SO here: http://stackoverflow.com/a/33631230/2552244

**Comment by grantgumina** [comment]
Has there been a breaking change in the Twitter auth code? I'm experiencing this issue right now. http://stackoverflow.com/questions/36185258/twitter-oauth-failure-error-parsing-a-meta-elements-content

**Comment by grantland** [comment]
@grantgumina You're issue isn't relevant to the original issue here and I see you've already posted this in another issue. I've responded in your issue, but please refrain from spamming other issues.

**Comment by Jawnnypoo** [comment]
@rogerhu I think this can be closed. If people want to support Google, they can create a third party lib for it and potentially make a PR or alert us and we could pull it in for community support.
