### ISSUE TITLE
saveEventually() enhancement

### ISSUE THREAD

**Issue by prempalsingh** [parse-community/Parse-SDK-Android#337]
Currently, if network connection is lost and the app is closed, saveEventually() will only try uploading the data the next time the app is opened. There should be an option to register a broadcast receiver for network connectivity which uploads the data in a background service even if the app is closed.

**Comment by grantland** [comment]
Technically if the app is closed, any BroadcastReceiver in the app will resume the eventually commands in the queue since calling it would cause the app to re-open.
