### ISSUE TITLE
How to clear out ParseUser, ParseInstallation etc

### ISSUE THREAD

**Issue by alexblack** [parse-community/Parse-SDK-Android#377]
A number of our users are facing significant issues using our app, hitting ParseBugs like #376, #267, #209 , #203 

Is there a way I can provide them with a `Reset` button?  Perhaps there is a creative or out of the box solution here.  Basically I think if I wipe some/all of their local Parse data, then they can get things working again.

**Comment by natario1** [comment]
Closing, most of linked issues are closed now, the request is not clear and anyway I don't think we are going to provide such thing.
