### ISSUE TITLE
Certificate Pinning

### ISSUE THREAD

**Issue by kingmatusevich** [parse-community/Parse-SDK-Android#378]
The SDKs should be compatible with pinned certificates for connecting to the Parse Servers, allowing for faster, safer deployment, particularly in small or internal deployments.

**Comment by grantland** [comment]
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/799#issuecomment-176958306

**Comment by rogerhu** [comment]
Feel free to submit a PR now that OkHttp3 is the standard base: https://github.com/square/okhttp/wiki/HTTPS#certificate-pinning

**Comment by natario1** [comment]
I guess this can be closed now that the builder is exposed? @Jawnnypoo

**Comment by Jawnnypoo** [comment]
Yep, good point.
