### ISSUE TITLE
ParseFile save fails on parser-server after migration: Unable to encode an unsaved ParseFile

### ISSUE THREAD

**Issue by smanikandan14** [parse-community/Parse-SDK-Android#384]
I am using parse-android SDK 1.13.0. I am able to upload file to parse's backend. 

But when i change my server endpoint to migrated end point, upload fails. 

```
{
    "code": 130,
    "error": "Invalid file upload."
}
```

I added console logs in file.js on parse-server i found the request.body is empty.

**Files.js processCreate req: [object Object] : {} : undefined**

```
var processCreate = function(req, res, next) {
console.log(" Files.js processCreate req:"+req+" : "+ JSON.stringify(req.body)+" : "+req.body.length
if (!req.body || !req.body.length) {
    next(new Parse.Error(Parse.Error.FILE_SAVE_ERROR,
         'Invalid file upload.'));
    return;
  }

```

Exception message shown on client side.

```
iIllegalStateException: Unable to encode an unsaved ParseFile
```

I am not sure if this is a client side issue or it on the parse-server side. But the request body is found empty.

**Comment by grantland** [comment]
If this was working with hosted Parse, but stopped working with Parse Server, it's most likely a Parse Server issue.

**Comment by natario1** [comment]
This appears to be solved in parse-server.
