### ISSUE TITLE
File upload using android sdk i/o failure

### ISSUE THREAD

**Issue by ishaan1995** [parse-community/Parse-SDK-Android#397]
The file upload not working when i try to upload files larger than 200kb(i am trying to upload pdf).
getting error--->
com.parse.ParseRequest$ParseRequestException: i/o failure
the saveinbackground() func with progressCallback shows 3/4 attempts after which i eventually get the i/o error
The error persist in the latest 'com.parse:parse-android:1.13.0' but does not occur in 1.10.0
But since parse is shutting down ,i have to use my self parse-server which requires 1.13.0 version
Is there a solution to this problem currently?

**Comment by grantland** [comment]
Could you provide a small working sample project that reproduces this issue as well as the full stack trace and logcat?

**Comment by ishaan1995** [comment]
Full Stack Trace------->
https://gist.github.com/ishaan1995/06a7c7abe83414ab4ceb

and i cannot upload the whole project as is a private repo,
below are the concerned files gist that are causing problem.

code.java -->https://gist.github.com/ishaan1995/16942130abe71f08c96d
parse initialize--> https://gist.github.com/ishaan1995/4a69af1f4c7d898303bb

i cannot use a previous version of android sdk as 1.13.0 is the one that supports own parse-server

**Comment by ishaan1995** [comment]
an update to my problem-->
image upload is working properly (any size upto 10mb)but i want to upload pdf`s which is causing problem in my case, if the size exceeds 100kb.

**Comment by grantland** [comment]
You don't need to upload your entire project, just a small concise project that reproduces your issue as well as any other relevant information required (Android version, emulator, device, etc.).

**Comment by ishaan1995** [comment]
git project test module-->
https://github.com/ishaan1995/TestUpload.git
https://github.com/ishaan1995/TestUpload
This contains the concise part which is causing problem.

**Comment by ishaan1995** [comment]
Did you find the problem @grantland ?

**Comment by ishaan1995** [comment]
Hey i need to develop an app asap using parse android sdk @grantland , so can you please resolve the bug?

**Comment by grantland** [comment]
Your repro seems to be missing a file to use. Could you provide it?

**Comment by ishaan1995** [comment]
[check_file.pdf](https://github.com/ParsePlatform/Parse-SDK-Android/files/138026/check_file.pdf)

You can use this file which is causing the above mentioned problem. @grantland

**Comment by ishaan1995** [comment]
Have you checked the uploaded file with my code? @grantland

**Comment by ishaan1995** [comment]
Have you found the problem @grantland ?
Still the same problem persists in the android version 1.13.0
I cannot use an older version since I am using my own parse-server.
Resolve the issue asap.
Thank You.

**Comment by grantland** [comment]
Unfortunately I will not have a chance to investigate this for a week or so. I've changed the tag to "needs investigation" to ensure the it doesn't get auto-closed.

**Comment by KTrizAdmin** [comment]
Are you free now to resolve the issue @grantland ?

**Comment by ishaan1995** [comment]
i guess its an bug in 1.13.0
Even using the latest parse-server 2.1.16 the problem still persists and gives an bad json response error 
Please resolve the issue/bug asap.
Can you try to look into my code once to verify if its an bug or my mistake @grantland ?
http://stackoverflow.com/questions/36059472/com-parse-parserequestparserequestexception-bad-json-response-or-i-o-failure-d/36059684#36059684
This is my stackoverflow question link

**Comment by ishaan1995** [comment]
Can you try to look into my code once to verify if its an bug or my mistake @grantland ?

**Comment by iamalroberts** [comment]
@ishaan1995 did you ever figure this out?

**Comment by ishaan1995** [comment]
No @iamalroberts , but this got resolved in 1.13.1, so i am closing the issue now.
