### ISSUE TITLE
[Parse Server] clientKey is optional if using Parse Server

### ISSUE THREAD

**Issue by hramos** [parse-community/Parse-SDK-Android#402]
A client key does not need to be configured in order to deploy a Parse Server. The Parse Android SDK does not currently support connecting to a clientKey-less Parse Server.

Parse keys can be configured in two ways in the Parse Android SDK:
- Via the `initialize()` constructor, or
- Configuring the keys in `AndroidManifest.xml`

However,
- Parse.java lacks a `initialize()` constructor that does not require a client key to be passed in,
- and, if using `AndroidManifest.xml`, the Parse Android SDK will throw an exception if the client key is missing

**Comment by grantland** [comment]
For now you can pass in `null` for the `clientKey` as a workaround.

**Comment by natario1** [comment]
I think this was fixed by @hermanliang , right?

**Comment by Jawnnypoo** [comment]
Yep, sure was
