### ISSUE TITLE
Huge bug!!! in Default ACL.  - not cloned. 

### ISSUE THREAD

**Issue by daviddayag** [parse-community/Parse-SDK-Android#403]
Create two objects.
get ACL of one and set read access.
save
get ACL of other and set read access.
save
ACL of other is saved with the first, unless you don't use  ParseACL.setDefaultACL
My guess is that the defaultACL is not beeing duplicated for each object.

**Comment by daviddayag** [comment]
Any word on this?

**Comment by natario1** [comment]
Yes, at first look the default ACL is not duplicated for each object.
I think that if you want to alter the default ACL you are supposed to call `new ParseACL(defaultACL)`.

I don’t think this is going to change since it would be breaking older apps.
