### ISSUE TITLE
Push Notification are received even though after unsubscribing

### ISSUE THREAD

**Issue by Sutirth** [parse-community/Parse-SDK-Android#410]
I use following code for while registering 

   currentInstallation  = ParseInstallation.getCurrentInstallation();
             currentInstallation.put("userId", userId);
            currentInstallation.saveInBackground();
            try {
                ParsePush.subscribeInBackground(userTeam.toLowerCase().toString());
        }catch (Exception e){
            Toast.makeText(this,"Parse Exception",Toast.LENGTH_SHORT).show();
        }

After logging out of my app I use:
 currentInstallation  = ParseInstallation.getCurrentInstallation();
            currentInstallation.remove("userId");
            currentInstallation.unpinInBackground();

```
        try {
            ParsePush.unsubscribeInBackground(userTeam.toLowerCase().toString());
        }catch (Exception e){
            //Toast.makeText(this, "Parse Exception", Toast.LENGTH_SHORT).show();
        }
```

**Comment by Jawnnypoo** [comment]
You would need to call `currentInstallation.saveInBackground()` after removing the `userId`  in order to update the installation on the backend and therefore no longer get the push
