### ISSUE TITLE
After returning to the app the first request to parse fails multiple times

### ISSUE THREAD

**Issue by diegolaballos** [parse-community/Parse-SDK-Android#426]
The first time I open the app it works well. If I return in less than 30 seconds it works also well but if I return later, then the first call to parse fails multiple times. (Then if I return after a ParseRequestException it works).

I'm using 1.13.0 android sdk and parse.com (not my own server)

<b>This is the first call log:</b>

Type : Request
Request-Id : 23
Url : https://api.parse.com/1/config
Method : GET
Headers : {X-Parse-Application-Id=XXXXXXXX, X-Parse-App-Display-Version=1.0.2, X-Parse-Installation-Id=22f1d01d-98ba-4185-9204-1e70aa45ff73, X-Parse-OS-Version=4.2.2, User-Agent=Parse Android SDK 1.13.0 (com.blackboxes.learny/3) API Level 17, X-Parse-Client-Key=XXXXXXXX, X-Parse-Client-Version=a1.13.0, X-Parse-Session-Token=r:3SUrt5xUFgElUsXK3Q11axw4C, X-Parse-App-Build-Version=3}

---

Type : Response
Request-Id : 23
Status-Code : 200
Reason-Phrase : OK
Headers : {X-Runtime=0.398417, Date=Thu, 24 Mar 2016 14:52:12 GMT, Access-Control-Allow-Origin=_, Content-Length=59, X-Parse-Platform=G1, Access-Control-Allow-Methods=_, Connection=keep-alive, Content-Type=application/json; charset=utf-8, Server=nginx/1.6.0}
Body : {
        "params": {
                    "needs_update": "1.0.2",
                    "categories_version": 1
                  }
        }

---

<b>And then when I return to the app about 30 seconds later or more I get this:</b>

Type : Request
Request-Id : 17
Url : https://api.parse.com/1/config
Method : GET
Headers : {X-Parse-Application-Id=XXXX, X-Parse-App-Display-Version=1.0.2, X-Parse-Installation-Id=22f1d01d-98ba-4185-9204-1e70aa45ff73, X-Parse-OS-Version=4.2.2, User-Agent=Parse Android SDK 1.13.0 (com.blackboxes.learny/3) API Level 17, X-Parse-Client-Key=XXX, X-Parse-Client-Version=a1.13.0, X-Parse-Session-Token=r:3SUrt5xUFgElUsXK3Q11axw4C, X-Parse-App-Build-Version=3}

---

 Type : Error
Request-Id : 17
Error : Read error: ssl=0x51056778: I/O error during system call, Connection reset by peer

---

Type : Request
Request-Id : 18
Url : https://api.parse.com/1/config
Method : GET
Headers : {X-Parse-Application-Id=XXXX, X-Parse-App-Display-Version=1.0.2, X-Parse-Installation-Id=22f1d01d-98ba-4185-9204-1e70aa45ff73, X-Parse-OS-Version=4.2.2, User-Agent=Parse Android SDK 1.13.0 (com.blackboxes.learny/3) API Level 17, X-Parse-Client-Key=XXXX, X-Parse-Client-Version=a1.13.0, X-Parse-Session-Token=r:3SUrt5xUFgElUsXK3Q11axw4C, X-Parse-App-Build-Version=3}

---

Type : Error
Request-Id : 18
Error : The target server failed to respond

---

Type : Request
Request-Id : 19
Url : https://api.parse.com/1/config
Method : GET
Headers : {X-Parse-Application-Id=XXXX, X-Parse-App-Display-Version=1.0.2, X-Parse-Installation-Id=22f1d01d-98ba-4185-9204-1e70aa45ff73, X-Parse-OS-Version=4.2.2, User-Agent=Parse Android SDK 1.13.0 (com.blackboxes.learny/3) API Level 17, X-Parse-Client-Key=XXXX, X-Parse-Client-Version=a1.13.0, X-Parse-Session-Token=r:3SUrt5xUFgElUsXK3Q11axw4C, X-Parse-App-Build-Version=3}

---

Type : Error
Request-Id : 19
Error : The target server failed to respond

---

Type : Request
Request-Id : 20
Url : https://api.parse.com/1/config
Method : GET
Headers : {X-Parse-Application-Id=XXXXXX, X-Parse-App-Display-Version=1.0.2, X-Parse-Installation-Id=22f1d01d-98ba-4185-9204-1e70aa45ff73, X-Parse-OS-Version=4.2.2, User-Agent=Parse Android SDK 1.13.0 (com.blackboxes.learny/3) API Level 17, X-Parse-Client-Key=XXXXX, X-Parse-Client-Version=a1.13.0, X-Parse-Session-Token=r:3SUrt5xUFgElUsXK3Q11axw4C, X-Parse-App-Build-Version=3}

---

Type : Response
Request-Id : 20
Status-Code : 200
Reason-Phrase : OK
Headers : {X-Runtime=1.259609, Date=Thu, 24 Mar 2016 14:27:40 GMT, Access-Control-Allow-Origin=_, Content-Length=59, X-Parse-Platform=G1, Access-Control-Allow-Methods=_, Connection=keep-alive, Content-Type=application/json; charset=utf-8, Server=nginx/1.6.0}
Body : {
        "params": {
                   "needs_update": "1.0.2",
                   "categories_version": 1
                  }
 } 

Sometimes the SDK throws a ParseRequestException depending on the number of HTTP request that fail. If it throws the ParseRequestException and I retry de query it works. Any idea? Thanks in advance

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
