### ISSUE TITLE
ClassCastException: HashMap cannot be cast to ParseUser

### ISSUE THREAD

**Issue by danielsanfr** [parse-community/Parse-SDK-Android#434]
Hello. I'm having this problem after updating the Parse SDK version **1.9** to **1.12+**.

First follows the error log:

> java.lang.ClassCastException: java.util.HashMap cannot be cast to com.parse.ParseUser
>     at br.com.domain.appname.model.CauseTheProblem.containsUserOnList(CauseTheProblem.java:213)
>     at br.com.domain.appname.features.ListViewHolder$1.onClick(ListViewHolder.java:64)
>     at android.view.View.performClick(View.java:4084)
>     at android.view.View$PerformClick.run(View.java:16966)
>     at android.os.Handler.handleCallback(Handler.java:615)
>     at android.os.Handler.dispatchMessage(Handler.java:92)
>     at android.os.Looper.loop(Looper.java:137)
>     at android.app.ActivityThread.main(ActivityThread.java:4745)
>     at java.lang.reflect.Method.invokeNative(Native Method)
>     at java.lang.reflect.Method.invoke(Method.java:511)
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>     at dalvik.system.NativeStart.main(Native Method)

Now follows a small piece of code that can cause the problem I'm having:

``` java
@ParseClassName("CauseTheProblem")
public class CauseTheProblem  extends ParseObject {
    public void addUserToList(String key) {
        addUnique(key, ParseUser.getCurrentUser());
        saveEventually();
    }
    public boolean containsUserOnList(String key) {
        String currentUserId = ParseUser.getCurrentUser().getObjectId();
        List<ParseUser> userList = getList(key);
        if (userList != null) {
            for (ParseUser user : userList) {
                if (currentUserId.equals(user.getObjectId())) {
                    return true;
                }
            }
        }
        return false;
    }
}
```

**The problem occurs in the line:** `List<ParseUser> userList = getList(key);`

In my class on the server data is being saved as follows (in key specifies):
`[{"objectId":"bEiN7zvSHK"},{"objectId":"3gXRzk6gvm"}]`

Searching the commit history here on GitHub I believe that this problem may have been introduced from the commit: cf58d030563c6f25113e53426aabe4b838229b90

Finally, in version **1.9** is working perfectly, but if you upgrade to a version **1.12+** happens this problem. _It was not me who developed this application, I'm just with the task of updates it, and it would be very difficult to change this structure._

**Comment by grantland** [comment]
Could you submit a failing unit test for this problem?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
