### ISSUE TITLE
I am receiving timeout often

### ISSUE THREAD

**Issue by leonardo-sj** [parse-community/Parse-SDK-Android#438]
I am receiving timeout often when I upload a file. I intercept the timeout message using parseinterceptors:0.0.2. The files have 1 Mb at most. Apparently, there is no reason to it happens and it is leading to unpredictable behaviour. 
In fact, it does not happen in iOS SDK, only in Android.
I already migrated and I am using Parse Server with Heroku.

I do not know if I increase the request time in Parse Server or in android sdk or how to do it.

These are some of gradle components of my project:

``` java
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.squareup.okhttp:okhttp:2.4.0'
compile 'com.facebook.android:facebook-android-sdk:4.10.1'
compile 'com.parse.bolts:bolts-android:1.3.0'
compile 'com.parse:parse-android:1.13.0'
```

**Comment by arun-94** [comment]
Facing the exact same issue. Its working fine on iOS but not on android. I'm uploading image files not more than 500kb but its giving timeout exception. Please let us know the fix ASAP as my app is going into production.

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
