### ISSUE TITLE
"com.parse.Channel" intent extras field is Null

### ISSUE THREAD

**Issue by xado85** [parse-community/Parse-SDK-Android#444]
I've tried to send push this way to a channel
curl -X POST -H "X-Parse-Application-Id: anApp" -H "X-Parse-Master-Key: aKey" -H "Content-Type: application/json" -d '{"data": { "title": "The Shining", "alert": "All work and no play makes Jack a dull boy."  },"channels":["aChannel"]}'  http://localhost:1337/parse/push

but everytime I want to extract  the parameter "com.parse.Channel", from the received intent,  the result is always a null value. Only "com.parse.Data" is initialized. Is this a client bug or a server Bug?

**Comment by grantland** [comment]
I'm not really sure if this is intended or a bug, but you can intercept the raw push `Intent` here to verify if the SDK is even receiving it: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParsePushBroadcastReceiver.java#L113

**Comment by xado85** [comment]
Unfortunatly I confirm this behaviour: the client doesn't recive the "com.parse.Channel" value. It's always null. So is this a server bug? In my system Every client subscribes with multiple channels and I was using this value to have different effect by the destination channel of the recived push.

**Comment by xado85** [comment]
Hi, now if somebody confirm it as a Server side missing value setting, is it possibile to move this issue in parse-server project or I need to create a new one?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
