### ISSUE TITLE
Got SSLPeerUnverifiedException when using Facebook sdk

### ISSUE THREAD

**Issue by super10793** [parse-community/Parse-SDK-Android#447]
Hi, all!
I'm using Facebook's AccountKit&Parse sdk, but always throw SSLPeerUnverifiedException when Parse.initialize();
java code like this:

public class AccountKitSampleApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        AccountKit.initialize(getApplicationContext());
        Parse.initialize(getApplicationContext(),"XXXX","XXXX");
    }
}

Has anyone faced a such issue?

**Comment by rogerhu** [comment]
Can you check again with the 1.14-1-SNAPSHOT?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
