### ISSUE TITLE
ParseRequestException: i/o failure

### ISSUE THREAD

**Issue by lgkbarros** [parse-community/Parse-SDK-Android#455]
I am trying to save some images to parse and link them to another ParseObject, but when I try to save them that exception happen.

> com.parse.ParseRequest$ParseRequestException: i/o failure
>                                                                               at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:289)
>                                                                               at com.parse.ParseRequest$2.then(ParseRequest.java:144)
>                                                                               at com.parse.ParseRequest$2.then(ParseRequest.java:138)
>                                                                               at bolts.Task$15.run(Task.java:917)
>                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>                                                                               at java.lang.Thread.run(Thread.java:841)
>                                                                            Caused by: java.io.FileNotFoundException: /document/image:2989: open failed: ENOENT (No such file or directory)
>                                                                               at libcore.io.IoBridge.open(IoBridge.java:409)
>                                                                               at java.io.FileInputStream.<init>(FileInputStream.java:78)
>                                                                               at com.parse.ParseFileHttpBody.writeTo(ParseFileHttpBody.java:43)
>                                                                               at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:52)
>                                                                               at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
>                                                                               at com.parse.interceptors.ParseLogInterceptor.intercept(ParseLogInterceptor.java:304)
>                                                                               at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:154)
>                                                                               at com.parse.ParseDecompressInterceptor.intercept(ParseDecompressInterceptor.java:30)
>                                                                               at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
>                                                                               at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
>                                                                               at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
>                                                                               at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
>                                                                               at com.parse.ParseRequest$3.then(ParseRequest.java:135)
>                                                                               at com.parse.ParseRequest$3.then(ParseRequest.java:132)
>                                                                               at bolts.Task$15.run(Task.java:917)
>                                                                               at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
>                                                                               at bolts.Task.completeAfterTask(Task.java:908)
>                                                                               at bolts.Task.continueWithTask(Task.java:715)
>                                                                               at bolts.Task.continueWithTask(Task.java:726)
>                                                                               at bolts.Task$13.then(Task.java:818)
>                                                                               at bolts.Task$13.then(Task.java:806)
>                                                                               at bolts.Task$15.run(Task.java:917) 
>                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
>                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
>                                                                               at java.lang.Thread.run(Thread.java:841) 
>                                                                            Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
>                                                                               at libcore.io.Posix.open(Native Method)
>                                                                               at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
>                                                                               at libcore.io.IoBridge.open(IoBridge.java:393)
>                                                                               at java.io.FileInputStream.<init>(FileInputStream.java:78) 
>                                                                               at com.parse.ParseFileHttpBody.writeTo(ParseFileHttpBody.java:43) 
>                                                                               at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:52) 
>                                                                               at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158) 
>                                                                               at com.parse.interceptors.ParseLogInterceptor.intercept(ParseLogInterceptor.java:304) 
>                                                                               at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:154) 
>                                                                               at com.parse.ParseDecompressInterceptor.intercept(ParseDecompressInterceptor.java:30) 
>                                                                               at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147) 
>                                                                               at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115) 
>                                                                               at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147) 
>                                                                               at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122) 
>                                                                               at com.parse.ParseRequest$3.then(ParseRequest.java:135) 
>                                                                               at com.parse.ParseRequest$3.then(ParseRequest.java:132) 
>                                                                               at bolts.Task$15.run(Task.java:917) 
>                                                                               at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) 
>                                                                               at bolts.Task.completeAfterTask(Task.java:908) 
>                                                                               at bolts.Task.continueWithTask(Task.java:715) 
>                                                                               at bolts.Task.continueWithTask(Task.java:726) 
>                                                                               at bolts.Task$13.then(Task.java:818) 
>                                                                               at bolts.Task$13.then(Task.java:806) 
>                                                                               at bolts.Task$15.run(Task.java:917) 
>                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
>                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
>                                                                               at java.lang.Thread.run(Thread.java:841) 

**ParseLogInterceptor**

05-12 15:38:30.121 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Type : Request
05-12 15:38:30.122 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Request-Id : 3
05-12 15:38:30.122 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Url : https://api.parse.com/1/files/image:2989
05-12 15:38:30.123 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Method : POST
05-12 15:38:30.125 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Headers : {X-Parse-Application-Id=IchsrB77459oKHabshyD4oVvJI0g92QTRfSMsAqX, X-Parse-App-Display-Version=1.0, X-Parse-Installation-Id=f1d64bda-795a-4f50-9b07-b3d739162538, Content-Length=0, X-Parse-OS-Version=4.4.4, User-Agent=Parse Android SDK 1.11.0 (br.com.xxx.xxx/1) API Level 19, Content-Type=null, X-Parse-Client-Key=Gi9Ksq9z4RxwXv3k81jPgogIIm7vEZ1lijvFjCHK, X-Parse-Client-Version=a1.11.0, X-Parse-Session-Token=r:OpKwrwewXxIXBFMikF92ffXQL, X-Parse-App-Build-Version=1}
05-12 15:38:30.153 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Body : Ignored
05-12 15:38:30.153 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: --------------
05-12 15:38:30.154 6726-7884/br.com.xxx.xxx W/System: Ignoring header Content-Type because its value was null.
05-12 15:38:30.167 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Type : Error
05-12 15:38:30.167 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Request-Id : 3
05-12 15:38:30.167 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: Error : /document/image:2989: open failed: ENOENT (No such file or directory)
05-12 15:38:30.167 6726-7884/br.com.xxx.xxx I/ParseLogInterceptor: --------------

**Comment by needsst** [comment]
#482

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
