### ISSUE TITLE
Parse AutomaticUser isn't saved between sessions after Parse Migration

### ISSUE THREAD

**Issue by eladrich** [parse-community/Parse-SDK-Android#470]
Our code uses the automatic user system of Parse. After migrating to our own local parse server Parse started generating a new user every time the application is opened, instead of using the existing one.
I suspect the problem to be in the LocalStorage which has been changed in the new API, as in #398.
But even after using the new API call the problem persists.

```
Parse.initialize(new Parse.Configuration.Builder(this)
                        .server("server-url") // The trailing slash is important
                        .applicationId("our-app-id")
                        .clientKey("our-client-id")
                        .enableLocalDataStore()
        .build()
        );
```

Automatic users is enabled as follows:

```
        ParseUser.enableAutomaticUser();
        ParseACL defaultACL = new ParseACL();
        //enable public read access.
        defaultACL.setPublicReadAccess(true);
        ParseACL.setDefaultACL(defaultACL, true);
```

**Comment by grantland** [comment]
If it worked with hosted Parse, but not parse-server, I'd recommend following up with parse-server to figure out what's different since the bug is most likely there.
