### ISSUE TITLE
Can't unpin object if another object has related to it.

### ISSUE THREAD

**Issue by Stream1988** [parse-community/Parse-SDK-Android#478]
Current parseObject.unpinInBackground don't work properly if some other pinned objects have relation to this parseObject.
unpinInBackground done without errors, but parseQuery.findInBackground keep return unpinned object until app restart. Other strange behavior that parseObject may returned by ParseQuery after second, third, N query. So it totally confused while developing.
I think unpinInBackground should ignore any relations like backend deleteOnBackground does. Or at least return an error

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
