### ISSUE TITLE
push_hash not receiving

### ISSUE THREAD

**Issue by daniyalnykaa** [parse-community/Parse-SDK-Android#479]
I have integrated parse code into my app and receiving push as expected.
After I click on notification it calls **ParseAnalytics.trackAppOpenedInBackground(intent);** event, that tracks the notification is opened.
But there is not tacking happening on my server. I have debugged the code and found that **push_hash** is missing.
What can be the issue?Can anyone please help me.

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
