### ISSUE TITLE
Android use ParseImageView load data from parse some image will be rotate

### ISSUE THREAD

**Issue by AnChiChang** [parse-community/Parse-SDK-Android#481]
I got a problem, after I saved image in ParseFile upload to parse.com, and download via dashboard to review, the image is correct.

However, after use Android app, use ParseImageView to set ParseFile, and loadInBackground. Some images will be rotate 90 degree. If I don't use ParseImageView, just use ImageView, get ParseFile convert to bitmap. Some images still rotate 90 degree.

I had research about Exif, but, I don't know how to get exif orientation information via ParseFile. Please kindly help. Thanks.

**Comment by rogerhu** [comment]
You should be able to convert the ParseFile back into a bytestream and examine the EXIF (http://guides.codepath.com/android/Accessing-the-Camera-and-Stored-Media#rotating-the-picture)
