### ISSUE TITLE
setCachePolicy & fromLocalDatastore 

### ISSUE THREAD

**Issue by devmsh** [parse-community/Parse-SDK-Android#483]
Why there is no equivalent out of the box CachePolicy implementation for LocalDatastore?

I already reviewed some codes here https://github.com/ParsePlatform/Parse-SDK-Android/issues/6#issuecomment-136863870, Is there any available implementations or gist related to this?

**Comment by natario1** [comment]
I’ll start working on #6 . I don’t think we should explicitly support `CachePolicy` when LDS is enabled, that would generate a lot of confusion. But once `query.fromNetwork()` is made public, you can emulate policies as explained in the comments there.
