### ISSUE TITLE
java.lang.IllegalArgumentException: You cannot increment a non-number.

### ISSUE THREAD

**Issue by iForests** [parse-community/Parse-SDK-Android#485]
I can simply reproduce this issue by the following code (`myNum` is a Number field in User object):

```
ParseUser parseUser = ParseUser.getCurrentUser();

parseUser.increment("myNum", 1);
parseUser.saveInBackground();

parseUser.increment("myNum", -1);
parseUser.saveInBackground();

parseUser.increment("myNum", 1);
// ^^^^^ Crash here with java.lang.IllegalArgumentException: You cannot increment a non-number.
```

I'm using Parse-SDK-Android 1.13.1 & Parse-Server 2.2.12. 

I think the problem here is, when `myNum` becomes 0 after several increment() operations, the next increment() will fail.

**Comment by natario1** [comment]
@iForests are you still in touch with this issue? I cannot reproduce it on latest version. Could you check if it still happens and provide more info or a sample app?

**Comment by Jawnnypoo** [comment]
Closing due to no response.
