### ISSUE TITLE
count operation fetches all the objects.

### ISSUE THREAD

**Issue by jyoon17** [parse-community/Parse-SDK-Android#495]
https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseRESTQueryCommand.java#L65-L71

https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseQuery.java#L1318

While encoding parameters to generate a http request for `count`, `setLimit(0)` is ignored. As a result, it fetches every object (at most 100 objects).

**Comment by natario1** [comment]
@jyoon17 I’m not sure I get it, could you elaborate? count is supposed to count all objects.

**Comment by jyoon17** [comment]
@natario1  Yes, it is supposed to count all objects but it is NOT supposed to fetch all objects. 

As you can see it here https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseQuery.java#L1313, `countInBackground` explicitly sets the `limit` parameter to zero in order to prevent from fetching all objects.

However, HTTP request encoder (https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseRESTQueryCommand.java#L65-L71) ignores the `limit` parameter when it sees `count` parameter.

As a result, it will generate something like this:

```
GET /1/classes/GameScore?count=1
```

instead of 

```
GET /1/classes/GameScore?limit=0&count=1
```

On the [server side](https://github.com/parse-community/parse-server/blob/f7af48db895f58edcdbca383a5a5e1458bf88a31/src/RestQuery.js#L141-L155), a server will [first find](https://github.com/parse-community/parse-server/blob/f7af48db895f58edcdbca383a5a5e1458bf88a31/src/RestQuery.js#L145) all the objects and then puts results under `results` since the `limit` parameter is non-zero (https://github.com/parse-community/parse-server/blob/f7af48db895f58edcdbca383a5a5e1458bf88a31/src/RestQuery.js#L478-L482).

Then the server will also [do counting](https://github.com/parse-community/parse-server/blob/f7af48db895f58edcdbca383a5a5e1458bf88a31/src/RestQuery.js#L147) and put the result under `count`.

The response would look like: 
```javascript
{
    "count": 11423,
    "results": [
          {"objectId": .... },
          {"objectId": .... },
          {"objectId": .... },
          {"objectId": .... },
          ...
    ]
}
```

I though fetching `results` is not desirable and please correct me if I am wrong.

**Comment by natario1** [comment]
I got it, thanks! I’ll look into this.

**Comment by natario1** [comment]
@jyoon17 thanks man, this was a nice catch, wonder how you noticed it.
