### ISSUE TITLE
SignUpCallBack not working after update to 1.13.1

### ISSUE THREAD

**Issue by maravilhosinga** [parse-community/Parse-SDK-Android#510]
I have recently updated my parse app to SDK 1.13.1 and now when i signup a new user it only callBack on done if there is same error or warnnig. But if the user is signed up with sucess, the callback does not notify and even session is still invalid. Help please

**Comment by Jawnnypoo** [comment]
This isn't a problem with the latest SDK, @rogerhu this can be closed

**Comment by rogerhu** [comment]
How'd we fix it?

**Comment by Jawnnypoo** [comment]
I just cannot reproduce it with the latest, so unless a test or sample is provided showing it occurring I think it was resolved somewhere along the way
