### ISSUE TITLE
saveInBackground() return a Task "faulted" when updating a ParseRelation

### ISSUE THREAD

**Issue by Toofoo** [parse-community/Parse-SDK-Android#515]
When I update a ParseRelation (adding or removing an item) and then save the ParseObject in background,  I receive en error everytime :  **java.lang.IllegalArgumentException: Operation is invalid after previous operation** 
Below a sample code:
`ParseUser user = ParseUser.getCurrentUser();`
  `user.getRelation("items").remove(item);`
`Task taskResult = user.saveInBackground();`
`Thread.sleep(15000);`
`log("task isfaulted? : " + taskResult.isFaulted() + " " + taskResult.getError());`

where "item" is another ParseObject already saved in Database.
The Remote database is correctly updated but the Task returned by the method saveInBackgound is faulted anyway. So I cannot chaine with others task depending on the result.

(using parse-android-1.13.1")

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
