### ISSUE TITLE
Parse SDK can't download files with whitespaces in the name.

### ISSUE THREAD

**Issue by dbychkov** [parse-community/Parse-SDK-Android#528]
Parse SDK for Android fails to download ParseFiles that have whitespaces in the name.

**Comment by natario1** [comment]
Any insight into this? I am actually able to download files with whitespace. Maybe OkHttp now cares about it?

**Comment by Jawnnypoo** [comment]
You are saying you are able, or are not?

**Comment by natario1** [comment]
@Jawnnypoo Sorry, I mean I am able, I can’t reproduce the issue myself. You get a `url` string with whitespace, but file is downloaded anyway, so I assume OkHttp cares about proper encoding. I don’t know where else the issue could be.

**Comment by Jawnnypoo** [comment]
Yeah, this may have just been something with one of the other HTTP implementations. I think it is fine to close since we know OkHttp handles it.
