### ISSUE TITLE
Parse localDataStore and Syncing with Parse-Server

### ISSUE THREAD

**Issue by hatpick** [parse-community/Parse-SDK-Android#534]
Let's say I have a custom class **MyClass** that has an **id** field, on one device (**A**) I create bunch of objects from this class and pin them to be accessible locally, I also save them on the server if network is available. Let's say the same user logs in on a different device (**B**) and fetches all the created records from the server and pins them to be accessible locally. Now, device **B** goes into airplane mode and has no network. User makes some changes on device **A** to a record with **id** equal to **1** at time **t1**. Now user makes another change to the same record (**id equal to 1**) on device **B** at time **t2** where t2>t1 while no network is available and pins the object. How can I sync the changes to the server and ultimately all the devices (**A** and **B**) when device **B** comes online, obviously in this case I want the record (with **id = 1**) have all the changes from device **B** because the changes are more recent (t2 > t1).

```
MyClass record = new MyClass();
MyClass.setId(1);
MyClass.setModifiedAt(new Date());
//set the rest of fields for this new Myclass 
if(networkIsAvailable()) {
  record.saveInBackground(new SaveCallback() {
     @Override
     public void done(ParseException e) {
        if(e == null) {
          record.pinInBackground();
        }
     }
} else {
   record.pinInBackground();
}
```

I have a receiver for network changes and can detect if a network is available, I want to sync my changes to the server (if they are more recent) and get changes from the server that are either new records or more recent changes.

Another question: How can I findInBackground and force it to get everything from the server not localDataStore even though it's enabled.

p.s: I know about saveEnevtually but I want to know when the save is done.

**Comment by hatpick** [comment]
Ok, I recently found this:
"There are a couple of side effects of enabling the local datastore that you should be aware of. When enabled, there will only be one instance of any given ParseObject. For example, imagine you have an instance of the "GameScore" class with an objectId of "xWMyZ4YEGZ", and then you issue a ParseQuery for all instances of "GameScore" with that objectId. The result will be the same instance of the object you already have in memory."

Is there any workaround for this? To be able to sync properly I need to compare the modification date of a local object to the modification date of its remote version (with the same objectId).

**Comment by natario1** [comment]
You could ask the server for the date you are looking for, for example with a cloud code function.

**Comment by hatpick** [comment]
It doesn't matter, as soon as it gets to the client, the in memory objects and server object will be the same.

**Comment by natario1** [comment]
@hatpick I mean asking only for the date string, not for the whole object.

**Comment by hatpick** [comment]
@natario1 I just want to compare modified dates of the cloud object and local object to see which one is more recent to either save that one in the cloud or update the local db. I don't know which field is updated to ask for that in particular.

**Comment by natario1** [comment]
`I need to compare the modification date of a local object to the modification date of its remote version` you can create a cloud code function that returns the updatedAt date.
