### ISSUE TITLE
Invalid type for ParseObject

### ISSUE THREAD

**Issue by songradinesh** [parse-community/Parse-SDK-Android#555]
Error : java.lang.IllegalArgumentException: invalid type for ParseObject: class org.json.JSONObject

I have moved parse server on "centOS" and also database from parse.com to mangoDB. I'm getting Above error when I make below request from my android app.

Note : I'm using android parse sdk(v1.13.1)

I have tried to add jsonObject as arraylist using addAllUnique() method because I have to store jsonObject as datatype of "array" in parse database.

Below i share my code :

JSONObject jsonObj = new JSONObject();

try {
    jsonObj.put("__type", "Pointer");
    jsonObj.put("className", className);
    jsonObj.put("objectId", objectId);
} catch (JSONException e1) {    e1.printStackTrace();}

ParseUser user = ParseUser.getCurrentUser();
user.addAllUnique("Keyword",Arrays.asList(jsonObj));
user.saveInBackground();

I have also tried user.addAll() method insted of addAllUnique() but it's also not working.

Before parse migration code is working fine for me.

Please help me to resolve this. Thanks

**Comment by natario1** [comment]
I don't think you should create json pointers this way. You can use `ParseObject.createWithoutData` instead.
