### ISSUE TITLE
Installation disappeares when sending a push notification with own GCMSenderId

### ISSUE THREAD

**Issue by tehmaestro** [parse-community/Parse-SDK-Android#566]
Hi. I am installing my app and setting it up as described here https://github.com/ParsePlatform/Parse-SDK-Android/issues/39 to use my own sender id for GCM push notifications. It works, the notifications are received, but the installation disappears from the _Installation class in Parse.
  Anyone else having this issue?

**Comment by Jawnnypoo** [comment]
Using a custom GCM sender ID is no longer supported, with the deprecation of GCM
