### ISSUE TITLE
ParseUser.getCurrentUser().fetch (in background, syncronous, any) doesn't fire call

### ISSUE THREAD

**Issue by RafaRuiz** [parse-community/Parse-SDK-Android#571]
Hello.

I have the latest version of Parse SDK for Android.

Suddenly, I don't know what's wrong (since I haven't changed my library since 1 month ago), when I call `ParseUser.getCurrentUser().fetch()` or any variable function (`fetchInBackground` for example), Parse SDK doesn't fire the call to get my User.

I'm testing it with Charles (http sniffer) and it's working with any other query, for example:
- `ParseQuery.getQuery(ParseUser.class).find()`
- `ParseQuery.getQuery("_Installation").find()`
- `ParseQuery.getQuery(ParseUser.class).get(ParseUser.getCurrentUser().getObjectId())` << this is working!! 
- all of them

why isn't Parse SDK firing my call?

EDIT:
It's working when I clear all data of the app, but that doesn't solve the problem since I can't tell all my users to clear the data.

EDIT2:
My `ParseUser.getCurrentUser()` is not `null` when using `.enableLocalDataStore()` but it's `null` when disabling the local data storage. Why?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.

**Comment by nouhoum-ibrahim-traore** [comment]
Hello Everybody. (I am talking about a android java problem with login or sign up using ParserUser). My problem was that the "signUpInbackground" and the "signInInBackground" weren't working. And the app crash when I try to logging with one of my users in the parse database.

Solution ::::: We resolve the problem by replace all the "undefinied" row  by 0. 
Then every thing work properly. 

NB: It is better for us in our project to initialize the "undefinied" row in some specific column by 0 or some thing else while SignUp a new user. 
We hope this will helps some persons to resolve some problems. Take care :-) .
