### ISSUE TITLE
I/ParseCommandCache: Network timeout in command cache

### ISSUE THREAD

**Issue by plaudev** [parse-community/Parse-SDK-Android#575]
Encountering this errmsg when connecting to parse in certain situations. I traced the error msg to [ParseCommandCache.java](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseCommandCache.java). I would greatly appreciate if you could point me in the right direction in getting it resolved.

I have a working android/parse app connecting to parse deployed over HTTPS on heroku. Connection to parse is successful when:

1. app running in emulator connecting to parse from home internet connection
2. app running on actual device connecting to parse using one specific public wifi (call it X)
3. app running on same device connecting to parse over cellular data

However when I run the same app in the same emulator, I encounter subject errmsg when:

1. app connecting to that same specific public wifi X mentioned above
2. app connecting to other public wifi, eg startbucks, libraries, etc.

What might the issue? If it is a matter of uncrecognized CA issues, then the app should not be able to connect via actual device using public wifi X. Where should I begin to look? Thanks.

**Comment by alexblack** [comment]
If you're using Heroku's free SSL, its based on SNI, and is not supported by all Android devices. Your error doesn't sound SSL related, but perhaps something is tripping up there?

We upgraded to their paid SSL endpoint.

**Comment by rogerhu** [comment]
Not sure there is enough info here to troubleshoot... Also we now allow you to pass in a custom OkHttp builder instance so any cert issue can be mitigated.  You should also check what Android version you are usjng
