### ISSUE TITLE
fetchInBackground returns no data but shows isComplete=true

### ISSUE THREAD

**Issue by paatz04** [parse-community/Parse-SDK-Android#589]
When the app starts I'm loading an object from local data store and get some data if it was cached before. Then I start a fetchInBackground request to get the most recent version of the object from our server. 

       `final Subscription subscription = getUser().getSubscription();

            if (subscription != null && !subscription.isDataAvailable())
            {
                try
                {
                    subscription.fetchFromLocalDatastore();
                } catch (ParseException e)
                {
                    e.printStackTrace();
                }
            }

            subscription.fetchInBackground(new GetCallback<ParseObject>()
            {
                @Override
                public void done(ParseObject object, ParseException e)
                {
                    if (e == null)
                    {
                        subscription.pinInBackground("subscription");
                    }
                }
            });`

The local fetch works, the fetch to the server doesn't work in this call. The strange thing is that the object contains isComplete=true. If i check isDataAvailable after this fetch it will return true, but estimatedData is empty, the whole object is empty.

When i do the same fetchInBackground later in a different view it succeeds and i get the object from the backend. 

I tried disabling the local query, or the pinning but nothing seems to do the trick.

What is going on  ?

Thanks!
All the best,
Patric

**Comment by natario1** [comment]
What changes between here and when you fetch it again in the different view?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
