### ISSUE TITLE
Publicize `ParseQuery.fromNetwork()` & allow multiple `find()`/`count()`

### ISSUE THREAD

**Issue by grantland** [parse-community/Parse-SDK-Android#6]
`ParseQuery.fromNetwork()` would be useful for toggling a query `.fromLocalDatastore()` <-> `.fromNetwork()` to mimic `CACHE_THEN_NETWORK` and `CACHE_ELSE_NETWORK` from query caching.

We already have the private API, so it'd be super easy to enable this.

We'd also need to remove the limitation of mutating an inflight query, which should be fine since we now since `ParseQuery.State` is passed to the controller as an immutable object.

**Comment by chrisjenx** [comment]
:+1: on creating a immutable state when creating a Task so we can keep mutating the builder.

Not sure if `fromLocalDataStore()` explicitly means `CACHE_THEN_NETWORK`. 

Generally when chaining queries, I want to know what they are doing. So I would concat `.fromLocalDatastore` with `.fromNetwork` to create a `CACHE_THEN_NETWORK`.

Exposing them should make it much easier for people to consume the tasks directly.

**Comment by satyadeepk** [comment]
@grantland I would like to pick up this. Can you be more specific on how `.fromLocalDatastore()` and `.fromNetwork()` corresponds to `CACHE_THEN_NETWORK` and `CACHE_ELSE_NETWORK` ?
Is it a chaining like @chrisjenx mentioned?

**Comment by grantland** [comment]
@satyadeepk Then it's yours! You are correct, this change would allow developers to emulate `CACHE_THEN_NETWORK` and `CACHE_ELSE_NETWORK` by using public `ParseQuery` APIs:

### CACHE_THEN_NETWORK

```java
final ParseQuery<ParseObject> query = // ...
query.fromLocalDatastore().findInBackground().continueWithTask((t) -> {
  // Update UI with results from LDS
  return query.fromNetwork().findInBackground();
}).continueWithTask((t) -> {
  // Update UI with results from Network
  return t;
});
```

### CACHE_ELSE_NETWORK

```java
final ParseQuery query = // ...
query.fromLocalDatastore().findInBackground().continueWithTask((t) -> {
  if (t.isFaulted) {
    return query.fromNetwork().findInBackground();
  }
  return t;
}).continueWithTask((t) -> {
  // Update UI with results
  return t;
});
```

s/`fromLocalDatastore()`/`setCachePolicy(CachePolicy.CACHE_ONLY)`/g and s/`fromNetwork()`/`setCachePolicy(CachePolicy.NETWORK_ONLY)`/g without LDS.

**Comment by satyadeepk** [comment]
Gotcha, I made `fromNetwork()` public and both your above use cases worked as expected. Mutable inflight query is not required for these two cases, because the second query happens after the first one is completed. Am I right?

Also, to make the query mutable inflight, I am thinking of bypassing `ParseQuery.checkIfRunning` in `ParseQuery.doWithRunningCheck` and all query methods like `whereEqualTo`. Do you forsee any side effects of doing that? Or is there a better way of doing it?

**Comment by grantland** [comment]
Yeah, that's correct. We've added the immutable `ParseQuery.State` which is in the beginning of all "inflight" entry points and is used for all query properties so there shouldn't be any issues with removing this limitation. In addition, it would allow a slightly faster approach for `CACHE_THEN_NETWORK`:

```java
ParseQuery<T> query = //...
final Task<Void> network = query.fromNetwork().findInBackground().continueWithTask((t) -> {
  // Update UI
  return t;
}, singleThreadExecutor);
final Task<Void> local = query.fromLocalDatastore().findInBackground().continueWithTask((t) -> {
  if (network.isCompleted) {
    return t;
  }
  
  // Update UI
  return t;
}, singleThreadExecutor);
```

**Comment by danielapsmaior** [comment]
Hi, I'm on version `'com.parse:parse-android:1.13.0'` and I can't see `query.fromNetwork()`. Was it reverted? On my ParseQuery.java, there is:

```
/* package */ ParseQuery<T> fromNetwork() {
    checkIfRunning();

    builder.fromNetwork();
    return this;
  }
```

**Comment by grantland** [comment]
Nothing was ever merged in for this

**Comment by natario1** [comment]
I am wondering how should `cancel()` behave. With this we allow for multiple `find/count` to be run at the same time, from the same query object. So either

- `cancel()` cancels the very last operation
- `cancel()` cancels all running operations

I think the second makes more sense. Any thoughts?

**Comment by chrisjenx** [comment]
@natario1 I thought Parse was dead?

**Comment by natario1** [comment]
@chrisjenx we are moving forward now, you can see there has been a lot of activity in this repo recently

**Comment by Jawnnypoo** [comment]
I think @chrisjenx may be referring to parse.com being shut down. Parse still lives on as an open source server which you can host yourself 👍

**Comment by rogerhu** [comment]
See https://medium.com/@flovilmart/long-live-parse-127e0308bd74
