### ISSUE TITLE
Adding ParsePushBroadcastReceiver in Manifest breaks LocalDatastore

### ISSUE THREAD

**Issue by ppilip** [parse-community/Parse-SDK-Android#601]
Hi all,

I have very unusual issue with LocalDatastore. So far I've been using it with no issues, but when I tried to implement PUSH notification receiver, whenever I add to Manifest.xml:
```
<receiver android:name="com.parse.ParsePushBroadcastReceiver" android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.OPEN" />
                <action android:name="com.parse.push.intent.DELETE" />
            </intent-filter>
        </receiver>
```
and query LocalDatastore for objects with:
```
ParseQuery<ModAvatar> query = ParseQuery.getQuery(ModAvatar.class);
        query.fromPin(PIN_COSTUME);
        query.getFirstInBackground(new GetCallback<ModAvatar>() {
            @Override
            public void done(ModAvatar object, ParseException e) {
                //do something nice
            }
        });
```
I get this error:
```
java.lang.ClassCastException: com.parse.ParseObject cannot be cast to com.mypackage.model.ModAvatar
```
When I remove receiver from Manifest.xml it works ok. This happens to all queries, not just to this ModAvatar class (which extends ParseObject of course).

Any help would be appreciated,
thanks.

**Comment by ppilip** [comment]
It got resolved by putting:
```
ParseObject.registerSubclass(ModUser.class);
ParseObject.registerSubclass(ModAvatar.class);
```

**before** this line in application onCreate() method:

```
Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId(APP_ID)
                .clientKey("")
                .server(server_address) 
                .enableLocalDataStore()
                .build());
```

**Comment by rogerhu** [comment]
Great!  Do you have a pull request that might make this exception better detectable?

**Comment by natario1** [comment]
We could throw an exception at `registerSubclass` if parse is already initialized. What do you think @rogerhu ?

**Comment by Jawnnypoo** [comment]
Sounds like we can at least close this issue since it was resolved.
