### ISSUE TITLE
Re-save installation is allowed if LDS is enabled 

### ISSUE THREAD

**Issue by hermanliang** [parse-community/Parse-SDK-Android#605]
Following PR #579  
The installation data will attempt to resave if installation is removed on the server.
But the resaving is not allowed when the local datastore is enabled due to [objectID is unchangeable](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/OfflineStore.java#L1459) in offline store.  
But I think [in this case](https://github.com/ParsePlatform/Parse-SDK-Android/pull/579#issuecomment-285926783) should be allowed .  

1. The `setObjectId(id)` seems only [updating the in-memory map](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/OfflineStore.java#L1462-L1474) (call sequences: [1](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/ParseObject.java#L1241) -> [2](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/ParseObject.java#L1268) -> [3](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/OfflineStore.java#L1454)). Maybe just unregister old object from the map when `setObjectId(null)` and allowing `ParseInstalltion` type only.
2. The `ParseInstallation` offline store (database) will be [updated](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/OfflineObjectStore.java#L61-L68) after resaving (call sequences: [1](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/ParseInstallation.java#L174) -> [2](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/CachedCurrentInstallationController.java#L58) -> [3](https://github.com/ParsePlatform/Parse-SDK-Android/blob/e0f096e850511e4dea7f1b0781186cf32e83e12b/Parse/src/main/java/com/parse/OfflineObjectStore.java#L61)). The code seems okay does not need to be changed.

Plz correct me if I'm wrong. 😄

**Comment by rogerhu** [comment]
Sounds ok but is it possible to make this consistent on iOS?

**Comment by hermanliang** [comment]
I think it is possible. I'll submit a PR to make this consistent on iOS. 😄
