### ISSUE TITLE
Should we expose ParseObject.fromJSON and ParseObject.toJSON ?

### ISSUE THREAD

**Issue by natario1** [parse-community/Parse-SDK-Android#618]
These methods already exist, and we would just need to have a special signature exposed to public, that throws when necessary and makes less assumptions on the sanity of input data, deal with hidden keys etc.

This would allow long time requested features such as passing `ParseObject` to cloud code, receiving `ParseObject` in response to cloud code functions, passing `ParseObject` via push notifications...
Moreover, the JS sdk already has similar methods.

What do you think? This looks easy but was never done, so I guess there’s something I am missing.
I found just a few comments in #84 .

*(it would also let you pass ParseObjects in Bundles, until we implement Parcelable. But that’s an extra and not the intended usage of this feature, as I see this)*

**Comment by Jawnnypoo** [comment]
Do we know if this is implemented in the iOS SDK?

**Comment by natario1** [comment]
I don’t know. After dealing with `Parcelable`, I would say that exposing `fromJSON` and `toJSON` does not seem a good idea, one can do pretty much everything with a JSON and that’s too much room for nasty errors. 

Yet it would be great to pass/get objects from cloud code functions (using JSONs internally)

**Comment by natario1** [comment]
Looking at the source it seems we would just need [_toFullJSON](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseObject.js#L266) in the JS sdk to be exposed - renamed.

Then it should be *already* possible to call

    ParseObject object = ParseCloud.callFunction(“function”, params);

or even

    List<ParseObject> list = ParseCloud.callFunction(“function”, params);

with no edits on our side.
