### ISSUE TITLE
Allow specifying a custom OkHttp client

### ISSUE THREAD

**Issue by Jawnnypoo** [parse-community/Parse-SDK-Android#620]
Since 1.14+ have a hard dependency on OkHttp, I think it would be great to expose the ability to specify the OkHttpClient to use. We would probably have to have them pass an OkHttpClient.Builder, so that we can add things to it as needed, and override things if necessary, but this would be great because we would then be exposing many things that were not previously exposed, such as HTTP timeouts, the ability to specify things like certificate pinning, and would eliminate the need for the class `ParseNetworkInterceptor`. 

What do you think @rogerhu ? I am happy to make a PR with this, keeping in mind backwards compatibility.

**Comment by rogerhu** [comment]
Yes absolutely.  That has been my thought all along to solve many of those cert-related issues.

We should just make sure to keep the docs updated too: https://github.com/ParsePlatform/docs

**Comment by rogerhu** [comment]
Agree in passing a builder instead of instance as well

**Comment by Jawnnypoo** [comment]
Closed with https://github.com/parse-community/Parse-SDK-Android/pull/628
