### ISSUE TITLE
error:135 deviceType must be specified in this operation Parse v 1.14.1

### ISSUE THREAD

**Issue by ClarkXP** [parse-community/Parse-SDK-Android#627]
Hi, I had the error in my app, exists any workaround for this error. 
The field 'deviceType' is read only in ParseInstallation, so I don't know how to fix it.
The unique solution was delete all application data and relogin, but I can't do it with my users.

**Comment by natario1** [comment]
Your users are experiencing this or just you in your test device?

ParseInstallation is often messed up when switching between debug / release APKs, different build variants, ... Ideally you would want debug APKs to connect to a different app with different app id.

**Comment by hermanliang** [comment]
It seems to be related to the #611, #607, and #579.
Have you done any similar operations?  
As @natario1 said, if you switch different parse server (database) with the same applicationId, it may cause problems by mixing the cached data.

**Comment by ClarkXP** [comment]
Yes, I can confirm that the issue started when I changed the build variant from debug to release. So the session was revoked and started the issue.

**Comment by hermanliang** [comment]
We may add this logic to the installation [re-save process](https://github.com/parse-community/Parse-SDK-Android/blob/38b1e29e0c78ac2c75972e6a9682e0b79dfbea6f/Parse/src/main/java/com/parse/ParseInstallation.java#L145-L156).
@rogerhu What do you think?

@ClarkXP during the meantime, you may trigger the re-save process yourself when you get code 135.
```java
if (e.getCode() == 135 && installation.getObjectId() == null) {
  installation.setObjectId("objectId"); // set a fake objectId
  installation.saveInBackground(); // it will trigger resave process due to object not found in the server
}
```
Note: `setObjectId` will not be available after #611 is merged.

**Comment by rogerhu** [comment]
Should be fixed now right?

**Comment by hermanliang** [comment]
@ClarkXP This issue should be resolved since v.1.15.2. If you still encounter the same issue, you can provide additional information to reopen it.
