### ISSUE TITLE
Handle redirects 

### ISSUE THREAD

**Issue by Jawnnypoo** [parse-community/Parse-SDK-Android#630]
Right now, within ParseHttpClient, line 68, we are modifying the OkHttp client builder to not allow for redirects. Do we have any idea why this is the case? There is a comment that links to https://quip.com/Px8jAxnaun2r which I cannot access and see what the reasoning is. 

@flovilmart Are you by chance able to see this document and see why this is important. Seems like some server configurations might want to be able to follow redirects and this seems like an unneeded restriction now that this library is not just for Parse.com

**Comment by Jawnnypoo** [comment]
Line I am referring to 
https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseHttpClient.java#L69

**Comment by rogerhu** [comment]
@wangmengyan95 ^^

**Comment by Jawnnypoo** [comment]
If we are getting no answer here, I think it would be best to remove this. I can think of no reasons why we would not allow redirects (it was probably something with parse.com and not parse server). Maybe we can have someone look into the iOS SDK and see if they are not allowing redirects?

**Comment by flovilmart** [comment]
The save object has a redirect

**Comment by Jawnnypoo** [comment]
@flovilmart Meaning redirects should not be allowed? I am envisioning that someone might have something like myapp.com which is hosted on Heroku, so its being directed to myapp.heroku.com and right now, the Android app would not allow for this as far as I can tell since we are not allowing redirects.

**Comment by flovilmart** [comment]
I don't believe it's good practices to have redirect, not sure if it would break to follow them. How is the iOS behaving?

**Comment by Jawnnypoo** [comment]
I am not familiar with the iOS SDK, but I imagine it does support redirects unless it is specifically disabling them like we are?

**Comment by rogerhu** [comment]
```  // Don't handle redirects. We copy the setting from AndroidHttpClient.
```

I suspect is was to make things consistent with AndroidHttpClient, which does not follow 302 links automatically.

http://blog.kosev.net/2011/01/follow-302-redirects-with-androidhttpclient/

I agree, I think we can take this thing out.

**Comment by rogerhu** [comment]
small hygiene but you can put your full name in the commit log?  :)
