### ISSUE TITLE
Updatig lib rom 1.15.2 to 1.15.3+ ParseTwitterUtils-Android No longer works

### ISSUE THREAD

**Issue by josuer** [parse-community/Parse-SDK-Android#652]
Hello, 
I'm always trying to use the latest lib of parse, but recenlty I updated the lib and my app no longer compiles.

Please Help this is the error I'm getting after I update the Parse lib to 1.15.3+
Error:Module 'com.parse:parsetwitterutils-android:1.10.5' depends on one or more Android Libraries but is a jar

Please help and thanks in advance.

**Comment by rogerhu** [comment]
Gotcha looks like we can't be aar only will fix

**Comment by rogerhu** [comment]
Can you try using `com.parse:parsetwitterutils-android:1.10.5@aar` and see if the problem goes away?

**Comment by josuer** [comment]
@rogerhu Now it is fixed! thank you very much.

**Comment by Jawnnypoo** [comment]
Sweet! So this can be closed now? Or do we need to modify the configuration there, @rogerhu

**Comment by rogerhu** [comment]
I simply made the default packaging to be AAR for Twitter utils

**Comment by mohamedbelhassen** [comment]
Hi @rogerhu 
Could you please tell me how you fixed this problem.
Being a beginner in this field, please describe all steps one by one.
cordially,
M.B
