### ISSUE TITLE
Adding core contributors

### ISSUE THREAD

**Issue by rogerhu** [parse-community/Parse-SDK-Android#657]
@hermanliang @Jawnnypoo and @natario1 have been the most active contributors to this repo. 

I nominate them to be granted merge access to this repo.  Major responsibilities require being stewards of this code base, reviewing pull requests, and helping to respond to issues reported.

I've finally gotten through the 6 Android repos and added Bintray upload automation now.    To release, the steps are basically:

1. Bump the version in the `Parse/build.gradle` file.

2. Update the README.md

3. In GitHub, tag a release (must be in the format of X.X.X).    
    a. Add a link to the compare between versions (i.e. https://github.com/parse-community/ParseUI-Android/compare/0.0.1...master)
   b. Note all changes in the release.    Give credit where credit is due.
   c. Once the release is created, Travis will build the files, upload them to jCenter, and syns to Maven Central automatically!  No more manual intervention steps.   We can move much faster now without all the work.

4. Update any documentation necessary from docs.parseplatform.org.

I wanted to get the repos in a state where core contributors and release managers didn't need to get Sonatype access just to deploy.  My goal all along has to expand the set so I'm not the only one merging across the 4-6 Android repos.

Thoughts?  Up for the challenge?

**Comment by hermanliang** [comment]
Yeah, I'd love to.
Thanks @rogerhu

**Comment by natario1** [comment]
Same for me, thanks @rogerhu ! I seem to have a lot of free time these days, so I definitely can help.

**Comment by Jawnnypoo** [comment]
Sounds great! 👍 Would love to help out further 😄

**Comment by rogerhu** [comment]
Thanks -- I've added you as a collaborators on this repo for now.  I'm happy to grant access to the other Android repos so let me know.

Can you guys update your GitHub profiles/Git commits with your full names? :)

**Comment by rogerhu** [comment]
@natario1 can you join Bintray.com via your GitHub handle?  I will invite you to the org too.

**Comment by natario1** [comment]
@rogerhu you mean the bintray org? I just linked my bintray account with github, [see](https://bintray.com/natario). Tell me if you need anything else

**Comment by hermanliang** [comment]
@rogerhu I think it would be helpful if we're permitted merge access to https://github.com/parse-community/docs repo to keep SDK documents up to date.
Thanks!
