### ISSUE TITLE
Android 7 i/o failure

### ISSUE THREAD

**Issue by pcegarra** [parse-community/Parse-SDK-Android#660]
Im getting this error with any android device 7.0 trying to do a (GET) Parse Query
Its working on 7.1.1 and <7.0

Internet its working on a webview..

I dont know whats happening
Any suggestion?

Tried with:
- com.parse:parse-android:1.14.1
- com.parse:parse-android:1.15.6

**Comment by Jawnnypoo** [comment]
Can you post the full stack trace here, and give more info on what device this occurred on? Also, are you sure you have the `INTERNET` permission in the manifest?

**Comment by pcegarra** [comment]
I tried with pixel emulator and real S7 device, i havent got more  strack trace than this i/o failure sorry.
Now im using 1.13.1 and its working nice

**Comment by Jawnnypoo** [comment]
Can you post what your parse query looks like?

**Comment by pcegarra** [comment]
public static void getPatrocinadores(final APIResponseListener listener) {
        ParseQuery<Patrocinador> parseQuery = ParseQuery.getQuery(API_PATROCINADOR);
        parseQuery.whereEqualTo("visible", true);
        parseQuery.findInBackground(new FindCallback<Patrocinador>() {
            @Override
            public void done(List<Patrocinador> objects, ParseException e) {
                if (e == null) {
                    listener.onSuccess(objects);
                } else {
                    listener.onError(e);
                }
            }
        });
    }

**Comment by Jawnnypoo** [comment]
Can you add a request interceptor to your Parse instance so that we can see what is going on with `1.15.6`? 

Add this to your `build.gradle` 
```
compile "com.squareup.okhttp3:logging-interceptor:3.7.0"
```
Then, when you are intiailizing Parse, can you add:

```
OkHttpClient.Builder builder = new OkHttpClient.Builder()
      .addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY));

Parse.Configuration config = new Parse.Configuration.Builder(context)
            .clientBuilder(builder)
            .build();
```

Then can you take a look in LogCat and see if it gives any additional information?

**Comment by pcegarra** [comment]
Ok im going to try

**Comment by pcegarra** [comment]
Yes, the server is using letsencrypt

**Comment by pcegarra** [comment]
Trying to create my own Trust manager Im getting this error only in Android 7:
`java.net.NoRouteToHostException: No route to host`

My Trust Manager:
`public final class CustomTrust {
    private final OkHttpClient client;

    public OkHttpClient getClient() {
        return client;
    }

    public CustomTrust() {
        X509TrustManager trustManager;
        SSLSocketFactory sslSocketFactory;
        try {
            trustManager = trustManagerForCertificates(trustedCertificatesInputStream());
            SSLContext sslContext = SSLContext.getInstance("TLS");
            sslContext.init(null, new TrustManager[]{trustManager}, null);
            sslSocketFactory = sslContext.getSocketFactory();
        } catch (GeneralSecurityException e) {
            throw new RuntimeException(e);
        }

        client = new OkHttpClient.Builder()
                .sslSocketFactory(sslSocketFactory, trustManager)
                .build();
    }
    

    /**
     * Returns an input stream containing one or more certificate PEM files. This implementation just
     * embeds the PEM files in Java strings; most applications will instead read this from a resource
     * file that gets bundled with the application.
     */
    private InputStream trustedCertificatesInputStream() {
        // PEM files for root certificates of Comodo and Entrust. These two CAs are sufficient to view
        // https://publicobject.com (Comodo) and https://squareup.com (Entrust). But they aren't
        // sufficient to connect to most HTTPS sites including https://godaddy.com and https://visa.com.
        // Typically developers will need to get a PEM file from their organization's TLS administrator.
        String comodoRsaCertificationAuthority = ""
                + "-----BEGIN CERTIFICATE-----\n"
                + "my key\n"
                + "-----END CERTIFICATE-----\n";
        String entrustRootCertificateAuthority = ""
                + "-----BEGIN CERTIFICATE-----\n"
                + "my key\n"
                + "-----END CERTIFICATE-----\n";
        return new Buffer()
                .writeUtf8(comodoRsaCertificationAuthority)
                .writeUtf8(entrustRootCertificateAuthority)
                .inputStream();
    }

    /**
     * Returns a trust manager that trusts {@code certificates} and none other. HTTPS services whose
     * certificates have not been signed by these certificates will fail with a {@code
     * SSLHandshakeException}.
     * <p>
     * <p>This can be used to replace the host platform's built-in trusted certificates with a custom
     * set. This is useful in development where certificate authority-trusted certificates aren't
     * available. Or in production, to avoid reliance on third-party certificate authorities.
     * <p>
     * <p>See also {@link CertificatePinner}, which can limit trusted certificates while still using
     * the host platform's built-in trust store.
     * <p>
     * <h3>Warning: Customizing Trusted Certificates is Dangerous!</h3>
     * <p>
     * <p>Relying on your own trusted certificates limits your server team's ability to update their
     * TLS certificates. By installing a specific set of trusted certificates, you take on additional
     * operational complexity and limit your ability to migrate between certificate authorities. Do
     * not use custom trusted certificates in production without the blessing of your server's TLS
     * administrator.
     */
    private X509TrustManager trustManagerForCertificates(InputStream in)
            throws GeneralSecurityException {
        CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
        Collection<? extends Certificate> certificates = certificateFactory.generateCertificates(in);
        if (certificates.isEmpty()) {
            throw new IllegalArgumentException("expected non-empty set of trusted certificates");
        }

        // Put the certificates a key store.
        char[] password = "password".toCharArray(); // Any password will work.
        KeyStore keyStore = newEmptyKeyStore(password);
        int index = 0;
        for (Certificate certificate : certificates) {
            String certificateAlias = Integer.toString(index++);
            keyStore.setCertificateEntry(certificateAlias, certificate);
        }

        // Use it to build an X509 trust manager.
        KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(
                KeyManagerFactory.getDefaultAlgorithm());
        keyManagerFactory.init(keyStore, password);
        TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(
                TrustManagerFactory.getDefaultAlgorithm());
        trustManagerFactory.init(keyStore);
        TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();
        if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) {
            throw new IllegalStateException("Unexpected default trust managers:"
                    + Arrays.toString(trustManagers));
        }
        return (X509TrustManager) trustManagers[0];
    }

    private KeyStore newEmptyKeyStore(char[] password) throws GeneralSecurityException {
        try {
            KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
            InputStream in = null; // By convention, 'null' creates an empty key store.
            keyStore.load(in, password);
            return keyStore;
        } catch (IOException e) {
            throw new AssertionError(e);
        }
    }

 
}`

And my builder:
`        CustomTrust customTrust = new CustomTrust();
        OkHttpClient.Builder builder = customTrust.getClient().newBuilder()`

**Comment by pcegarra** [comment]
Testing the response:

```
    public void run() throws Exception {

        Request request = new Request.Builder()
                .url("https:/mydomain.com/index.html")
                .build();

        Response response = client.newCall(request).execute();
        if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);

        Headers responseHeaders = response.headers();
        for (int i = 0; i < responseHeaders.size(); i++) {
            System.out.println(responseHeaders.name(i) + ": " + responseHeaders.value(i));
        }

        System.out.println(response.body().string());

    }
```

Response OK, if I change my keys to "fake keys" then I get an error, but... if its ok, why android 7 doesnt work? =\

**Comment by pcegarra** [comment]
Wtf this is crazy:
Added new code and I can log in with parse but getting my files I get this error:

`HTTP FAILED: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x86cfa340: I/O error during system call, Connection reset by peer`

Now my parse init...

`        ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                .tlsVersions(TlsVersion.TLS_1_2)
                .cipherSuites(

                        CipherSuite.TLS_DHE_RSA_WITH_AES_256_CBC_SHA)
                .build();

        CustomTrust customTrust = new CustomTrust();
        OkHttpClient.Builder builder = customTrust.getClient().newBuilder()
                .connectionSpecs(Collections.singletonList(spec))
                .addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY));;`

**Comment by pcegarra** [comment]
Wow! Finally its working, I need to add the CipherSuit from amazon:

 ```
       ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                .tlsVersions(TlsVersion.TLS_1_2)
                .cipherSuites(
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_256_CBC_SHA)
                .build();

        OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .connectionSpecs(Collections.singletonList(spec))
                .addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY));
```

**Comment by Jawnnypoo** [comment]
Glad you got it sorted out. Hopefully this will be a good reference for others who might come across the need to have this kind of configuration. 👍

**Comment by pcegarra** [comment]
New error with parse login:
D/OkHttp: <-- HTTP FAILED: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)], supported protocols=[SSLv3, TLSv1]

**Comment by pcegarra** [comment]
Fixed, just change the TLS version to 1_0:

`        ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                .tlsVersions(TlsVersion.TLS_1_0)
                .cipherSuites(
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_256_CBC_SHA)
                .build();`
