### ISSUE TITLE
Cannot put null value

### ISSUE THREAD

**Issue by iernie** [parse-community/Parse-SDK-Android#662]
Hi

This is more of a question to the SDK than an issue, but I was wondering why `null` values are not allowed in `ParseObject.performPut(key, value)`

`if (value == null) {
      throw new IllegalArgumentException("value may not be null.");
    }`

Why is that?
How are you supposed to remove/clear a value from a cell?

I have a pointer to a `ParseUser` on my `Installation` that gets set during login. I want to remove that pointer during logout, but cannot set it to null because of the exception. I tried using `.remove()`, but that did nothing.

I havnen't used the iOS SDK personally, but a colleague said he was able to just set the pointer to `null`.

**Comment by natario1** [comment]
`remove` should be what you are looking for... Is it possible that your installation failed to save after using remove?

**Comment by iernie** [comment]
@natario1 I thought about that too, but the other Boolean "loggedIn" gets set to `false` successfully.

My code looks like this:
```
ParseInstallation installation = ParseInstallation.getCurrentInstallation();
installation.put("loggedIn", false);
installation.remove("userId");
installation.saveInBackground(e -> {...});
```

and while "loggedIn" gets set to `false`, "userId" is still a pointer to the `ParseUser.getCurrentUser()` object which was set during login.

**Comment by hermanliang** [comment]
You may try to refresh dashboard page of your browser (not dashboard refresh button).
Or upgrade your parse dashboard to latest version.

**Comment by iernie** [comment]
@hermanliang You are completely right! A refresh of the browser shows that the cell has indeed been cleared! Thank you! I was only using refresh inside the dashboard.
