### ISSUE TITLE
Binary JAR not published v.1.15.6

### ISSUE THREAD

**Issue by hermanliang** [parse-community/Parse-SDK-Android#663]
The JAR download link in `README.md` is not accessible.
https://search.maven.org/remote_content?g=com.parse&a=parse-android&v=LATEST

Now it redirect to
https://repo1.maven.org/maven2/com/parse/parse-android/1.15.6/parse-android-1.15.6.jar

Since the SDK deploy process only publish aar and source jar now, so the download url response `404 Not Found`.
https://repo1.maven.org/maven2/com/parse/parse-android/1.15.6/

If the SDK need keep going to provide the JAR version, we should add the binary jar artifact to the auto-deploy process, upload to bintray then sync to maven.

Thoughts?

**Comment by rogerhu** [comment]
1) I think we just point people to https://oss.jfrog.org/artifactory/oss-snapshot-local/com/parse/parse-android/ going forward.

There is a way to pull the latest release using jFrog:
```http://oss.jfrog.org/artifactory/api/search/latestVersion?g=com.parse&a=parse-android```

It's not clear why we need the JAR files.  The AAR allows you use to use the ProGuard rules.    Also, once you use an AAR, the other dependencies assume you are also using AAR (i.e. ParseTwitterUtils as indicated in https://github.com/parse-community/Parse-SDK-Android/issues/652)

Just so everyone knows, we could add back the JAR by adding a similar section as https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/build.gradle#L179-L182 and add to https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/build.gradle#L273.

**Comment by hermanliang** [comment]
The JAR files may be used in the deprecated Android IDE (Eclipse + ADT).
But I believe that Android developers are now using Android Studio, maybe we don't need to release the binary JAR.
We may remove the JAR link or point it to bintray
https://bintray.com/parse/maven/com.parse%3Aparse-android/_latestVersion#files

**Comment by rogerhu** [comment]
Google 2 years ago discontinued support for Eclipse (https://developer.android.com/studio/tools/sdk/eclipse-adt.html).  

Gradle is now the preferred mechanism.  Larger codebases using Buck can still use AARs as well.

Should we simply point to the AAR files?

**Comment by Jawnnypoo** [comment]
I think it is just fine to point to the AAR files and even potentially remove the .jar

**Comment by rogerhu** [comment]
I believe Sonatype requires at least a `-sources.jar`.  Somehow I'm able to get away with not including `javadoc.jar` though.

http://central.sonatype.org/pages/requirements.html

```
If, for some reason (for example, license issue or it's a Scala project), you can not provide -sources.jar or -javadoc.jar , please make fake -sources.jar or -javadoc.jar with simple README inside to pass the checking. We do not want to disable the rules because some people tend to skip it if they have an option and we want to keep the quality of the user experience as high as possible.

```

**Comment by hermanliang** [comment]
Bintray doesn't seem to provide dynamic api to query and download the latest AAR. 
https://bintray.com/docs/api/#_content_downloading

I think we can simply point to 
https://dl.bintray.com/parse/maven/com/parse/parse-android/

**Comment by rogerhu** [comment]
iYeah..I'm assuming we don't get premium access and/or the $latest token
doesn't work?

**Comment by hermanliang** [comment]
No luck, content download url (from repo path) can't use $latest token, and the dynamic download is only for Premium repo. 😞 
So we can consider using the root folder link
https://dl.bintray.com/parse/maven/com/parse/parse-android/

**Comment by hermanliang** [comment]
Since JAR is no longer provided, I think we can close this issue now. Thanks :)
