### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzblr.class

### ISSUE THREAD

**Issue by Bharadhan** [parse-community/Parse-SDK-Android#664]

**Comment by hermanliang** [comment]
It doesn't seem to be an SDK issue.
Can you provide more details?

**Comment by Jawnnypoo** [comment]
This is likely a Multidex setup issue. Make sure you have set up multidex properly.

**Comment by hermanliang** [comment]
@Bharadhan I'm closing this issue due to lack of description. You can provide additional information to reopen it. Thank you!
