### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: Could not store file.

### ISSUE THREAD

**Issue by sandeep2242** [parse-community/Parse-SDK-Android#670]
I am working on Parse using Heroku server. last night my Images was uploading fine (all other data is uploading fine ie string ,int etc), but this morning there was an error in uploading images and the error was ie
com.parse.ParseRequest$ParseRequestException: Could not store file.  
` final ParseObject productDetails = new ParseObject("VendorInv");

            productDetails.put("productMrp", mrp2);
            productDetails.put("productName", name2);
            productDetails.put("productDetails", details2);
           // productDetails.put("size", size2);
            productDetails.put("type", type2);
            productDetails.put("color", color2);

            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            // Compress image to lower quality scale 1 - 100
            cropped.compress(PNG, 100, stream);
            byte[] image = stream.toByteArray();

            // Create the ParseFile
            final ParseFile file = new ParseFile(name2 + ".png", image,"image/png");
            file.saveInBackground(new ProgressCallback() {
                @Override
                public void done(Integer percentDone) {
                    Log.i("Parse", percentDone.toString());
                }
            });
            file.saveInBackground(new SaveCallback() {
                @Override
                public void done(ParseException e) {
                    if (e == null) {
                        productDetails.put("productImage", file);

                        try {
                            productDetails.save();

                            String obj = productDetails.getObjectId();

                            ParseObject pd = ParseObject.createWithoutData("Vendors", objId);

                            ParseRelation<ParseObject> pr = pd.getRelation("vendorInv");

                            pr.add(ParseObject.createWithoutData("VendorInv", obj));

                            pd.saveInBackground(new SaveCallback() {
                                @Override
                                public void done(ParseException e) {
                                    if (e == null) {
                                        Log.i("Parse", "Save Succeeded");
                                    } else {
                                        Log.i("Parse", e.toString());
                                    }
                                }
                            });
                        } catch (ParseException e1) {
                            e1.printStackTrace();
                        }
                    } else {
                        Log.i("sand", e.toString());
                    }
                }
            });`  
**EDIT**  
```
`final ParseObject productDetails = new ParseObject("VendorInv");
            if (EorF) {                   // Electronics
                productDetails.put("productMrp", mrp2);
                productDetails.put("productName", name2);
                productDetails.put("productDetails", details2);
                productDetails.put("type", item2);
                productDetails.put("model", pModel2);
                productDetails.put("color", colorId);


            } else {                           // fashion
                productDetails.put("productMrp", mrp2);
                productDetails.put("productName", name2);
                productDetails.put("productDetails", details2);
                productDetails.put("size", item1);
                productDetails.put("type", item2);
                productDetails.put("color", colorId);
            }

            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            if (cropped != null) {
                cropped.compress(PNG, 100, outputStream);
                byte[] imgs = outputStream.toByteArray();

                ParseFile file = new ParseFile("sandeep.png", imgs);
                file.saveInBackground(new SaveCallback() {                            //error
                    @Override
                    public void done(ParseException e) {
                        if (e == null) {
                            Log.i("Parse", "Save Succeeded");
                        } else {
                            Log.i("Parse", "not Succeeded");
                        }
                    }
                });
            } else {
                Log.i("Parse", "is null");
            }

            try {
                productDetails.save();

                obj = productDetails.getObjectId();

                ParseObject pd = ParseObject.createWithoutData("Vendors", objId);

                ParseRelation<ParseObject> pr = pd.getRelation("vendorInv");

                pr.add(ParseObject.createWithoutData("VendorInv", obj));

                pd.saveInBackground(new SaveCallback() {
                    @Override
                    public void done(ParseException e) {
                        if (e == null) {
                            Log.i("Parse", "Save Succeeded");
                        } else {
                            Log.i("Parse", e.toString());
                        }
                    }
                });
            } catch (ParseException e1) {
                Log.i("Parse23", e1.toString());
            }`
```

**Comment by natario1** [comment]
Looks like an error within your files controller in parse-server... Why are you saving the file twice? To define both callbacks you should use `file.saveInBackground(progressCallback, saveCallback)`.

**Comment by sandeep2242** [comment]
It was just to check wether r it saves or not. So what should i do to solve this problem?

**Comment by sandeep2242** [comment]
@natario1 I'm stucked here for couple of days , please any help would be greatly appereciated.

**Comment by natario1** [comment]
I think this is a server issue, we send the data and get the response. Files controller is not able to save, [link](https://github.com/parse-community/parse-server/blob/d5940b17b6914f04462420812aed9efe54a2b37f/src/Routers/FilesRouter.js#L93).

Might be related parse-community/parse-server#3830

Do you get any info in parse-server logs?

Remove one of the `saveInBackground`, and try to reduce the file size (crop the image, compress with lower quality, ...). If it works maybe you have to increase the `maxUploadSize` in parse server.

**Comment by sandeep2242** [comment]
I have removed saveInBackground but still it's not working, and i think size is not a 
problem , bcoz yesterday only i have uploaded same images in parse.

**Comment by natario1** [comment]
Do you get any logs in parse-server when the upload fails?

**Comment by sandeep2242** [comment]
2017-05-20T15:04:29.109653+00:00 heroku[router]: at=info method=POST path="/parse/classes/VendorInv" host=mainandroid.herokuapp.com request_id=efbb6d7a-c87f-4428-b4fc-6b258d5d69b3 fwd="103.249.239.170" dyno=web.1 connect=1ms service=26ms status=201 bytes=615 protocol=https
2017-05-20T15:04:31.211260+00:00 heroku[router]: at=info method=PUT path="/parse/classes/Vendors/4pckZ6nRQb" host=mainandroid.herokuapp.com request_id=7903bbb2-f987-450c-a62d-4beb2f2e1c53 fwd="103.249.239.170" dyno=web.1 connect=1ms service=45ms status=200 bytes=507 protocol=https
2017-05-20T15:05:48.941335+00:00 heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=POST path="/parse/files/bxhxjc.png" host=mainandroid.herokuapp.com request_id=5434c55f-63e6-4089-8619-61633a05f0f0 fwd="103.249.239.170" dyno=web.1 connect=1ms service=76021ms status=499 bytes=0 protocol=https
2017-05-20T15:05:52.482564+00:00 heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=POST path="/parse/files/bxhxjc.png" host=mainandroid.herokuapp.com request_id=6d710a54-c105-4fd8-a704-5be7cb99d5d6 fwd="103.249.239.170" dyno=web.1 connect=1ms service=65001ms status=499 bytes=0 protocol=https
2017-05-20T15:06:46.246706+00:00 heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=POST path="/parse/files/bxhxjc.png" host=mainandroid.herokuapp.com request_id=384f34fe-cd90-47bf-b32a-e9ddbc660fa9 fwd="103.249.239.170" dyno=web.1 connect=9ms service=47449ms status=499 bytes=0 protocol=https
2017-05-20T15:26:19.672926+00:00 heroku[router]: at=info method=POST path="/parse/classes/Array" host=mainandroid.herokuapp.com request_id=5d8bf191-d8ea-4d3d-b99d-876f16d66200 fwd="103.249.239.170" dyno=web.1 connect=1ms service=255ms status=200 bytes=961 protocol=https
2017-05-20T15:26:20.132633+00:00 heroku[router]: at=info method=POST path="/parse/classes/VendorInv" host=mainandroid.herokuapp.com request_id=24bb960f-4fe4-40f3-81e7-bdecabd3b986 fwd="103.249.239.170" dyno=web.1 connect=1ms service=43ms status=201 bytes=615 protocol=https
2017-05-20T15:26:20.734503+00:00 heroku[router]: at=info method=PUT path="/parse/classes/Vendors/4pckZ6nRQb" host=mainandroid.herokuapp.com request_id=bfaa4d2d-3261-42df-9bb3-e7a1e8933fc8 fwd="103.249.239.170" dyno=web.1 connect=1ms service=52ms status=200 bytes=507 protocol=https
2017-05-20T15:26:52.114333+00:00 heroku[router]: at=info method=POST path="/parse/files/cuucufu.png" host=mainandroid.herokuapp.com request_id=444805b5-7d94-4d3c-9520-2748ee3f11eb fwd="103.249.239.170" dyno=web.1 connect=1ms service=29624ms status=400 bytes=520 protocol=https
2017-05-20T15:56:55.714754+00:00 heroku[router]: at=info method=GET path="/" host=mainandroid.herokuapp.com request_id=2dac1ffb-bbdb-4ed3-92ae-d521c865929f fwd="103.249.239.170" dyno=web.1 connect=0ms service=30ms status=200 bytes=206 protocol=https
2017-05-20T15:56:56.439012+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=mainandroid.herokuapp.com request_id=2bc20d21-f2ed-4dd8-891b-3f0e45187320 fwd="103.249.239.170" dyno=web.1 connect=0ms service=2ms status=404 bytes=174 protocol=https

**Comment by sandeep2242** [comment]
@natario1 any idea whats going on?

**Comment by natario1** [comment]
Nope. Let’s wait to see if someone else can help you, but I think you’ll get better help on parse-server. Looks like a configuration issue.

By the way, in the original comment you had pasted more lines of logs, now you left just one, but some of these were meaningful (the ones with `at=warning`). I’d suggest to edit the comment again to include them.

**Comment by sandeep2242** [comment]
@natario1 Thanks for looking into my problem. I am unable find any logs regarding warning, and in addition to that I can upload String ,Integers and array  but not Images.

**Comment by DanGTZ** [comment]
@sandeep2242 does this happen for any file you try to save or only when file size exceed a certain value? Do you have a very simple ParseFile code saving example that produce the issue?

**Comment by sandeep2242** [comment]
@DanGTZ  the only thing I am saving is an image , which i have converted into a file

**Comment by DanGTZ** [comment]
@sandeep2242 I've updated my comment, my question is about file size, not file type.

**Comment by Jawnnypoo** [comment]
Instead of `Log.i("Parse", e.toString());` do `e.printStackTrace();` and look through the Android Monitor and see if you can see what the exact exception is.

**Comment by sandeep2242** [comment]
@DanGTZ file size is 200kb

**Comment by sandeep2242** [comment]
@Jawnnypoo  when i checked my parse logs it shows , Quota exceeded ,Could not store file

**Comment by Jawnnypoo** [comment]
So I suppose that is your issue then. You will have to get more storage space from your provider.

**Comment by sandeep2242** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25986690/26552728/0585ad3a-44a6-11e7-9484-002e81379e65.png)

@Jawnnypoo  please can u check my db stats and please tell me wether i have to change my sandbox plans

**Comment by Jawnnypoo** [comment]
No I cannot. I have no access to things like that. You need to speak with whoever set up your Parse server instance, more than likely you have exceeded your limits on mLab or whatever provider you are using for MongoDB. This is the tracker just for the Android SDK, if you need help with server stuff, go ahead and open an issue on the server issue tracker.

**Comment by sandeep2242** [comment]
@Jawnnypoo I have opened But no one is bothering to reply. Btw Thank you.

**Comment by flovilmart** [comment]
@sandeep2242 not sure what you're talking about... https://github.com/parse-community/parse-server/issues/3839 But yes, if you think we don't take the time to respond to you, that's fine.

**Comment by sandeep2242** [comment]
@flovilmart  I have created my database 3 times and every time parse logs shows Could not store file,quota exceeded.

**Comment by flovilmart** [comment]
Did you ever mentioned that? No I don't think so. Also, the error you have is a mongoDB error, not a parse-server error. Perhaps you should investigate it. And as mentioned many time, you should store your files on S3 or something similar, not in DB!

**Comment by sandeep2242** [comment]
@flovilmart  I'll investigate more into it. Thank You

**Comment by jadhavmanoj** [comment]
@flovilmart @sandeep2242 do you guys find any solution to this problem. I am facing the same issue.

any help appreciated.

Thanks
