### ISSUE TITLE
Can't Build APK or generate signed APK starting today

### ISSUE THREAD

**Issue by paatz04** [parse-community/Parse-SDK-Android#671]
Hey, 

as of today i can't create an APK anymore. I can still run and build on the simulator and device. 

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/parse/BuildConfig.class
```

This is the error I get when I'm trying to build an APK. I guess it's related to some sort of dependency issue. I've tried to go through the dependence tree, I tried of course clean and rebuild, i tried older version. I'm on the newest PARSE SDK

Any hints ?
Thanks in advance.

**Comment by hermanliang** [comment]
Can you provide your `build.gradle` dependency configuration?

**Comment by hermanliang** [comment]
It seems to be relevant to https://github.com/parse-community/ParseLiveQuery-Android/issues/60#issuecomment-301954907 if ParseLiveQuery is included in dependencies.

**Comment by paatz04** [comment]
hey, i'll attach it as soon as im back on my mac. thanks for the quick reply!
live query is indeed a dependency
cheers

On May 23, 2017 5:15 PM, Herman Liang <notifications@github.com> wrote:

It seems to be relevant to parse-community/ParseLiveQuery-Android#60 (comment)<https://github.com/parse-community/ParseLiveQuery-Android/issues/60#issuecomment-301954907> if ParseLiveQuery is included in dependencies.

**Comment by Jawnnypoo** [comment]
I think this is partially because LiveQuery and the Parse SDK both use the same package name. We honestly should move toward LiveQuery living under a different package if possible.

**Comment by hermanliang** [comment]
@paatz04 This issue has been resolved in the latest LiveQuery.
Now you may declare the dependencies like this
```groovy
dependencies {
    compile 'com.parse:parse-android:1.15.7'
    compile 'com.parse:parse-livequery-android:1.0.4@aar'
}
```
