### ISSUE TITLE
How to check Android SDK version during run time? 

### ISSUE THREAD

**Issue by bfjfm2** [parse-community/Parse-SDK-Android#680]
How to check Android SDK Version in during run time?

iOS Client SDK Version can be checked at  https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/PFConstants.h

Thanks,

**Comment by hermanliang** [comment]
com.parse.BuildConfig.VERSION_NAME

**Comment by bfjfm2** [comment]
Is it public property? I tried to assign to a string, it is not showing.

String parseVersionName = com.parse.BuildConfig.VERSION_NAME; // Not showing

String myAppVersionName = com.myapp.BuildConfig.VERSION_NAME; // showing

**Comment by hermanliang** [comment]
What do you mean by no showing?
I have no idea because it works fine in my own project.

**Comment by bfjfm2** [comment]
@hermanliang  Just found it. We using Old SDK Version 1.13.1 and it is not showing once we update to latest SDK 1.15.7 it is showing.  
Thanks
