### ISSUE TITLE
Unsupported method when Local Datastore is enabled.

### ISSUE THREAD

**Issue by yefengfreedom** [parse-community/Parse-SDK-Android#681]
parseQuery.setCachePolicy(ParseQuery.CachePolicy.NETWORK_ELSE_CACHE).

hi,I have called Parse.enableLocalDatastore(app) in application onCreate() method.
but this still prompt this message.

so I check the source code, then I see 
public Builder<T> setCachePolicy(CachePolicy cachePolicy) {
        throwIfLDSEnabled();
        this.cachePolicy = cachePolicy;
        return this;
      }

private static void throwIfLDSEnabled() {
    throwIfLDSEnabled(false);
  }

private static void throwIfLDSEnabled(boolean enabled) {
    boolean ldsEnabled = Parse.isLocalDatastoreEnabled();
    if (enabled && !ldsEnabled) {
      throw new IllegalStateException("Method requires Local Datastore. " +
          "Please refer to `Parse#enableLocalDatastore(Context)`.");
    }
    if (!enabled && ldsEnabled) {
      throw new IllegalStateException("Unsupported method when Local Datastore is enabled.");
    }
  }

why   throwIfLDSEnabled(false)  ?
is this a bug? or?

**Comment by hermanliang** [comment]
In fact, `setCachePolicy` is not supported when LDS is enabled.
Please refer to 
http://docs.parseplatform.org/android/guide/#caching-queries
and
http://docs.parseplatform.org/android/guide/#local-datastore.
then use `pinInBackground()` and `fromLocalDatastore()` instead.

**Comment by yefengfreedom** [comment]
get it. thanks.
