### ISSUE TITLE
Introduce a way to disable retries

### ISSUE THREAD

**Issue by frangulyan** [parse-community/Parse-SDK-Android#683]
Currently there is no way to disable the retries of a parse request, although the developers understand that it is needed ([here is a TODO](https://github.com/parse-community/Parse-SDK-Android/blob/0c3009afd0070fc7867f94d3a11f38195382a27d/Parse/src/main/java/com/parse/ParseRESTCommand.java#L189)). Would be nice to have it per command type (I need to disable it for cloud functions only).

**Comment by Jawnnypoo** [comment]
This is now configurable at a global level.

**Comment by JacobJT** [comment]
@Jawnnypoo Where is this configurable? I can't find it. Global to the Android Client or global to the Parse-Server instance?

**Comment by addisonElliott** [comment]
It is configurable in Android. Look at the Android API reference and you should see it in the ClientBuilder instance.

I'd give you a link if I wasn't on my mobile device. Let me know if you can't find it and I'll give you a link

**Comment by JacobJT** [comment]
I finally found the link... http://parseplatform.org/Parse-SDK-Android/api/com/parse/Parse.Configuration.Builder.html

Is the API link broken on the parseplatform page though?

http://parseplatform.org/Parse-SDK-Android/api/  This is the link provided at http://parseplatform.org/

It seems rather sparse of information. Had 4 classes with a couple of methods each, and I couldn't figure out how to get to like the core Parse classes. Whereas 

Sorry, I'm more of an iOS developer, and am not very familiar with the Android API. But I couldn't find a page more like what I was looking for, such as this [package summary](http://parseplatform.org/Parse-SDK-Android/api/com/parse/package-summary.html)

I know you're not supposed to discuss separate issues, particularly in a completely unrelated closed issue thread, but I'm also not sure if this actually is an issue nor where I should post it if it is.

**Comment by addisonElliott** [comment]
@JacobJT You did find an issue with the documentation. I just recently submitted a PR to fix publishing the API docs to GitHub pages. However, there was recent changes in Parse-SDK-Android repository regarding GCM so I think that is related.

If you can, please submit an issue regarding this. I will try to find time to work on this.

**Comment by franalt** [comment]
Hey guys, is there a way to disable retries on JS?
