### ISSUE TITLE
Login with facebook succesfully but if I close the app and open it again, the ParseUser.getCurrentUser() is null

### ISSUE THREAD

**Issue by josuer** [parse-community/Parse-SDK-Android#686]
Hello, I'm havig a big issue with some users, These users log in with  ParseFacebookUtils.logInInBackground and everything goes fine, the app opens and all the request to the cloud are working great, but when they close the app and re-open it ParseUser.getCurrentUser() is null and not keeping the session live.
Any idea of what is going on? Seems like the user is working great when the user logs in but it is never stored...
Any help would be appriciated and thank you in advance.

**Comment by NOA-Scott** [comment]
@josuer I have encountered, have any solution?

**Comment by josuer** [comment]
@NOA-Scott Yes, the problem was not only for facebook login, but for email login also, the problem was that those users had a big array of data, so whenever we where trying to login the call was fetching the entire user with the enourmous array and that makes the call fail. We removed those arrays and then the login worked with no problem.

**Comment by NOA-Scott** [comment]
@josuer  Thank you for your answer, But I don't know those arrays, this array, what do you mean?
