### ISSUE TITLE
i/o failure while calling saveInBackground function of ParseObject

### ISSUE THREAD

**Issue by ajaypandita** [parse-community/Parse-SDK-Android#690]
MainActivity.class
`
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ParseObject _parseObject = new ParseObject("DemoClass");
        _parseObject.put("username", "demo");
        _parseObject.put("password", "demo");
        _parseObject.saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                if (e == null)
                    Log.i("parse", "done");
                else
                    Log.i("parse", "error | " + e.getMessage());

            }
        });

    }
}`

ParseApplication.class

`
public class ParseServerLink extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        Parse.enableLocalDatastore(this);
        Log.i("parse","connecting");
        Parse.initialize(new Parse.Configuration.Builder(getApplicationContext()).applicationId("myAppId").server("http://172.17.0.3:1337/parse/").clientKey("password").build());
        Log.i("parse","connected");

    }
}
`

AndroidManifest.xml

`<application
        android:name=".ParseApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <meta-data
            android:name="com.parse.SERVER_URL"
            android:value="http://172.17.0.3:1337/parse/"/>
        <meta-data
            android:name="com.parse.APPLICATION_ID"
            android:value="myAppId"/>

        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
`

Log

>I/System.out: [CDS]rx timeout:10000
I/System.out: [socket][0] connection /172.17.0.3:1337;LocalPort=57762(10000)
I/System.out: [CDS]connect[/172.17.0.3:1337] tm:10
W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
I/System.out: [socket][1:57762] exception
I/System.out: [CDS]close[57762]
I/System.out: close [socket][/0.0.0.0:57762]
I/System.out: [CDS]rx timeout:10000
I/System.out: [socket][1] connection /172.17.0.3:1337;LocalPort=51480(10000)
I/System.out: [CDS]connect[/172.17.0.3:1337] tm:10
I/System.out: [socket][2:51480] exception
I/System.out: [CDS]close[51480]
I/System.out: close [socket][/0.0.0.0:51480]
I/System.out: [CDS]rx timeout:10000
I/System.out: [socket][2] connection /172.17.0.3:1337;LocalPort=48263(10000)
I/System.out: [CDS]connect[/172.17.0.3:1337] tm:10
I/System.out: [socket][3:48263] exception
I/System.out: [CDS]close[48263]
I/System.out: close [socket][/0.0.0.0:48263]
I/System.out: [CDS]rx timeout:10000
I/System.out: [socket][3] connection /172.17.0.3:1337;LocalPort=37325(10000)
I/System.out: [CDS]connect[/172.17.0.3:1337] tm:10
I/System.out: [socket][4:37325] exception
I/System.out: [CDS]close[37325]
I/System.out: close [socket][/0.0.0.0:37325]
I/System.out: [CDS]rx timeout:10000
I/System.out: [socket][4] connection /172.17.0.3:1337;LocalPort=34692(10000)
I/System.out: [CDS]connect[/172.17.0.3:1337] tm:10
I/System.out: [socket][5:34692] exception
I/System.out: [CDS]close[34692]
I/System.out: close [socket][/0.0.0.0:34692]
I/parse: error | i/o failure

**Comment by fvimagination** [comment]
Does your application tag start like this:
<application 
   android:name=".ParseServerLink"
...
