### ISSUE TITLE
api.parse.com is down

### ISSUE THREAD

**Issue by kenorb** [parse-community/Parse-SDK-Android#694]
Our app is using the following REST endpoint: https://api.parse.com/1/push to send push notification for Android devices as per [REST Guide](http://docs.parseplatform.org/rest/guide/), however currently the endpoint is either down or has invalid SSL certificate (ERR_CERT_DATE_INVALID).

**Comment by montymxb** [comment]
@kenorb **api.parse.com** was shutdown earlier [this year](http://blog.parse.com/announcements/a-parse-shutdown-reminder/). It is not longer a valid end point to interact with. Instead you will need to setup your own parse-server instance or use one of the many hosted alternatives, all of which are compatible with these sdks. You can checkout the parse-server [github page](https://github.com/parse-community/parse-server) for more info on this.

**Comment by Jawnnypoo** [comment]
Thanks for answering @montymxb That is indeed the case

**Comment by rogerhu** [comment]
Do we need to update the docs?

**Comment by montymxb** [comment]
@rogerhu yeah...there's quite a few references to **api.parse.com** in the rest guide as mentioned above after looking at it. I can jump in there and correct those as needed, maybe we can do something like `your.parse-server.com` instead, with an emphasis on replacing that with their own server.

**Comment by rogerhu** [comment]
Thank you so much!
