### ISSUE TITLE
how to see the saved data? where the data is being saved? 

### ISSUE THREAD

**Issue by anasahmedtaj** [parse-community/Parse-SDK-Android#700]
i am new to android and dont know much about parse. i am following rob percival tutorials. when he created the apps using parse it was different. Now i dont know how to see the saved data (classes/object/users)? please help me

**Comment by addisonElliott** [comment]
This is typically not the place to ask questions. The issues page is for issues regarding bugs/features in the code that you want to see added.

For a getting started guide, check out this: http://docs.parseplatform.org/android/guide/
and this: http://docs.parseplatform.org/parse-server/guide/
