### ISSUE TITLE
Better README?

### ISSUE THREAD

**Issue by natario1** [parse-community/Parse-SDK-Android#705]
Do we need a better front page?

We are getting some basic-usage issues opened recently and I figured out that, apart from the repo description on top, the readme is even missing links to the official guide.

We could add links to http://docs.parseplatform.org/android/guide/ and copy-paste at least the first section here. The current readme is very contributor-oriented with things like `./gradlew clean jarRelease` that possibly no one cares about.

Is anyone up for this?

**Comment by addisonElliott** [comment]
Couldn't agree more and I think this is a perfect first contribution for me! (First contribution for this repository at least)

**Comment by natario1** [comment]
Thanks!
