### ISSUE TITLE
ParseObject cloning

### ISSUE THREAD

**Issue by WanClem** [parse-community/Parse-SDK-Android#712]
Hi, is there plan to make the `copyChangesFrom` method in the `ParseObject.java` class public?

Example `objectA.copyChangesFrom(objectB); 
objectA.saveInBackground();`

My app needed this feature urgently.
Thanks.

**Comment by Jawnnypoo** [comment]
Couldn't you just create a copy constructor?

**Comment by WanClem** [comment]
@Jawnnypoo I doubt the feasibility of a copy constructor.Though an example would suffice.

**Comment by natario1** [comment]
Yeah I think we have no plans for this, you should do it manually... iterating over the keys and using `isDirty(key)` if needed. Closing for now, feel free to comment.
