### ISSUE TITLE
Parse delete is not working

### ISSUE THREAD

**Issue by sandeep2242** [parse-community/Parse-SDK-Android#720]
I am deleting  an object from parse and below is my code
`  holder.cross.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View view) {
                new AlertDialog.Builder(context).setIcon(R.drawable.main).setTitle("Delete this product ?")
                        .setMessage("Are you sure you want to Delete this product ?").setPositiveButton("Yes", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {

                        ParseQuery<ParseObject> query = ParseQuery.getQuery("VendorInv");
                        query.whereEqualTo("objectId", details.getObjectId());
                        query.getFirstInBackground(new GetCallback<ParseObject>() {
                            @Override
                            public void done(ParseObject object, ParseException e) {
                                try {
                                    object.delete();
                                    object.saveInBackground(new SaveCallback() {
                                        @Override
                                        public void done(ParseException e) {

                                            if (e == null) {
                                                vendorDetailsList.remove(position);
                                                notifyItemRemoved(position);
                                                notifyItemRangeChanged(position, vendorDetailsList.size());
                                                count.setText(String.valueOf(vendorDetailsList.size()) + "/" + totalNo + " items are Online");
                                                Toast.makeText(context, "Deleted", Toast.LENGTH_SHORT).show();
                                            }
                                        }
                                    });
                                } catch (ParseException e1) {
                                    Log.i("sand", e1.toString());
                                }
                            }
                        });
                    }

                }).setNegativeButton("No", null).show();

            }

        });

    }`
exception is null , and hence toast is printing "deleted".

**Comment by natario1** [comment]
```
object.delete();
object.saveInBackground();
```

I don't know what your plan is but this makes no sense. Just use `delete()` or `deleteInBackground(DeleteCallback)`.

For usage support please refer to StackOverflow or to [our guide](http://docs.parseplatform.org/android/guide/).

**Comment by sandeep2242** [comment]
@natario1  
`
                        ParseQuery<ParseObject> query = ParseQuery.getQuery("VendorInv");
                        query.whereEqualTo("objectId", details.getObjectId());
                        query.getFirstInBackground(new GetCallback<ParseObject>() {
                            @Override
                            public void done(ParseObject object, ParseException e) {
                                object.deleteInBackground(new DeleteCallback() {
                                    @Override
                                    public void done(ParseException e) {
                                        if (e == null) {
                                            vendorDetailsList.remove(position);
                                            notifyItemRemoved(position);
                                            notifyItemRangeChanged(position, vendorDetailsList.size());
                                            count.setText(String.valueOf(vendorDetailsList.size()) + "/" + totalNo + " items are Online");
                                            Toast.makeText(context, "Deleted", Toast.LENGTH_SHORT).show();
                                        }
                                    }
                                });
                            }
                        });`  
but this is also not working
