### ISSUE TITLE
Array only adding one item on parse server and remove does not delete item from array :/

### ISSUE THREAD

**Issue by anasahmedtaj** [parse-community/Parse-SDK-Android#727]
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        if (ParseUser.getCurrentUser().getList("hello")==null)
        {
            List<String> emptyList = new ArrayList<String>();
            ParseUser.getCurrentUser().put("hello",emptyList);
            ParseUser.getCurrentUser().saveInBackground();
        }
        ParseUser.logInInBackground("anas", "anas", new LogInCallback() {
            @Override
            public void done(ParseUser user, ParseException e) {

                if (e==null)
                {
                  
                    ParseUser.getCurrentUser().getList("arrayName").add("robert");
                    ParseUser.getCurrentUser().saveInBackground();                   
                }
            }
        });
    }
}

**Comment by tadhao** [comment]
@anasahmedtaj  I am actually facing the same issue at the moment. Would appreciate if you could share the answer to that if you figured it out!

**Comment by flovilmart** [comment]
This makes sense I believe as you're not setting back the list after removing the element from it. It is probably the same when using `getList("arrayName").add("robert")`

```
ArrayList<String> aList = obj.getList("arrayName");
aList.add("aString")
obj.put("arrayName", aList);
obj.saveInBackground();
```

**Comment by flovilmart** [comment]
Have a look here how to properly use lists for example:

https://github.com/parse-community/Parse-SDK-Android/blob/e86b920a001e9b184aa7d7f81cad00abcbe2afe8/Parse/src/main/java/com/parse/ParsePushChannelsController.java#L54

**Comment by sanapagarkar** [comment]
I had the same problem. I did this for remove and it worked.
List<Object> alist=ParseUser.getCurrentUser().getList("isFollowing");
alist.remove(activeUsername);
ParseUser.getCurrentUser().put("isFollowing", alist);
ParseUser.getCurrentUser().saveInBackground();
