### ISSUE TITLE
Add JVM support

### ISSUE THREAD

**Issue by holgerbrandl** [parse-community/Parse-SDK-Android#728]
It would be great if the API could be also used to build JVM applications (targeting the desktop/server rather than the mobile).

I guess the public API would look pretty similar but the backend would need to be decoupled from android to provide an alternative JVM backend.

Or is there a different parse SDK for the JVM? I've seen the generic REST API but it lacks some convenience compared to the nice way the Android SDK works.

**Comment by flovilmart** [comment]
@mmimeault, do you know what it would take to ripoff android dépendant code and if / how it could be approached?

**Comment by joelhandwell** [comment]
How about use Kotlin language to support JVM together with Kotlin/JS to wrap Parse-SDK-JS and [Kotlin/Native](https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md) to wrap Parse-SDK-iOS-OSX? Creating one Kotlin common interface opens way for [multi platform shared codebase](https://kotlinlang.org/docs/reference/multiplatform.html).

**Comment by flovilmart** [comment]
Not sure about the validity of rewriting all the SDK’s in kotlin, but thst’s for sure a fun project to explore.

The issue here is about the android package a dependencies in the existing codebase, which could be removed

**Comment by joelhandwell** [comment]
Actually my interest is to write Android and iOS app using Kotlin/Native so initial step can be thin wrapper of Parse-SDK-Android and Parse-SDK-iOS-OSX in Kotlin which would be done smaller amount of work compared to "rewriting all the SDK’s in kotlin" still satisfy developers who want to do multi platform development in Kotlin. That can be called Parse-SDK-Kotlin. Those who want to use Parse via Kotlin can also access [Parse server via Kotlin/JS interop](https://kotlinlang.org/docs/reference/js-interop.html).

Then second step can be refactor the it to remove Android specific codes to support JVM in server. How do you think?

**Comment by flovilmart** [comment]
Both steps are indépendant. As for the ‘thin wrapper’ this would require two thin wrappers as neither SDK’s are compatible.

**Comment by joelhandwell** [comment]
| Android Classes   (27)       | iOS Classes (19)                                | Found both (18) |
|------------------------------|-------------------------------------------------|-----------------|
| ManifestInfo                 |                                                 |                 |
| Parse                        | Parse                                           | [x]             |
| Parse.Configuration          | ParseClientConfiguration                        | [x]             |
| Parse.Configuration.Builder  |                                                 | [ ]             |
| ParseACL                     | PFACL                                           | [x]             |
| ParseAnalytics               | PFAnalytics                                     | [x]             |
| ParseAnonymousUtils          | PFAnonymousUtils                                | [x]             |
| ParseClassName               |                                                 | [ ]             |
| ParseCloud                   | PFCloud                                         | [x]             |
| ParseConfig                  | PFConfig                                        | [x]             |
| ParseException               |                                                 | [ ]             |
| ParseFile                    | PFFile                                          | [x]             |
| ParseFileUtils               |                                                 | [ ]             |
|                              | PFFileUploadResult                              | [ ]             |
| ParseGeoPoint                | PFGeoPoint                                      | [x]             |
| ParseInstallation            | PFInstallation                                  | [x]             |
| ParseObject                  | PFObject                                        | [x]             |
| ParsePolygon                 | PFPolygon                                       | [x]             |
| ParsePush                    | PFPush                                          | [x]             |
| ParsePushBroadcastReceiver   |                                                 | [ ]             |
| ParseQuery                   | PFQuery                                         | [x]             |
| ParseQuery.CachePolicy       |                                                 | [ ]             |
| ParseRelation                | PFRelation                                      | [x]             |
| ParseRole                    | PFRole                                          | [x]             |
| ParseSession                 | PFSession                                       | [x]             |
| ParseUser                    | PFUser                                          | [x]             |
| PLog                         |                                                 | [ ]             |
| PushRouter                   |                                                 | [ ]             |
|                              |                                                 |                 |
| Android Http Classes         | iOS Http Classes                                |                 |
| ParseHttpBody                | PFEncoder                                       | [ ]             |
| ParseHttpRequest             | PFKnownParseObjectDecoder                       | [ ]             |
| ParseHttpRequest.Builder     | PFNoObjectEncoder                               | [ ]             |
| ParseHttpRequest.Method      | PFOfflineDecoder                                | [ ]             |
| ParseHttpResponse            | PFOfflineObjectEncoder                          | [ ]             |
| ParseHttpResponse.Builder    | PFPointerObjectEncoder                          | [ ]             |
|                              | PFPointerOrLocalIdObjectEncoder                 | [ ]             |
|                              |                                                 |                 |
| Android Callback Classes     | iOS Constants                                   | [ ]             |
| AuthenticationCallback       | PFInvalidSessionTokenNotification               | [ ]             |
| ConfigCallback               | PFNetworkDidReceiveURLResponseNotification      | [ ]             |
| CountCallback                | PFNetworkNotificationURLRequestUserInfoKey      | [ ]             |
| DeleteCallback               | PFNetworkNotificationURLResponseBodyUserInfoKey | [ ]             |
| FindCallback                 | PFNetworkNotificationURLResponseUserInfoKey     | [ ]             |
| FunctionCallback             | PFNetworkWillSendURLRequestNotification         | [ ]             |
| GetCallback                  | PFObjectDefaultPin                              | [ ]             |
| GetDataCallback              | PFParseErrorDomain                              | [ ]             |
| GetDataStreamCallback        | kPFDeviceType                                   | [ ]             |
| GetFileCallback              | Enumerations                                    | [ ]             |
| LocationCallback             | PFCachePolicy                                   | [ ]             |
| LogInCallback                | PFErrorCode                                     | [ ]             |
| LogOutCallback               | PFLogLevel                                      | [ ]             |
| ProgressCallback             | Protocols                                       | [ ]             |
| RefreshCallback              | PFFileUploadController                          | [ ]             |
| RequestPasswordResetCallback | PFSubclassing                                   | [ ]             |
| SaveCallback                 | PFUserAuthenticationDelegate                    | [ ]             |
| SendCallback                 | ParseMutableClientConfiguration                 | [ ]             |
| SignUpCallback               | Type Definitions                                | [ ]             |
|                              | PFQueryArrayResultBlock                         | [ ]             |

**Comment by joelhandwell** [comment]
According to API reference 18 classes (excluding Callbacks or Encoders/Decoders) have almost same functions.  What I meant was using Kotlin's ```expect``` and ```actual``` declaration, underlining specific implementation incompatibility can be abstracted away like:


```kotlin
expect class Parse(){
    fun enableLocalDatastore(context: Any)
}

//Android
actual class Parse(){
    fun enableLocalDatastore(context: Any){
        val androidContext = context as android.content.Context // cast type from Any
        com.parse.Parse.enableLocalDatastore(androidContext)
    }
}

//iOS
actual class Parse(){
    fun enableLocalDatastore(context: Any){
        Parse.enableLocalDatastore() // ignore arg context
    }
}
```

**Comment by joelhandwell** [comment]
I saw https://github.com/BoltsFramework and how it's used in Parse-SDK-Android and Parse-SDK-iOS-OSX. 

Step 1. Extract common ```expect class``` implement ```actual class``` only for Android, and iOS/OSX in this step no need to wrap bolts
Step 2. Implement ```actual class``` with JVM by replacing Android specific bolts code, at this time something like bolts needs to be implemented with only Kotlin stdlib if possible.
Step 3. If Kotlin stdlib implementation can be expanded to full Parse lib, then it can be compiled into other platforms like linux and windows etc.

**Comment by flovilmart** [comment]
Sounds like you have your plan for it. However I'm not sure this is a direction / strategy that we'll pursue in any case. If this is something you want to pursue (build a kotlin SDK) feel free to get started. 

This discussion was originally about extracting the JVM compatible core of this SDK, and not introducing a new language. This has drifted tremendously.

@holgerbrandl I'll reopen a new issue about the JVM and rename / close this one.
