### ISSUE TITLE
Query on parse user not working

### ISSUE THREAD

**Issue by Aniket6055** [parse-community/Parse-SDK-Android#731]
ParseQuery<ParseUser> query = ParseUser.getQuery();
query.findInBackground(new FindCallback<ParseUser>() {
                        @Override
                        public void done(List<ParseUser> list, ParseException e) {
}
}

findInBackground showing error com.parse.ParseRequest: Request failed.

**Comment by flovilmart** [comment]
Can you provide more information?

**Comment by Aniket6055** [comment]
@flovilmart I am doing simple user query and it's giving me that error.

**Comment by flovilmart** [comment]
What are the server logs when running with VERBOSE=1?
