### ISSUE TITLE
Failed to resolve "support-annotations:26.0.1" error

### ISSUE THREAD

**Issue by durey** [parse-community/Parse-SDK-Android#733]
When using up to version 1.15.8 in my projects, everything works fine: 

`compile 'com.parse:parse-android:1.15.8'`

But when trying to use the latest release:

`compile 'com.parse:parse-android:1.16.0'`

I start getting this error:

`Failed to resolve "com.android.support:support-annotations:26.0.1" error`

And clicking on the install link for that library does nothing. I check Android Studio's log and it says nothing. I tried to download the library by hand and no success... 

Are you aware of this? Thank you very much for your time.

**Comment by rogerhu** [comment]
You probably need to add the Maven Google repo -- https://developer.android.com/studio/build/dependencies.html#google-maven

**Comment by durey** [comment]
Thank you very much, that solved the problem :-)

Anyway, I won't use the

`compile 'com.parse:parse-android:1.+'`

abbreviation anymore, lesson learnt!
