### ISSUE TITLE
When running the App it Crashed

### ISSUE THREAD

**Issue by matmar2** [parse-community/Parse-SDK-Android#734]
When trying to run the application I received the attached message..

What could be the cause of the problem?

<img width="297" alt="screen shot 2017-09-08 at 1 13 03 pm" src="https://user-images.githubusercontent.com/31569847/30223143-a0689f38-9497-11e7-9b17-6fe3f43eaabf.png">

**Comment by Jawnnypoo** [comment]
The starter app is not a complete sample, it is meant for you to copy and modify to match your needs. Since you need your own parse server, there is no configuration present, therefore it crashes when launched without modification.
