### ISSUE TITLE
Issues with parse on kitkat and jellybean.

### ISSUE THREAD

**Issue by otimtony** [parse-community/Parse-SDK-Android#736]
My app seems to send data to my parse server for android version lollipop and above but fails to submit data to the parse server for android versions lower that lollipop. I get an SSL handshake error. Can some one help me out.

**Comment by Jawnnypoo** [comment]
KitKat is the first version of Android that started using TLS 1.2 by default, you might need to customize your OkHttpClient.Builder and assure you are always using TLS 1.2 https://github.com/square/okhttp/issues/2372
