### ISSUE TITLE
Fatal Exception: java.lang.verifyerror

### ISSUE THREAD

**Issue by noobiehacker** [parse-community/Parse-SDK-Android#747]
**Stacktrace** 

`Fatal Exception: java.lang.VerifyError: Verifier rejected class com.parse.ManifestInfo: com.parse.ManifestInfo$ManifestCheckResult com.parse.ManifestInfo.gcmSupportLevel() failed to verify: com.parse.ManifestInfo$ManifestCheckResult com.parse.ManifestInfo.gcmSupportLevel(): [0x62] copyRes1 v4<- result0 type=Undefined
 com.parse.ManifestInfo$ManifestCheckResult com.parse.ManifestInfo.ppnsSupportLevel() failed to verify: com.parse.ManifestInfo$ManifestCheckResult com.parse.ManifestInfo.ppnsSupportLevel(): [0x4A] copyRes1 v2<- result0 type=Undefined (declaration of 'com.parse.ManifestInfo' appears in /data/app/com.xxxx.sampleApp-1/base.apk)
       at com.parse.ManifestInfo.getApplicationMetadata(ManifestInfo.java:337)
       at com.parse.Parse$Configuration$Builder.(Parse.java)
       at com.aadhk.woinvoice.util.ParseInit.init(ParseInit.java:92)`

**Scenerio**

Hey guys, this bug just suddenly started appearing in our production app and I am not sure why there is a verifyerror.  I am using version `1.13.2` of SDK, I read somewhere that PPNS support has been taken out, would upgrading the SDK be a possible solution?

**Comment by Jawnnypoo** [comment]
Yep, that would probably fix it
