### ISSUE TITLE
ERROR: Cannot register a type that does not implement the default constructor!

### ISSUE THREAD

**Issue by rommex** [parse-community/Parse-SDK-Android#752]
Hi there, thanks for your time and work.

I'm following the guide for Android and ParseObjects are written and quiried just fine.
But once I start subclassing ParseObject I keep getting the error:

"Cannot register a type that does not implement the default constructor!"

My class declaration looks like this:
`@ParseClassName("MyParseObject")
    public class MyParseObject extends ParseObject {
        public MyParseObject() {
            super(); //with or without it, the error persists
        }
    }`

I do the registering before Parse.initialize ():
ParseObject.registerSubclass(MyParseObject.class);

Please help

**Comment by natario1** [comment]
This feature should be very well tested. Are you sure that's your constructor? The error might be related to another class?

**Comment by Jawnnypoo** [comment]
Feel free to comment again if you would like support, but it seems like this is a dead issue.
