### ISSUE TITLE
i/o failure in parse

### ISSUE THREAD

**Issue by centoos** [parse-community/Parse-SDK-Android#754]
![screenshot from 2017-10-28 09-17-25](https://user-images.githubusercontent.com/23267387/32134703-e9e3c14c-bbc0-11e7-8b30-51cc6be6eeb9.png)

**Comment by RenatoMarques** [comment]
Same here. :-(

**Comment by natario1** [comment]
I wonder if the starter project does still make sense. It's supposed to be a super easy showcase but now you need a parse-server correctly set up and that can be not easy at all, depending on your skills. 

Also, I don't think it adds anything to the Android docs...

Also, no one is maintaining it. What do you think guys?

**Comment by Jawnnypoo** [comment]
Yeah, it just adds confusion in the end. It would be better to rename it as `sample` and then integrate it with an actual server if anything

**Comment by DanGTZ** [comment]
I think it could be removed from the project.

**Comment by Jawnnypoo** [comment]
Starter project has been removed
