### ISSUE TITLE
 all of this server and client work on gcm?

### ISSUE THREAD

**Issue by mohamadpk** [parse-community/Parse-SDK-Android#755]
i have a big question you create big client sdk and big server controlling all of this over "gcm". means all 
===========================>
data in 1 your server 2 google gcm 3 target
<===========================
data of target 1 target 2 in google 4 now again in your hand

if my question is true? why we use your notification instead use direct gcm

**Comment by Jawnnypoo** [comment]
You can use direct GCM or FCM if you would like, it is up to you as the developer. Parse Server allows you to define queries easily of Installations that the pushes will go out to, which makes it simple and nice to send pushes to specific users and devices. But if you intend to just push to all devices all the time, or just single users all the time, you could certainly do the pushes yourself. Nothing is stopping you.
