### ISSUE TITLE
ParseBroadcastReceive not found in manifest

### ISSUE THREAD

**Issue by renegens** [parse-community/Parse-SDK-Android#758]
This happens when upgrading from 1.16 to 16 and above. Question is there somewhere a migration document how to set this up? The current configuration is based on the below.

https://gist.github.com/renegens/6f23b2dcd6e05979528d02b3c3869e54
PS: Github doesn't seem to like formating of the manifest.

**Comment by renegens** [comment]
<receiver android:name="com.parse.ParseBroadcastReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.USER_PRESENT" />
            </intent-filter>
        </receiver>
        <receiver
            android:name=".notificationservice.CustomPushReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="utils.UPDATE_STATUS" />
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="com.parse.GcmBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="com.some.name" />
            </intent-filter>
        </receiver>

        <service android:name="com.parse.PushService" />

**Comment by natario1** [comment]
There is no migration needed. You should declare `ParsePushBroadcastReceiver`, not `ParseBroadcastReceiver`

**Comment by renegens** [comment]
Alright thanks, did that. It works
