### ISSUE TITLE
Unable to encode an unsaved ParseFile

### ISSUE THREAD

**Issue by fvimagination** [parse-community/Parse-SDK-Android#761]
Since yesterday everything was working fine in my Android apps while uploading images via app, now it's not working anymore, it throws this error:
`java.lang.illegalStateException: 
Unable to encode an unsaved ParseFile`

In my saving method, I first perform a `saveInBackground()` instance for String data, then after the code successfully saved that data, i save my image like this:

```
Bitmap bitmap = ((BitmapDrawable) image1.getDrawable()).getBitmap();
                              ByteArrayOutputStream stream = new ByteArrayOutputStream();
                              bitmap.compress(Bitmap.CompressFormat.JPEG, 100, stream);
                              byte[] byteArray = stream.toByteArray();
                              ParseFile imageFile = new ParseFile("image1.jpg", byteArray);
                              adObj.put(Configs.ADS_IMAGE1, imageFile);

adObj.saveInBackground(new SaveCallback() {
```

That's where I get that error, it cannot upload files anymore... That's a huge issue, hope it will be fixed soon, my code above was perfectly working before this new SDK update.

**Comment by flovilmart** [comment]
You can probably, as a workaround, save the file first, then save the object `adObj` when the file was properly saved.

**Comment by fvimagination** [comment]
I guess it was a temporary SDK issue because now it works. 
Btw, I already first save my adObj then upload the images, because if I try to save both string data and image, it doesn't work.
Anyway, thanks, it seems that this issue is solved.

**Comment by flovilmart** [comment]
I was suggesting you do the exact opposite, save the image first, then save the object

**Comment by fvimagination** [comment]
I tried that a few hours ago, but got the same issue, so again, it may have just been a temporary SDK issue ;)

**Comment by broshka** [comment]
Hello, I also faced this issue "Unable to encode an unsaved ParseFile".
What should I do, if I need to save ParseObject with ParseFile locally. 

ParseFile has only method saveInBackground which requires internet connection

**Comment by MineRock** [comment]
Sorry for necroposting everyone!
I have found out that if the image size is too large or too high quality, a crash like this occurs. So while uploading, be sure not to use like a 4k 14mb image.

**Comment by arianagoldstein** [comment]
@MineRock that was it for me!! thank you so much for posting. here's the post I used to help resize the file and it worked for me: https://stackoverflow.com/questions/16292853/how-to-upload-an-image-in-parse-server-using-parse-api-in-android

hope this helps others!!
