### ISSUE TITLE
VideoView give error (1,1004) from parse server.

### ISSUE THREAD

**Issue by omercsoylu** [parse-community/Parse-SDK-Android#763]
i upload a video to parse server succesfully. and i can not use on videoview this video.

i upload same video to another server, my personal hosting. and use this URL. videoview was playins succesfully. but URL from parse didnt work, i give that error.

`W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: http://13.58.216.247/parse/files/******_video.mp4
D/RingtoneManager: Can't get current user. return default user
D/MediaPlayer: setDataSource IOException | SecurityException happend : 
               java.io.FileNotFoundException: No content provider: http://13.58.216.247/parse/files/******_video.mp4 `

`V/MediaPlayer: buffering 100
V/MediaPlayer: callback application
V/MediaPlayer: back from callback
V/MediaPlayer: message received msg=6, ext1=0, ext2=0
V/MediaPlayer: Received MEDIA_STARTED
V/MediaPlayer: callback application
V/MediaPlayer: back from callback
V/MediaPlayer: message received msg=200, ext1=702, ext2=0
V/MediaPlayer-JNI: getCurrentPosition: 21 (msec)
V/MediaPlayer-JNI: isPlaying: 1
W/MediaPlayer: info/warning (702, 0)
V/MediaPlayer: callback application
V/MediaPlayer: back from callback
V/MediaPlayer-JNI: getCurrentPosition: 21 (msec)
V/MediaPlayer-JNI: isPlaying: 1
D/libEGL: eglInitialize EGLDisplay = 0x9606e614
D/libEGL: eglInitialize EGLDisplay = 0x9606e614
D/libEGL: eglInitialize EGLDisplay = 0x9606e614
V/MediaPlayer: message received msg=100, ext1=1, ext2=-1004
E/MediaPlayer: error (1, -1004)`

**Comment by Jawnnypoo** [comment]
Is `http://13.58.216.247/parse/files/******_video.mp4` the actual URL of your video? or did you add the `******` to hide the URL.

**Comment by Jawnnypoo** [comment]
Not enough info on this to provide support, but I would assume this is a problem with the parse server setup.

**Comment by andresteves** [comment]
Also have the same problem as this.
