### ISSUE TITLE
Is there any provision for Google signon?

### ISSUE THREAD

**Issue by DerinLois** [parse-community/Parse-SDK-Android#765]
Please, i will so much appreciate a lead on this. I have been able to integrate FacebookParse, but really finding it a little bit difficult to also integrate Google signon to my mobile application.

I am new to the Parse technology, and any contribution to this will be duely appreciated.
thanks.

**Comment by Jawnnypoo** [comment]
I don't think you can expect any official support for this anytime in the future, as it would take quite a bit of effort. Feel free to search for other places where this solution may exist, or to contribute it yourself if you would like.
