### ISSUE TITLE
authData is not cleaned up when linkWithAsync() fails

### ISSUE THREAD

**Issue by mhartvick** [parse-community/Parse-SDK-Android#767]
Whenever [linkWithAsync()](https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseUser.java#L1280) fails, [the anonymity is restored](https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseUser.java#L457), but the `authData` map still contains the value for the `authType` that just failed.

It's unexpected from a consumer point of view, `isLinked(myAuthType)` will be `true` right after failing to link the exact same `myAuthType`, and differs from the iOS behavior (according to a colleague of mine who tried to reproduce the issue on its platform)

**Comment by flovilmart** [comment]
@rogerhu can you have a look please?

**Comment by Jawnnypoo** [comment]
Seems like we can close this out now. Thanks for the contribution @mhartvick !
