### ISSUE TITLE
enable localdatastore and use live query, case "Attempted to change an objectId to one that's already known to the Offline Store."

### ISSUE THREAD

**Issue by dilongl** [parse-community/Parse-SDK-Android#770]
enable localdatatore
use the liveQuery

call the ParseObject.saveInBackground and use the liveQuery subscribe the same ClassName, 
due to liveQuery receive data then call ParseObject.fromJSON to build a new ParseObject object, case "Attempted to change an objectId to one that's already known to the Offline Store." when the ParseObject.saveInBackground call updateObjectId.

**Comment by Jawnnypoo** [comment]
Dupe of #267
