### ISSUE TITLE
"Compiling for yourself into AAR file" instructions don't work

### ISSUE THREAD

**Issue by iainmerrick** [parse-community/Parse-SDK-Android#776]
I tried following the build instructions in README.md, option 2 (compiling for yourself into AAR file), but it failed. Here's the output from within the Android Studio terminal:

> Parse-SDK-Android-1.16.5$ ./gradlew clean jarRelease
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task 'jarRelease' not found in root project 'Parse-SDK-Android-1.16.5'.
> 
> * Try:
> Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s

I don't know anything about Gradle so I don't know how to fix this. (I'm guessing it's something simple, just most people don't use option 2.)

**Comment by rogerhu** [comment]
Use ./gradlew clean build.  There should be an AAR file in the app/build/outputs dir.

**Comment by iainmerrick** [comment]
That works, thanks! I'll send a little PR to fix the docs.

**Comment by rogerhu** [comment]
Thanks!
