### ISSUE TITLE
Parse configuration improvements

### ISSUE THREAD

**Issue by vovkab** [parse-community/Parse-SDK-Android#789]
Hello

I would like to discuss possibility of improving parse configuration.
According to documentation:
http://docs.parseplatform.org/android/guide/

You can configure parse via `AndroidManifest` or by providing `Parse.Configuration` to `Parse`.

But as I can see, even though we are doing manual configuration it would still do Manifest lookup, which is pretty expensive, especially considering that we need to do this in `Application.onCreate()`.

Would be great to avoid doing unnecessary manifest lookup. If manifest lookup from builder is still desired, would be great to have separate factory method or just builder method, for example:

Factory method:
```
Parse.Configuration.builder().server(...).build()
Parse.Configuration.fromManifest().build();
```

Builder method:
```
Parse.Configuration.builder().manifest(context).build();
```

And another suggestion is to add logging level to configuration, so you can do initial parse configuration with just single init call. Right now you have to do this separately by calling `Parse.setLogLevel()`

**Comment by Jawnnypoo** [comment]
Thanks for the suggestion, we removed the Manifest support recently.
