### ISSUE TITLE
ParseCloud.callFunction creates a new thread

### ISSUE THREAD

**Issue by vovkab** [parse-community/Parse-SDK-Android#790]
We have two methods available to call functions:

```
ParseCloud.callFunction()
ParseCloud.callFunctionInBackground()
```

Which, according to description:
`callFunction()` - should make synchronous request
`callFunctionInBackground()` - should make async request

Though it works differently according to code of the `ParseCloud.callFunction()`:

```java
public static <T> T callFunction(String name, Map<String, ?> params) throws ParseException {
  return ParseTaskUtils.wait(ParseCloud.<T>callFunctionInBackground(name, params));
}
```

Link to source code: 
https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseCloud.java#L82

Actual: It would block current thread, create a new thread and then return result to blocked thread.

Expected: sync calls should be executed on current thread only and not create unnecessary new threads.

Use case for sync calls: let the app to define where calls should be executed. We may call it from Service's, Tasks, RxJava, tests and etc.

Can you please provide pure synchronous function call?

**Comment by Jawnnypoo** [comment]
If you look at other calls such as `parseObject.save()`, they are similar in that they call the background method, and then wait for the result. This would be a large change across the board, which I don't think will happen due to the nature of Bolts and the way this SDK has been built.
