### ISSUE TITLE
Parse push with FCM seems to not be working

### ISSUE THREAD

**Issue by billyz313** [parse-community/Parse-SDK-Android#797]
I have been trying to update an old app that used parse.com.  I have setup my own instance of parse server and directed the app to use the new instance.  Everything works now in the app with the exception of the push notifications.  I created a new firebase application and enabled FCM.  I have placed the keys in myConfig.json which i reference when i start parse from the terminal. It looks like:

> 

{
   "appId": "idofapp",
   "masterKey": "master,
   "cloud": "/home/ubuntu/cloud/",
   "databaseURI": "mongodb://localhost:27017/test-app",
   "push": {
            "android":{
         "senderId": "99999999999",
         "apiKey": "BigLongKeyGeneratedFromFirebase"
      }
   }
}

> 

I have created a cloud/main.js which i reference in the config file.  It looks like: 

> 

Parse.Cloud.define("SendPush", function(request) {
	var msg = request.params.message;
	var query = new Parse.Query(Parse.User);
	var user = request.params.user;
	query.equalTo("objectId", user);
	Parse.Push.send({
      		where: query,
		data:{
			alert: {
				"title" : msg,
				"body" : msg
			},
			sound: 'default'
		}
    	}, {
      		useMasterKey: true,
		success: function(){
			response.success("Push Sent!");
		},
		error: function(error){
			response.error("Error while trying to send push " + error.message);
		}
    });
 });

> 

I enabled verbose logging since it wasn't giving me any information about why the push notifications were not being delivered.  It prints out the following five times only changing the Status-Id.

> 

verbose: REQUEST for [POST] /parse/functions/SendPush: {
  "message": "You have a new message ",
  "user": "bXYVlwltiN"
} method=POST, url=/parse/functions/SendPush, x-parse-session-token=r:6d11549cc2f2e7ffd64ba07a6d327e8d, x-parse-application-id=app, x-parse-client-version=a1.15.8, x-parse-app-build-version=1, x-parse-app-display-version=1.0, x-parse-os-version=8.0.0, user-agent=Parse Android SDK 1.15.8 (com.websitedesigns.zero.three.ribbit/1) API Level 26, x-parse-installation-id=44324cf9-65fa-4671-8798-26eafa291711, content-type=application/json, content-length=57, host=ec2-54-218-38-143.us-west-2.compute.amazonaws.com:1337, connection=Keep-Alive, accept-encoding=gzip, message=You have a new message , user=bXYVlwltiN
verbose: REQUEST for [POST] /parse/push: {
  "where": {
    "objectId": "bXYVlwltiN"
  },
  "data": {
    "alert": {
      "title": "You have a new message ",
      "body": "You have a new message "
    },
    "sound": "default"
  }
} method=POST, url=/parse/push, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 7.10.1), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=269, connection=close, objectId=bXYVlwltiN, title=You have a new message , body=You have a new message , sound=default
verbose: RESPONSE from [POST] /parse/push: {
  "headers": {
    "X-Parse-Push-Status-Id": "ZOrTd4OylW"
  },
  "response": {
    "result": true
  }
} X-Parse-Push-Status-Id=ZOrTd4OylW, result=true

> 

No notifications are delivered.  Can you please tell me what I have missed?

**Comment by Jawnnypoo** [comment]
Parse does not support FCM push, you need to do the setup for GCM instead.

**Comment by billyz313** [comment]
I just setup the GCM for the application and changed the API key to the GCM one, everything else stays the same right?  I still didn't get any error or notification.

**Comment by rogerhu** [comment]
Can you look through https://guides.codepath.com/android/Push-Notifications-Setup-for-Parse and see if you followed those steps?

**Comment by Jawnnypoo** [comment]
Your query needs to be for Installation objects, not User objects

**Comment by Jawnnypoo** [comment]
For example:
```
var query = new Parse.Query(Parse.Installation);
```
Would send to all devices

**Comment by billyz313** [comment]
I have changed my query to 
`var pushQuery = new Parse.Query(Parse.Installation);`
so it should just send to every installation, however i'm still getting the same error.  It still goes to the success and prints out "#### PUSH OK" but then prints the error "_pushStatus ygmN5ce4R: error while sending push error=PushController: no results in query.
