### ISSUE TITLE
I can't build aar file. Hopefully your help.

### ISSUE THREAD

**Issue by mobilemaster128** [parse-community/Parse-SDK-Android#799]
when run gradle (gradlew clean build), I got below error.

F:\Work\Gukki\Parse-SDK-Android>gradlew clean build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :Parse
Observed package id 'add-ons;addon-google_apis-google-24' in inconsistent location 'D:\Android\sdk\add-ons\addon-google_apis-google-24-1' (Expected 'D:\Android\sdk\add-ons\addon-google_apis-google-24')
Already observed package id 'add-ons;addon-google_apis-google-24' in 'D:\Android\sdk\add-ons\addon-google_apis-google-24'. Skipping duplicate at 'D:\Android\sdk\add-ons\addon-google_apis-google-24-1'
Observed package id 'add-ons;addon-google_apis-google-24' in inconsistent location 'D:\Android\sdk\add-ons\addon-google_apis-google-24-1' (Expected 'D:\Android\sdk\add-ons\addon-google_apis-google-24')
Already observed package id 'add-ons;addon-google_apis-google-24' in 'D:\Android\sdk\add-ons\addon-google_apis-google-24'. Skipping duplicate at 'D:\Android\sdk\add-ons\addon-google_apis-google-24-1'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Parse:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_161 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
41 actionable tasks: 40 executed, 1 up-to-date

F:\Work\Gukki\Parse-SDK-Android>

**Comment by Jawnnypoo** [comment]
Looks like your environment is not set up properly with the right path to a JDK. This is a different issue from this actual library, closing.

**Comment by mobilemaster128** [comment]
Thank you for your reply
I have fixed issue
Cheers
