### ISSUE TITLE
Master Build Failing Travis CI

### ISSUE THREAD

**Issue by addisonElliott** [parse-community/Parse-SDK-Android#803]
@flovilmart I just checked it out because I wanted to make sure I didn't mess up the build...

It failed with something like "--github_token=" does not work.

Basically, you need to set GITHUB_TOKEN in Travis CI dashboard for the repository for it to work. Just a friendly reminder...

**Comment by flovilmart** [comment]
@addisonElliott perfect! I added back the key and the latest version of the docs is published now! 

Great job! 

http://parseplatform.org/Parse-SDK-Android/api/
