### ISSUE TITLE
Parse works in debug APK but not signed APK

### ISSUE THREAD

**Issue by neelkamath** [parse-community/Parse-SDK-Android#810]
My [app](https://github.com/neelkamath/goal-ninja-android) works perfectly in the debug APK, but when I use a signed APK (whether it's uploaded to the Play Store like [this](https://play.google.com/store/apps/details?id=io.github.neelkamath.goalninja) or just copy-pasting it to my phone) Parse doesn't function.

The initial account activity where the user logs in works fine but when creating or retrieving `ParseObject`s, it doesn't. This is the stacktrace given when dealing with a `ParseObject` subclass:
```
java.lang.RuntimeException: Failed to create instance of subclass.
com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:114)
    android.os.Handler.handleCallback(Handler.java:790)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6501)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Furthermore, if I close the app from the background tasks and open it again, `ParseUser` becomes `null`.

Here's the `Application` snippet for initializing Parse:
```java
public class App extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        ParseObject.registerSubclass(Goal.class);
        Parse.enableLocalDatastore(this);
        Parse.initialize(this);
        ParseACL.setDefaultACL(new ParseACL(), true);
```

**Comment by Jawnnypoo** [comment]
Are you using Proguard?

**Comment by neelkamath** [comment]
@Jawnnypoo no
