### ISSUE TITLE
ParseObject.delete() is successful while beforeDelete trigger returns an error

### ISSUE THREAD

**Issue by DanGTZ** [parse-community/Parse-SDK-Android#825]
## My setup
- parse-server 2.6.3
- Parse-SDK-Android 1.17.3

## Server code
Parse.Cloud.beforeDelete("TestClass", function(request, response) {
response.error("Delete is not allowed");
});

## Android JUnit4 test code
@Test
public void testDeleteObject() throws Exception {
ParseObject object = ParseObject.create("TestClass");
object.save();
object.delete();
}

## Expectation
The Android test should fail as object.delete() should throw a ParseException.

## Result
The Android test passes (no exception).

### Server logs
> verbose: REQUEST for [POST] /parse/classes/TestClass: {} method=POST, url=/parse/classes/TestClass, x-parse-session-token=r:xxx, x-parse-application-id=xxx, x-parse-client-version=a1.17.3, x-parse-app-build-version=2116, x-parse-app-display-version=2.1.1.0, x-parse-os-version=P, user-agent=Parse Android SDK 1.17.3 (com.perfexpert/2116) API Level 27, x-parse-installation-id=39b74a67-f47f-4ce5-b6fc-d2b881312cbe, x-parse-client-key=xxx, content-type=application/json, content-length=2, host=10.0.2.2:1337, connection=Keep-Alive, accept-encoding=gzip, 
verbose: RESPONSE from [POST] /parse/classes/TestClass: {
  "status": 201,
  "response": {
    "objectId": "V959ykRkPx",
    "createdAt": "2018-05-16T16:12:20.408Z"
  },
  "location": "http://localhost:1337/parse/classes/TestClass/V959ykRkPx"
} status=201, objectId=V959ykRkPx, createdAt=2018-05-16T16:12:20.408Z, location=http://localhost:1337/parse/classes/TestClass/V959ykRkPx
verbose: REQUEST for [DELETE] /parse/classes/TestClass/V959ykRkPx: {} method=DELETE, url=/parse/classes/TestClass/V959ykRkPx, x-parse-session-token=r:xxx, x-parse-application-id=xxx, x-parse-client-version=a1.17.3, x-parse-app-build-version=2116, x-parse-app-display-version=2.1.1.0, x-parse-os-version=P, user-agent=Parse Android SDK 1.17.3 (com.perfexpert/2116) API Level 27, x-parse-installation-id=39b74a67-f47f-4ce5-b6fc-d2b881312cbe, x-parse-client-key=xxx, host=10.0.2.2:1337, connection=Keep-Alive, accept-encoding=gzip, 
error: beforeDelete failed for TestClass for user QgYc16oZWm:
  Input: {"createdAt":"2018-05-16T16:12:20.408Z","updatedAt":"2018-05-16T16:12:20.408Z","objectId":"V959ykRkPx"}
  Error: {"code":141,"message":"Delete is not allowed"} className=TestClass, triggerType=beforeDelete, code=141, message=Delete is not allowed, user=QgYc16oZWm
error: Error generating response. ParseError { code: 141, message: 'Delete is not allowed' } code=141, message=Delete is not allowed
error: Delete is not allowed code=141, message=Delete is not allowed

**Comment by DanGTZ** [comment]
I also tested with 1.13.1 and it worked as expected : object.delete() has thrown an exception

**Comment by flovilmart** [comment]
@DanGTZ are you able to identify why the exception isn’t thrown?

**Comment by DanGTZ** [comment]
@flovilmart currently no, but with some indications I could do some searchs

**Comment by DanGTZ** [comment]
@flovilmart I can see there is no tests for the delete methods in the project, so I don't know really where to start.

**Comment by flovilmart** [comment]
Im not sur either; perhaps @rogerhu has an idea or @jawnnypoo ?

**Comment by Jawnnypoo** [comment]
@DanGTZ Can you initialize Parse with a custom OkHttp Builder with a logging interceptor? https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor Then we can see if it is getting back the error from the server or not

**Comment by DanGTZ** [comment]
@Jawnnypoo ok here are the logs (note that I renamed "TestClass" to "TestClassDeleteForbidden" in my Android test

> D/OkHttp: --> POST http://10.0.2.2:1337/parse/classes/TestClassDeleteForbidden http/1.1
D/OkHttp: Content-Type: application/json
D/OkHttp: Content-Length: 2
D/OkHttp: X-Parse-Session-Token: r:xxx
D/OkHttp: X-Parse-Application-Id: xxx
D/OkHttp: X-Parse-Client-Version: a1.17.3
D/OkHttp: X-Parse-App-Build-Version: 2116
D/OkHttp: X-Parse-App-Display-Version: 2.1.1.0
D/OkHttp: X-Parse-OS-Version: P
D/OkHttp: User-Agent: Parse Android SDK 1.17.3 (com.perfexpert/2116) API Level 27
D/OkHttp: X-Parse-Installation-Id: 39b74a67-f47f-4ce5-b6fc-d2b881312cbe
D/OkHttp: X-Parse-Client-Key: xxx
D/OkHttp: Host: 10.0.2.2:1337
D/OkHttp: Connection: Keep-Alive
D/OkHttp: Accept-Encoding: gzip
D/OkHttp: {}
D/OkHttp: --> END POST (2-byte body)
D/OkHttp: <-- 201 Created http://10.0.2.2:1337/parse/classes/TestClassDeleteForbidden (677ms)
D/OkHttp: X-Powered-By: Express
D/OkHttp: Access-Control-Allow-Origin: *
D/OkHttp: Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
D/OkHttp: Access-Control-Allow-Headers: X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type
D/OkHttp: Location: http://localhost:1337/parse/classes/TestClassDeleteForbidden/FHQx3zinwS
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Content-Length: 64
D/OkHttp: ETag: W/"40-RYqeOPmMJd61YlSze61KLZYWO7o"
D/OkHttp: Date: Thu, 17 May 2018 11:23:04 GMT
D/OkHttp: Connection: keep-alive
D/OkHttp: {"objectId":"FHQx3zinwS","createdAt":"2018-05-17T11:23:04.588Z"}
D/OkHttp: <-- END HTTP (64-byte body)
D/OkHttp: --> DELETE http://10.0.2.2:1337/parse/classes/TestClassDeleteForbidden/FHQx3zinwS http/1.1
D/OkHttp: X-Parse-Session-Token: r:xxx
D/OkHttp: X-Parse-Application-Id: xxx
D/OkHttp: X-Parse-Client-Version: a1.17.3
D/OkHttp: X-Parse-App-Build-Version: 2116
D/OkHttp: X-Parse-App-Display-Version: 2.1.1.0
D/OkHttp: X-Parse-OS-Version: P
D/OkHttp: User-Agent: Parse Android SDK 1.17.3 (com.perfexpert/2116) API Level 27
D/OkHttp: X-Parse-Installation-Id: 39b74a67-f47f-4ce5-b6fc-d2b881312cbe
D/OkHttp: X-Parse-Client-Key: xxx
D/OkHttp: Host: 10.0.2.2:1337
D/OkHttp: Connection: Keep-Alive
D/OkHttp: Accept-Encoding: gzip
D/OkHttp: --> END DELETE
D/OkHttp: <-- 400 Bad Request http://10.0.2.2:1337/parse/classes/TestClassDeleteForbidden/FHQx3zinwS (191ms)
D/OkHttp: X-Powered-By: Express
D/OkHttp: Access-Control-Allow-Origin: *
D/OkHttp: Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
D/OkHttp: Access-Control-Allow-Headers: X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Content-Length: 44
D/OkHttp: ETag: W/"2c-phFgJSPL6QagW5F+wLQGnE/IR1g"
D/OkHttp: Date: Thu, 17 May 2018 11:23:05 GMT
D/OkHttp: Connection: keep-alive
D/OkHttp: {"code":141,"error":"Delete is not allowed"}
D/OkHttp: <-- END HTTP (44-byte body)

**Comment by DanGTZ** [comment]
This problem is present since v1.15.2
One of the following changes is responsible for it : https://github.com/parse-community/Parse-SDK-Android/compare/1.15.1...1.15.2

**Comment by Jawnnypoo** [comment]
Can you confirm that this happens with actual usage on a device as well @DanGTZ ?

**Comment by DanGTZ** [comment]
Yes I confirm. First time I noticed this issue is on a real device, just after upgraded parse sdk version from 1.13.1 to 1.17.3
