### ISSUE TITLE
Failed to resolve: com.parse:parse-android-gcm:1.17.3

### ISSUE THREAD

**Issue by YoavTamir00** [parse-community/Parse-SDK-Android#829]
I wanted to use the GCM library but I it doesn't find it when I try to import in gradle as said in it's docs:
   `    implementation 'com.parse:parse-android-gcm:1.17.3'
`
and in gradle sync it throws
`Failed to resolve: com.parse:parse-android-gcm:1.17.3
`
BUT after it seems that 
`    implementation 'com.parse:parse-gcm-android:1.17.3'
` 
does work!
maybe it is a typo in the readme file?

**Comment by Jawnnypoo** [comment]
Thanks for pointing this out @YoavTamir00. We will fix this in the next release!
