### ISSUE TITLE
Implementation Parse-cmf Problem with Admob - Error inflating class com.google.android.gms.ads.AdView

### ISSUE THREAD

**Issue by rodrigosmarques** [parse-community/Parse-SDK-Android#840]
I have an application running and want to implement push notifications. The app has Admob.
When I include the implementation dependency "com.parse: parse-fcm-android: $ parseVersion" and I follow all the steps of the implementation the application starts to display error in the adsView XML:
"Unable to start activity ComponentInfo {.... activity.MainActivity}: android.view.InflateException: Binary XML file line # 17: Binary XML file line # 17: Error inflating class com.google.android.gms.ads.AdView
android.app.ActivityThread.performLaunchActivity "

Retrieving only the parse-fcm implementation, it works again.

Here is my gradle file:

---------------------------------------------------------------------------------------------------
_dependencies {
    compile('com.crashlytics.sdk.android:crashlytics:2.9.3@aar') {
        transitive = true
    }
    compile('com.crashlytics.sdk.android:answers:1.4.1@aar') {
        transitive = true
    }
    compile('io.branch.sdk.android:library:2.17.1@aar') {
        transitive = true
    }
    compile('io.fabric.sdk.android:fabric:1.3.10@aar') {
        transitive = true
    }

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.installreferrer:installreferrer:1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.android.support:support-v4:27.1.0' //android support
    implementation 'com.android.support:appcompat-v7:27.1.0' //android support
    implementation 'com.android.support:cardview-v7:27.1.0' //android support
    implementation 'com.android.support:design:27.1.0' //android support
    implementation 'com.android.support:customtabs:27.1.0'
    implementation 'com.android.support:design:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.android.support:support-vector-drawable:27.1.0'
    implementation 'com.parse:parse-android:1.17.3' //parse
    //implementation 'com.parse:parse-livequery-android:1.0.4' //parse
    implementation 'com.parse:parsefacebookutils-v4-android:1.10.4@aar' //parse
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation 'de.cketti.mailto:email-intent-builder:1.0.0' //send email
    implementation 'io.github.kobakei:ratethisapp:1.2.0' //rate ap
    implementation 'com.google.android.gms:play-services-ads:10.2.1'
    implementation 'com.google.android.gms:play-services-location:10.2.1'
    implementation 'com.google.android.gms:play-services:10.2.1' //playservices
    implementation 'com.google.firebase:firebase-appindexing:10.2.1' //firebase app index
    implementation 'com.afollestad:sectioned-recyclerview:0.5.0' //grid
    //implementation 'com.google.zxing:core:3.3.0' //qrcode
    //implementation 'me.dm7.barcodescanner:zxing:1.9' //qrcode
    implementation 'com.afollestad.material-dialogs:core:0.9.6.0' //dialog
    implementation 'com.afollestad.material-dialogs:commons:0.9.6.0'//dialog
    implementation 'com.inlocomedia.android:android-sdk-ads:3.5.+' //inlocomedia SDK
    implementation 'com.inlocomedia.android:android-sdk-location:3.5.+' ///inlocomedia DK
    implementation 'com.inlocomedia.android:android-admob-adapter:3.1.0' //admob adapter
    implementation 'org.jsoup:jsoup:1.10.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}_

**Comment by Jawnnypoo** [comment]
If you can update your Google Play Services dependencies to match the latest (15+), it will more than likely resolve this.

**Comment by rogerhu** [comment]
Can we update the README and docs about this?

**Comment by rodrigosmarques** [comment]
Thanks. I updated the versions and it is now working

New Gradle:

dependencies {
    compile('com.crashlytics.sdk.android:crashlytics:2.9.3@aar') {
        transitive = true
    }
    compile('com.crashlytics.sdk.android:answers:1.4.1@aar') {
        transitive = true
    }
    compile('io.branch.sdk.android:library:2.17.1@aar') {
        transitive = true
    }
    compile('io.fabric.sdk.android:fabric:1.3.10@aar') {
        transitive = true
    }

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.installreferrer:installreferrer:1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.android.support:support-v4:27.1.0' //android support
    implementation 'com.android.support:appcompat-v7:27.1.0' //android support
    implementation 'com.android.support:cardview-v7:27.1.0' //android support
    implementation 'com.android.support:design:27.1.0' //android support
    implementation 'com.android.support:customtabs:27.1.0'
    implementation 'com.android.support:design:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.android.support:support-vector-drawable:27.1.0'
    implementation 'com.parse:parse-android:1.17.3' //parse
    implementation 'com.parse:parse-fcm-android:1.17.3' //parse fcm
    implementation 'com.parse:parse-livequery-android:1.0.4' //parse
    implementation 'com.parse:parsefacebookutils-v4-android:1.10.6@aar' //parse
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation 'de.cketti.mailto:email-intent-builder:1.0.0' //send email
    implementation 'io.github.kobakei:ratethisapp:1.2.0' //rate app
    implementation 'com.google.android.gms:play-services-ads:15.0.1'
    implementation 'com.google.android.gms:play-services-location:15.0.1'
    //implementation 'com.google.android.gms:play-services:12.0.1' //playservices
    implementation 'com.google.firebase:firebase-appindexing:15.0.1' //firebase app index
    implementation 'com.afollestad:sectioned-recyclerview:0.5.0' //grid
    //implementation 'com.google.zxing:core:3.3.0' //qrcode
    //implementation 'me.dm7.barcodescanner:zxing:1.9' //qrcode
    implementation 'com.afollestad.material-dialogs:core:0.9.6.0' //dialog
    implementation 'com.afollestad.material-dialogs:commons:0.9.6.0'//dialog
    implementation 'com.inlocomedia.android:android-sdk-ads:3.5.+' //inlocomedia SDK
    implementation 'com.inlocomedia.android:android-sdk-location:3.5.+' ///inlocomedia DK
    implementation 'com.inlocomedia.android:android-admob-adapter:3.1.0'//admob adapter
    implementation 'org.jsoup:jsoup:1.10.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by Jawnnypoo** [comment]
@rogerhu What are you thinking specifically? Just to mention using at least 15.x of services?
