### ISSUE TITLE
Unable to query Parse-Server From Android App after deleting all Users.

### ISSUE THREAD

**Issue by grantespo** [parse-community/Parse-SDK-Android#845]
For every app I've ever developed using Parse-SDK-Android, I've needed to delete all users from my parse-dashboard. 

However, whenever this occurs, I've noticed that I am unable to query anything from Parse-Server to my android app for hours. Why is this?

**Comment by flovilmart** [comment]
> I've needed to delete all users from my parse-dashboard.

Needed is a bit strong here?

Also, because thst’s Not an issue related to parse or this SDK but more likely to your database, your should ask on stackoverflow
