### ISSUE TITLE
Unable to add parse library

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [parse-community/Parse-SDK-Android#846]
when attempting to add parse dependency in application gradle an Error pops up when trying to sync the project. it says : Failed to resolve: support-compat.

im using Android Studio 3.1.2
support Repository 47.0.0
android build-tools 28
compile and target sdk version 27
min sdk 17
parse version 1.17.3

and even added following repositories right after dependencies:

    repositories {
        mavenCentral()
        jcenter()
        maven {
            url "http://maven.google.com"
        }
    }

and even for more details im using following dependencies:

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

**Comment by Jawnnypoo** [comment]
Move 
```
maven {
        url "http://maven.google.com"
    }
```
above `jcenter()`
