### ISSUE TITLE
Using GCM compatibility always get null device token

### ISSUE THREAD

**Issue by desteve** [parse-community/Parse-SDK-Android#853]
Hi!
I'm using the GCM compatibility method, and the device token is never registered, always null. I'm using Android 8 and the following manifest:

<receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        <service
            android:name="com.parse.gcm.ParseGCMListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <service
            android:name="com.parse.gcm.ParseGCMInstanceIDListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>
        <receiver android:name="com.cuatroochenta.eulen.notifications.push.NotificationsReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>

Any idea about what can be wrong?

**Comment by Jawnnypoo** [comment]
Looks like the manifest didn't get posted properly, can you try again?

**Comment by desteve** [comment]
Forget it, it's all because the version 1.17.3 I'm using. So I downgraded to 1.16.3 using GCM and it works. It seems GCM compatibility doesn't work well, so it's time to migrate to FCM.

**Comment by Jawnnypoo** [comment]
No worries! Yep, I would recommend going that route
