### ISSUE TITLE
Use of ignoreAcls() for LocalDataStore queries is undocumented in Android SDK docs

### ISSUE THREAD

**Issue by jamesncl** [parse-community/Parse-SDK-Android#863]
I lost a couple of days of my life to this undocumented behavior:

Issue [https://github.com/parse-community/Parse-SDK-Android/issues/428](https://github.com/parse-community/Parse-SDK-Android/issues/428)

Basically, one of my subclasses of ParseObject exhibits this behaviour - attempting to retrieve pinned objects always returns an empty list, unless I call query.ignoreAcls(). The requirement to call ignoreAcls when loading from the localDataStore [is clearly documented in the iOS docs](https://docs.parseplatform.org/ios/guide/#security-in-local-datastore):

> The only difference is that you won’t be able to access any data protected by Role based ACLs due to the fact that the Roles are stored on the server. To access this data protected by Role based ACLs, you will need to ignore ACLs when executing a Local Datastore query:
> 
> PFQuery *query = [[[PFQuery queryWithClassName:@"Note"]
>                    fromLocalDatastore]
>                   ignoreACLs];

But there is [nothing in the Android SDK docs](https://docs.parseplatform.org/android/guide/). It needs to be added.

**Comment by flovilmart** [comment]
Do you want to make a PR on the docs repository to fix it?

**Comment by jamesncl** [comment]
Apologies, hadn't actually realised there was a docs repo! Have made a PR to update the docs - I've never done a PR before so hopefully I've done it right...

**Comment by flovilmart** [comment]
@jamesncl the PR was perfect! Thanks for the quick follow up!
