### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by shadi-alhaj** [parse-community/Parse-SDK-Android#865]
I am using Android Studio 3.1.3 and I tried to access Parse-SDK but it can't sync and show the following error:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.parse-community.Parse-SDK-Android:parse:latest.version.here.

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.alhaj.shadi.parseserverapp"
        minSdkVersion 25
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation "com.github.parse-community.Parse-SDK-Android:parse:latest.version.here"

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by Jawnnypoo** [comment]
Replace `latest.version.here` with the latest available version. For right now, it would be `1.18.4`, so:
```
implementation "com.github.parse-community.Parse-SDK-Android:parse:1.18.4"
```

**Comment by shadi-alhaj** [comment]
@Jawnnypoo 
Still have the same problem

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.parse-community.Parse-SDK-Android:parse:1.18.4.

**Comment by Jawnnypoo** [comment]
Try doing a Build -> Rebuild Project and make sure you have an internet connection when you do a Gradle sync

**Comment by shadi-alhaj** [comment]
@Jawnnypoo 
Thank you so much it's work, appreciate your help

**Comment by Jawnnypoo** [comment]
No problem!
