### ISSUE TITLE
mixing versions can lead to run time crashes 

### ISSUE THREAD

**Issue by shadi-alhaj** [parse-community/Parse-SDK-Android#869]
I am using Android Studio 3.1.3 and I have an issue in Gradle fie, I added the following dependency 
implementation "com.github.parse-community.Parse-SDK-Android:parse:1.18.4"

**Then I have an error "mixing versions can lead to run time crashes"**
The gradle file contains the following:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.alhaj.shadi.parseserverapp"
        minSdkVersion 25
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation "com.github.parse-community.Parse-SDK-Android:parse:1.18.4"

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by Jawnnypoo** [comment]
Updating to API 27 and 27.1.1 of the support library dependencies will fix this for you.

**Comment by shadi-alhaj** [comment]
@Jawnnypoo 

If I understand you correctly, you asked me to chose API 27 as compileSdkVersion 27, in this case there are less than 1% of devices can use my application

May I am right?
Also,

Can you help me in Updating to API 27 and 27.1.1 of the support library dependencies (step by step) if you don't mind, thinks

**Comment by Jawnnypoo** [comment]
`compileSdkVersion` does not equal `minSdkVersion`. They are very different things. You can keep your minSdkVersion as 25 (which is extremely high to be honest) or move it down to 19 which is what I would recommend. Here is what your `build.gradle` would look like:
```
apply plugin: 'com.android.application'

android {
compileSdkVersion 27
defaultConfig {
applicationId "com.alhaj.shadi.parseserverapp"
minSdkVersion 19
targetSdkVersion 27
versionCode 1
versionName "1.0"
testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
}
buildTypes {
release {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
}
}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation 'com.android.support:appcompat-v7:27.1.1'
implementation 'com.android.support.constraint:constraint-layout:1.1.2'
implementation "com.github.parse-community.Parse-SDK-Android:parse:1.18.4"

testImplementation 'junit:junit:4.12'
androidTestImplementation 'com.android.support.test:runner:1.0.2'
androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```
