### ISSUE TITLE
Program type already present: com.parse.AuthenticationCallback

### ISSUE THREAD

**Issue by amitkh6** [parse-community/Parse-SDK-Android#871]
Below is the error coming while I am running the program

Program type already present: com.parse.AuthenticationCallback
Message{kind=ERROR, text=Program type already present: com.parse.AuthenticationCallback, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by Jawnnypoo** [comment]
Can you post the list of Parse dependencies? Due to repackaging of dependencies, it is advised to be on the latest of each dependency (ParseUI, ParseFacebookUtils, etc)

**Comment by amitkh6** [comment]
These are the list of dependencies..

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.google.firebase:firebase-messaging:17.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.parse.bolts:bolts-tasks:1.4.0'
    implementation 'com.parse:parse-android:1.16.7'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation "com.github.parse-community.Parse-SDK-Android:parse:1.18.4"
    implementation "com.github.parse-community.Parse-SDK-Android:fcm:1.18.4"

    implementation "com.github.parse-community.Parse-SDK-Android:ktx:1.18.4"


**And build.gradle (project)**
buildscript {
    
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
            }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.0.1'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by Jawnnypoo** [comment]
You will need to remove `implementation 'com.parse:parse-android:1.16.7'` from your `build.gradle`

**Comment by mrtry** [comment]
I am having the same problem...
(Replaced `com.parse:parse-android` to `com.github.parse-community.Parse-SDK-Android:parse`)

I tried to update from `1.15.8` to `1.18.4`.
However I got an error saying `Program type already present: com.parse.AuthenticationCallback`.
It was able to be updated without problems with `com.parse: parse-android:1.17.3`.
Attempting to update to `com.github.parse-community.Parse-SDK-Android: parse:1.18.x` will result in an error.

I tried the following method.
- `./gradlew clean cleanBuildCache`
- remove `~/.gradle`
- with Android Studio
  - rebuild project
  - clean project
  - Invalidate and Restart

Are there any other measures...? 🙇

**Comment by Jawnnypoo** [comment]
Do you have other Parse dependencies, such as for the Facebook or Twitter Utils? If you have any other dependencies, you need to update those too.

**Comment by mrtry** [comment]
Also used GCM. 
So, it was as follows. 

```
implementation "com.github.parse-community.Parse-SDK-Android:parse:1.18.4 "
implementation "com.github.parse-community.Parse-SDK-Android:gcm:1.18.4"
```

**Comment by Jawnnypoo** [comment]
Can you paste in all your dependencies?

**Comment by mrtry** [comment]
Resolved... 🙇 
Used ParseSDK in other submodules I made by myself... 🙇
