### ISSUE TITLE
How to set uniqueness for a field that is customized in a database table

### ISSUE THREAD

**Issue by Likeyong** [parse-community/Parse-SDK-Android#882]
How to set uniqueness for a field that is customized in a database table，thanks

**Comment by Tom-Fox1** [comment]
Hi 👋. Could you please post this over on our [community forum](https://community.parseplatform.org/).

We are trying to keep GitHub issues reserved for bug reports & feature requests - see announcement about our channels of communication [here](https://community.parseplatform.org/t/where-should-you-ask-questions/167) or see the section on help and communication on our website [here](https://parseplatform.org/).

**Comment by Tom-Fox1** [comment]
If you decide to do so please also provide more information about what you are trying to achieve.
