### ISSUE TITLE
Unable to Compile latests versions 1.8.X

### ISSUE THREAD

**Issue by Sulfkain** [parse-community/Parse-SDK-Android#887]
Hello, I have a issue with icon on notifications (maybe I will create another issue with this).
I'm trying to update to the latest version 1.8.4, I have changed to the new implementations (on jetpack.io).
Well, while compiling, 2 kind of error occur (one first, then on other compilation, raises the other one, seems to be randomize the raise one or the other error)

```
Program type already present: com.parse.AbstractQueryController$1
Message{kind=ERROR, text=Program type already present: com.parse.AbstractQueryController$1, sources=[Unknown source file], tool name=Optional.of(D8)}
```

OR

```Program type already present: com.parse.AuthenticationCallback```

Both are the same error but pointing to differents classes.
Seems some kind of dependency error.

This are my dependencies
```
    implementation "com.github.parse-community.Parse-SDK-Android:parse:$parseVersion"
    implementation "com.github.parse-community.Parse-SDK-Android:fcm:$parseVersion"
    implementation "com.github.parse-community.Parse-SDK-Android:ktx:$parseVersion"
```
Where $parseVersion = 1.18.4, i have tried too 1.18.3 and no luck at all

Any info you need to debbug, please tell me
*EDITED*: The version number was a typo here, in my project it's 1.18.4

Thank's, I will appreciate a fast fix :)

**Comment by rodrigosmarques** [comment]
Hello, check the version you are reporting. The current version is 1.18.4. You wrote 1.8.4.

I'm using this version in my apps with no problem.

    implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.18.4'
    implementation 'com.github.parse-community.Parse-SDK-Android:fcm:1.18.4'

**Comment by pcegarra** [comment]
Same error here, Failed to resolve: com.parse:parse-android:1.18.4

**Comment by Sulfkain** [comment]
@rodrigosmarques Hey, sorry was a typo here, in my code it's 1.18.4.
I edited the message.

The problem still there.

Thank's!

**Comment by rodrigosmarques** [comment]
@Sulfkain 
This is very strange. Here I am using 3 applications without any problem.

Have you tried giving a clear on your project?

What is the API version of your project?

**Comment by amzoc** [comment]
I've got the same problem with similar setup.

this is what i get:

Failed to resolve: com.github.parse-community.Parse-SDK-Android:parse:1.18.5
Show in File
Show in Project Structure dialog

anyone managed to solve it ?

**Comment by Sulfkain** [comment]
Some update about this? Seems to happen on some of us

Some tests you want I do? or info you need?
You didn't updated something related with that files on the latests updates?

**Comment by Dekola** [comment]
Add the following code to your build.gradle

`allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}`

It worked for me.

**Comment by Sulfkain** [comment]
I finally I think I get it.
It seems to be a problem with liveQuery lib
https://github.com/parse-community/ParseLiveQuery-Android

If you update to the last version of parse *remember* to update to the last LiveQuery lib too.

That could be a well note on FAQ, because if they are 2 differents libs, seem odd *to must* update both at the same time.

**Comment by assilMekki** [comment]
Hello,
I have the same problem and it's still hapening even after updating to 

`    implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.18.5'
    implementation 'com.github.parse-community:ParseLiveQuery-Android:1.1.0'
    implementation 'com.github.parse-community.Parse-SDK-Android:fcm:1.18.5'
`
I also have these : 
`    implementation 'com.github.parse-community:ParseTwitterUtils-Android:1.11.1'
    implementation 'com.parse:parsefacebookutils-v4-android:1.10.3@aar'
`

is there any other solutions please ?

**Comment by Sulfkain** [comment]
For what I see, seems to be a problem with any mix between the new jitpack.io versions and any older lib versions.

And in your case @assilMekki, seems that will be a problem
implementation 'com.parse:parsefacebookutils-v4-android:1.10.3@aar'

Try to migrate all your libs to the new jitpack.io versions.
https://github.com/parse-community/ParseFacebookUtils-Android

Maybe will work

**Comment by assilMekki** [comment]
That fixed it ! thank you.

I also had to update : 
`implementation 'com.github.parse-community:ParseTwitterUtils-Android:1.11.1'`

to 1.12.0
