### ISSUE TITLE
ParseObject.save() stuck in infinite loop.

### ISSUE THREAD

**Issue by mik9** [parse-community/Parse-SDK-Android#888]
We have cloud function that returns object list (20 items, Post). It displayed in RecyclerView with pagination.
After I scroll a lot (600+ items) and try to create new object (Comment, that have reference to Post) it never returns from `save()`. I'm calling it on background thread (via RxJava).

After I attached profiler I saw it stuck in a loop:
<img width="1107" alt="10 42 47" src="https://user-images.githubusercontent.com/244760/45941405-bb445100-bfe6-11e8-924c-a5ce388ce9b6.png">
Or another:
<img width="1139" alt="10 47 41" src="https://user-images.githubusercontent.com/244760/45941539-4d4c5980-bfe7-11e8-86c3-b1b39aefb35c.png">

Used latest library version. Can share debug apk privately.

**Comment by mik9** [comment]
After removed `.enableLocalDataStore()` issues disappears.

**Comment by L3K0V** [comment]
As @shlusiak mention his #1058 PR most likely is improving even fixing this, so I close it.
