### ISSUE TITLE
FCM Token not updated when app is updated from GCM to FCM

### ISSUE THREAD

**Issue by littleariel** [parse-community/Parse-SDK-Android#890]
We are currently migrating our app from GCM to FCM and seeing an issue when users update from the current GCM version of the app to the newer FCM version. 
In that case, it seems that com.google.firebase.INSTANCE_ID_EVENT is never fired and the FCM token therefore not refreshed (seems confirmed by this: https://stackoverflow.com/questions/41330078/is-fcm-token-refreshed-on-app-update). Users going through this update path can't receive push notifications because of this. Users that do a fresh install are fine.

Is there an additional step needed in order to ensure existing installations cleanly register for FCM when updating from a non-FCM version?

**Comment by flovilmart** [comment]
Did you try what is suggested and call ‘getToken()’ on the initial activity. what’s the issue with this?

With the token returned, set in on the current installation and save.

**Comment by littleariel** [comment]
That worked! Thanks!
Not sure if the GCM->FCM migration docs should be updated to mention this?

**Comment by flovilmart** [comment]
Perhaps, you can always open a Pr on the guide to mention it.
