### ISSUE TITLE
Failed to resolve: com.github.parse-community.Parse-SDK-Android:parse:1.18.5

### ISSUE THREAD

**Issue by amzoc** [parse-community/Parse-SDK-Android#893]
Hi All, 

Just as in the the description i get that error on initial sync.

"Failed to resolve: com.github.parse-community.Parse-SDK-Android:parse:1.18.5" 

snippets of my code: build.gradle (app)

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.ariel.inspectiondemo"
        minSdkVersion 22
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.18.5'
}

repositories {
    mavenCentral()
    jcenter()
    maven {
        url "http://maven.google.com"
    }
}
`

*******************************************and build.gradle (project)

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        mavenCentral()
        jcenter()
        maven {
            url "http://maven.google.com"
        }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

any help will be greatly appreciated.

Ariel

**Comment by rogerhu** [comment]
I'm not sure why we're messing around with the Gradle scripts that no longer automate uploading to Bintray.  I looked at the last two releases and noticed we've nuked all the stuff that did this work.  I woudl restore it back.

@Jawnnypoo

**Comment by Jawnnypoo** [comment]
Versions are deployed to JitPack only now with the latest. Looks like @amzoc needs to follow the README and add `maven { url "https://jitpack.io" }` to `allprojects` as it says.

**Comment by rogerhu** [comment]
From what I understand Google is going to be adding internal jitpack
support for github branches.

I don't think this approach works for the open source world.  We should
revert.  I know of very few open source projects that follow this model.

**Comment by Jawnnypoo** [comment]
Few open source projects that follow the model of using JitPack? There are so, so many.

It has to do with the ease of releases. When a release needed to be done previously, only those with Bintray credentials/access could do so. You would have to also make commits to bump the release number in various places. Now, if you have Git repo access, you can tag a release and the library will be made available immediately via JitPack. It also reduces the friction of adding a new module/library makes it really easy to change over to a monorepo, as the iOS SDK is.

Feel free to revert it back if you wish, but I honestly think it is a detriment to the ease of development of the SDK to do so.

**Comment by amzoc** [comment]
thanks @Jawnnypoo. 

I should have started with the README instead I followed some incomplete tutorials.
It all works now. I appreciate your help.
