### ISSUE TITLE
Issue in getting response in proper format from parse database android

### ISSUE THREAD

**Issue by sitannsu** [parse-community/Parse-SDK-Android#895]
query.findInBackground(new FindCallback<Event>() {
            public void done(List<Event> itemList, ParseException e) {
                if (e == null) {
                    // Access the array of results here
                     

                    //Toast.makeText(TodoItemsActivity.this, firstItemId, Toast.LENGTH_SHORT).show();
                } else {
                    Log.d("item", "Error: " + e.getMessage());
                }
            }
        }); 

Above query does not return data in my model format. Instead it is coming under tag estimatedData.
Check below screenshots

<img width="878" alt="screen shot 2018-10-04 at 9 22 17 pm" src="https://user-images.githubusercontent.com/19958852/46486619-c899e080-c81b-11e8-9cf6-17f5ef392307.png">

**Comment by danielsanfr** [comment]
This is the normal behavior.

**Comment by sitannsu** [comment]
estimatedData is private, Then how i will get the data.

**Comment by danielsanfr** [comment]
I believe you have not read the documentation or the API reference.
**Android documentation:** https://docs.parseplatform.org/android/guide/

If you have another problem of this type, please look at StackOverflow. Here is to problems in the SDK and not to take doubts.
