### ISSUE TITLE
Parse doesn't load data in Android 9

### ISSUE THREAD

**Issue by JEKos** [parse-community/Parse-SDK-Android#897]
Hi,
I ran my app in API 28 (Android 9) without doing any changes, and I saw the areas that I have to load data from parse, it's not working. Parsing JSON from website and loading website urls in webView is working without any problem, only parse doesn't load data.
Did they change something on Android 9? Did any of you experience that problem?

**Comment by JEKos** [comment]
No one else have experienced that? My 2 apps that using parse as backend have this problem.

**Comment by flovilmart** [comment]
If you frame and ask the question with proper terms perhaps we could help. But as far as ‘load data’ goes, this doesn’t say anything meaningful

**Comment by JEKos** [comment]
@flovilmart thanks for the reply. I can't show any log, because there is no any error. It's like parse can't connect to the server to get the data, and this thing only happening in Android 9

**Comment by flovilmart** [comment]
Did you try the OK http request interceptors? Are your sure you’re using HTTPS and not HTTP? Is your ssl certificate valid?

**Comment by JEKos** [comment]
@flovilmart No I'm not using https on the parse server. Is HTTPS required in Android 9?

my Parse init is like that:
```
Parse.initialize(Parse.Configuration.Builder(this)
                    .applicationId("demoapp")
                    .clientKey("FDfsdHDhsdfJFDsfdifsdfsnc")
                    .server("http://XXX.XX.XXX.XXX:1337/parse/")
                    .build()
```

**Comment by flovilmart** [comment]
It’s 2018, you should not not use HTTPS. And I believe android 9 blocks non HTTP traffic. Closing. Please reopen if the problem persists with HTTPS

**Comment by flovilmart** [comment]
So you’re completely fine transmitting traffic unencrypted because it ‘lacks’ a tutorial running with https? It’s gotta be a joke. There’s a special place in hell for developers like you I believe who prefer putting all their user base at risk than have the intellectual integrity and honnesty to not run such insecure systems. Then what? You’re transmitting your master key as well over un encrypted channels? Up for the taking by anyone?

**Comment by JEKos** [comment]
@flovilmart I spent over 15 hours this weekend try to figure out how to setup my parse-server with https. I have Digital Ocean Droplet. I setup ngnix and added Let's encrypt in my domain and it working. Then I setup my PostgreSQL database and parse-server. I added `postgres://user:pass@host:port/database?ssl=true`  in the index.js file of parse-server and then I follow this [step](https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04#step-4-%E2%80%93-install-and-configure-nginx) and added this on my app but it doesn't working.

```
Parse.initialize(Parse.Configuration.Builder(this)
                    .applicationId("pmoreapp")
                    .clientKey("fFfsdfsdfsJFDUigdfgdfuinc")
                    .server("https://my-domain.com/parse/")
                    .build()
            )
```

The `https://my-domain.com` working without a problem.

Can you help me with that? I think it's almost but I can't figure out why it's not working.

**Comment by flovilmart** [comment]
I believe you’re confusing 2 things.

https and ssl connections to your DB. Both are indépendant.

Android is complaining about https, not the Postgres SSL connection.

**Comment by JEKos** [comment]
Yeah, I can. https://my-domain.com works without a problem and I see that html that says 'Success! The example.com server block is working!'
Also do I need this [step](https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04#step-4-%E2%80%93-install-and-configure-nginx) ?

**Comment by flovilmart** [comment]
Most probably, this is the setup instructions for nginx so it is correctly configure

**Comment by JEKos** [comment]
@flovilmart I finally made it!
Here what I did (Might help someone who's running into the same problem)

Prerequrements:
• You have to own a domain name already (I get one from namecheap) and connected to your droplet
• You already have setup parse-server and it's connected with your database (I prefer postgres)

Steps:
**1)** Install nginx on my Digital Ocean droplet with this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-18-04)
**2)** Add https on your domain name using [this](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04) tutorial.
**3)** Allow 2 ports through the firewall. `22` (for the ftp), `1337` for the parse-server  (I also added `1338` for my 2nd parse server] writing this commands
`sudo ufw allow 22/tcp`
`sudo ufw allow 1337`
**4)** Then type `sudo nano /etc/nginx/sites-available/my-domain.com` and added the following on the first server {..} this file has.

```
#if you have multiple parse-server you can change it to location /parse1 and make another one with location /parse2 etc...
location /parse {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/parse; #Change 1337 with your port
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }
```
**5)** Edit your parse initialization to `https://my-domain.com/parse` on your app like that

```
Parse.initialize(Parse.Configuration.Builder(this)
                    .applicationId("myapp")
                    .clientKey("XxXXxXxXxXxXxXxXx")
                    .server("https://my-domain.com/parse")
                    .build()
            )
```

**6)**  **Bam! It works!**

**Comment by flovilmart** [comment]
You should not need to open the firewall ports for your server, also 22 is SSH not FTP

**Comment by JEKos** [comment]
@flovilmart ok, thanks. I'll try it.

**Comment by JEKos** [comment]
@flovilmart Yep, I don't need them. I edited the tutorial above. Thanks!
