### ISSUE TITLE
Icon notification

### ISSUE THREAD

**Issue by Sulfkain** [parse-community/Parse-SDK-Android#899]
Hi,
On newer versions of Android the app icon, it's create such of SVG file, the foreground path and the background path (https://developer.android.com/studio/write/image-asset-studio), then mixing on some algorithm depending on the device (or launcher of Android) will dinamically create the icon app.

Firebase, knowing this problem, enable 2 steps to change the default icon, not to get the default app icon, instead, get what I set here.
```
<!-- Set custom default icon. This is used when no icon is set for incoming notification messages.
     See README(https://goo.gl/l4GJaQ) for more. -->
<meta-data
    android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@drawable/ic_stat_ic_notification" />
<!-- Set color used with incoming notification messages. This is used when no color is set for the incoming
     notification message. See README(https://goo.gl/6BKBk7) for more. -->
<meta-data
    android:name="com.google.firebase.messaging.default_notification_color"
    android:resource="@color/colorAccent" />
```

As you see here:
https://firebase.google.com/docs/cloud-messaging/android/client

- So while sending with parse, the icon of the notification gets the background layer only and the user just see a white plain dot (because our background icon is a white round).

- While sending with the Firebase notification pusher (https://console.firebase.google.com/project/_/notification?), we get the correct icon showed.

Seems there is a problem on the parse notification part, which don't read that tags and replace the default icon.

Thank's

**Comment by Sulfkain** [comment]
Any update about that?

**Comment by Jawnnypoo** [comment]
You can subclass `ParsePushBroadcastReceiver` and override `getNotification` and call the super, getting the created notification builder and then overriding it with your own icon.

**Comment by Sulfkain** [comment]
Finally I have fixed adding this, without subclass the Receiver from Parse

`<meta-data android:name="com.parse.push.notification_icon" android:resource="@drawable/ic_notification" />`
