### ISSUE TITLE
The order does not work after updating to 3.0.0  parse server

### ISSUE THREAD

**Issue by eslam2010011** [parse-community/Parse-SDK-Android#901]
my code 
 Query_post  = ParseQuery.getQuery(Database.t_Post);
            Query_post.whereContainedIn(Database.m_id_user, id);
            Query_post.orderByAscending("createdAt");
            Query_post.setSkip(itemPost * DISPLAY_LIMIT);
            Query_post.setLimit(DISPLAY_LIMIT);
            Query_post.include("Like");
            Query_post.include("createdBy");

**Comment by Jawnnypoo** [comment]
You should probably do some more investigating and seeing what logs you get in the server. The SDK does not have to do with server 3.0.0 issues, and you should probably open an issue there (with a lot more details)
