### ISSUE TITLE
Installation appVersion shows versionName instead of versionCode

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Android#902]
**Issue:**
The Android SDK sets the app's `versionName` (e.g. `2.0`) instead of its `versionCode` (e.g. build `200`) in the `Installation` field `appVersion`.

**Expected:**
The build number (i.e. `versionCode`) should be set.

**Rationale:**
It makes sense to set the version code, because:
* server logic that is dependent on the build number can easily compare the `versionCode` being an integer, instead of `versionName` being a String.
* a build number more accurately identifies an app package than a version code.
* it contradicts the Parse iOS SDK which sets the app build number

However, correcting this inconsistency would be a breaking change for existing server logic.
Note: The API request header contains both, the build number and version name.

**Affected Code:**
https://github.com/parse-community/Parse-SDK-Android/blob/0cfc67e9a3bcedc714f0041ee60cafb40ed93520/parse/src/main/java/com/parse/ParseInstallation.java#L212

https://github.com/parse-community/Parse-SDK-Android/blob/0cfc67e9a3bcedc714f0041ee60cafb40ed93520/parse/src/test/java/com/parse/ParseInstallationTest.java#L292

**Comment by flovilmart** [comment]
Uhm, that’s indeed problematic as it’s been a while. Can we feature flag it so it’s picked at initialization time by the developer?

**Comment by mtrezza** [comment]
I like the feature flag idea. It should be also a feature in the iOS SDK then.

**Comment by flovilmart** [comment]
Good idea

**Comment by mtrezza** [comment]
I suggest tagging this as up for grabs, good first PR.
