### ISSUE TITLE
Sometimes ParseInstallation object Id is null.

### ISSUE THREAD

**Issue by kkbpower** [parse-community/Parse-SDK-Android#906]
[Android]

```
ParseInstallation installation = ParseInstallation.getCurrentInstallation();
installation.fetchIfNeededInBackground(new GetCallback<ParseInstallation>){
    @Override
    public void done(final ParseInstallation object, ParseException e) {
        object.put("user", User.getCurrentUser());
        object.saveInBackground(new SaveCallback(){
            if(e == null){
                        // object.getObjectId is null
            }
        });

    }
}
```

response of ParseInstallation.saveInBackground has not error.
But ParseInstallation object id is null.
So I should reinstall my android app.
What can i do?

`implementation 'com.parse:parse-android:1.16.7'`

**Comment by Jawnnypoo** [comment]
Instead you can call `installation.saveInBackground` and then set the user then. The object does not have an objectId until it has been saved on the server, and this ParseInstallation might only have been created locally at this point.
