### ISSUE TITLE
Unable to create service com.parse.PushService: java.lang.ClassCastException: com.parse.ParsePlugins cannot be cast to com.parse.ParsePlugins$Android android.app.ActivityThread.handleCreateService

### ISSUE THREAD

**Issue by dsemelianov** [parse-community/Parse-SDK-Android#911]
I am seeing this error occur from the Parse PushService. I recently upgraded my Parse dependencies and am worried that that is causing the issue.

I used to use this: 

    compile files('libs/parse-android-1.13.1.jar')
    compile files('libs/bolts-android-1.4.0.jar')

But now I updated to this:

    compile "com.github.parse-community.Parse-SDK-Android:parse:1.18.5"

Any ideas what the problem could be?

I have not added the Parse fcm dependency because I am not using it currently, but perhaps that's the issue?

Full stacktrace below:

Fatal Exception: java.lang.RuntimeExceptionUnable to create service com.parse.PushService: java.lang.ClassCastException: com.parse.ParsePlugins cannot be cast to com.parse.ParsePlugins$Android Raw Text
--
  | android.app.ActivityThread.handleCreateService (ActivityThread.java:3308)
  | android.app.ActivityThread.-wrap5 (ActivityThread.java)
  | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1618)
  | android.os.Handler.dispatchMessage (Handler.java:102)
  | android.os.Looper.loop (Looper.java:154)
  | android.app.ActivityThread.main (ActivityThread.java:6311)

**Comment by Jawnnypoo** [comment]
Are you using Parse GCM push, or using push at all?

This comes from the fact that you have `PushService` registered in your manifest, and `PushService` no longer exists. If you are not using push at all for your app, you can just remove it. Otherwise you will need to migrate to the GCM or FCM dependencies

**Comment by dsemelianov** [comment]
Thanks Jawnny! I'll go ahead and remove it from the Manifest.

**Comment by Jawnnypoo** [comment]
Great! No problem
