### ISSUE TITLE
deviceToken is empty in parse installation table

### ISSUE THREAD

**Issue by developer--** [parse-community/Parse-SDK-Android#918]
I got undefined deviceToken field in parse table, when installation is successfully finished,
but this happens for some devices only, I have tested it for Android P, O, M, L and e.t.c and works properly, for now problem appears for samsung S7, installation goes success but deviceToken is empty. 
I'm using FCM for push notification.

```
implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.18.5'
implementation 'com.github.parse-community.Parse-SDK-Android:ktx:1.18.5'
implementation 'com.github.parse-community.Parse-SDK-Android:fcm:1.18.5'

implementation 'com.google.firebase:firebase-messaging:17.3.4'
implementation 'com.google.firebase:firebase-core:16.0.6'
```

**Manifest.xml**

<service android:name="com.parse.fcm.ParseFirebaseMessagingService">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
      </intent-filter>
    </service>
    <service
        android:name="com.parse.fcm.ParseFirebaseInstanceIdService"
        android:exported="true">
      <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
      </intent-filter>
    </service>

    <receiver
        android:name=".receivers.MyParsePushBroadcastReceiver"
        android:exported="false">
      <intent-filter>
        <action android:name="com.parse.push.intent.RECEIVE"/>
        <action android:name="com.parse.push.intent.DELETE"/>
        <action android:name="com.parse.push.intent.OPEN"/>
      </intent-filter>
    </receiver>`

**Comment by Jawnnypoo** [comment]
If the device has Google Play Services disabled or does not have the most up to date version of Google Play Services, there is a chance there would be no device token to upload.

**Comment by developer--** [comment]
I check and I have latest version of Google Play Services and it isn't disabled. 
Also if I invoke this code, the variable token is not empty, it is a valid token, but in installation object it has a null value.
```
FirebaseInstanceId.getInstance().instanceId.addOnSuccessListener {
                val token = it.token
                if (token.isNullOrEmpty()){
                  toast("token is empty")
                }else {
                  toast("Token 1: $token")
                }
              }
```

**Comment by Jawnnypoo** [comment]
Are you creating/saving the installation manually? Can you share the code where you are creating/saving the installation if you are anywhere?

**Comment by developer--** [comment]
```
    val instalation = ParseInstallation.getCurrentInstallation()
    instalation.pushType = "FCM"
    instalation.put("GCMSenderId", "123456789")
    instalation.saveInBackground { err ->
      if (err == null) {
        Log.d("INSTALATION_LOG", instalation.deviceToken)
      } else {
        err.printStackTrace()
      }
    }
```

**Comment by Jawnnypoo** [comment]
You shouldn't need to set the push type manually like that. Other than that, I see no issues with what you are showing. Can you enable verbose logging and see what shows up in LogCat under the ParseFCM tag?
```
Parse.setLogLevel(Parse.LOG_LEVEL_DEBUG);
```

**Comment by developer--** [comment]
Unfortunately I don't have this concrete device physically :((

**Comment by jecook** [comment]
Does the device have power saving mode enabled?
When I have power saving enabled on my Samsung Galaxy S6, the job that is scheduled to register with FCM never seems to get run, so I see a `"ParseFCM: Scheduling job to register Parse FCM"` message, but nothing else. Turning that mode off allows the job to run, and the installation table gets populated correctly.

**Comment by Jawnnypoo** [comment]
That is a really great point @jecook It is more than likely something like this. 

@developer-- If you really need to have the token save, you can add some manual checks when the app launches to see if the token is saved/exists and save it similar to how we are in that job if it does not exist. https://github.com/parse-community/Parse-SDK-Android/blob/master/fcm/src/main/java/com/parse/fcm/ParseFirebaseJobService.java#L48

**Comment by developer--** [comment]
Hm, :/ I thought I can't edit parse installation fields manually. Thanks <3

**Comment by ugochirico** [comment]
I solved in this way: if I found that deviceToken is null I call 

FirebaseInstanceId.getInstance().getInstanceId().addOnCompleteListener

to receive the token and then I store the received token by using ParseFCM.register(token)

this is my code:

```
installation.saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                if(e == null)
                {
                    String token = installation.getString("deviceToken");
                    if(token == null)
                    {
                        FirebaseInstanceId.getInstance().getInstanceId()
                                .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                                    @Override
                                    public void onComplete(@NonNull Task<InstanceIdResult> task) {
                                        if (!task.isSuccessful()) {
                                            Log.w(LOGTAG, "getInstanceId failed", task.getException());
                                            return;
                                        }

                                        // Get new Instance ID token
                                        String token = task.getResult().getToken();
                                        ParseFCM.register(token);
                                    }
                                });
                    }
                }
                else
                {
                    e.printStackTrace();
                }
            }
        });
```
