### ISSUE TITLE
Support AndroidX

### ISSUE THREAD

**Issue by abalta** [parse-community/Parse-SDK-Android#919]
My project migrated AndroidX, so can I use Parse GCM push with AndroidX?

**Comment by abalta-mobven** [comment]
I try now and works, but shows error on Parse imports.

**Comment by Jawnnypoo** [comment]
Can you post the errors you see @abalta ? I have a project that uses Jetifier and the Parse-SDK just fine.

**Comment by Jawnnypoo** [comment]
Also, is this specifically with the GCM module, or just the general SDK?

**Comment by abalta** [comment]
It works now.

**Comment by Jawnnypoo** [comment]
Great!
