### ISSUE TITLE
API 28 support

### ISSUE THREAD

**Issue by somnath-streetline** [parse-community/Parse-SDK-Android#923]
Currently targetSDKVersion and compileSDKVersion is 27. I was wondering when this will be bumped to 28?

**Comment by Jawnnypoo** [comment]
This shouldn't matter for you, so long as you are targeting API 28, but https://github.com/parse-community/Parse-SDK-Android/pull/926 is open to solve this.

**Comment by somnath-streetline** [comment]
Thanks for the prompt response on this.
