### ISSUE TITLE
Installation pushType is gcm with FCM

### ISSUE THREAD

**Issue by hatpick** [parse-community/Parse-SDK-Android#932]
I'm using the latest version of the SDK and FCM:
```
    implementation "com.github.parse-community.Parse-SDK-Android:parse:1.19.0"
    implementation "com.github.parse-community.Parse-SDK-Android:fcm:1.19.0"
```

Everything seems to be working but when I look into the Installation table on the parse server end, the pushType is still gcm. Is that expected?

**Comment by Jawnnypoo** [comment]
Yep, the tool used on the backend to send the pushes expects it to still be "gcm" for legacy reasons. 👍
