### ISSUE TITLE
I use the RestApi to create objects, and then get the object with error class type when the Android client gets the object

### ISSUE THREAD

**Issue by suihs11** [parse-community/Parse-SDK-Android#933]
![image](https://user-images.githubusercontent.com/12414740/53853293-cffa2b80-3fff-11e9-88ff-b40354285452.png)

The figure above shows the code and Debug data of the object I query on the Android client. In the result, the first two are the objects I created using the Android client, and the third is the data I created using the RestApi. How can I make the data created by the RestApi be DiscoveryDappType

**Comment by Jawnnypoo** [comment]
Seems like you are not using the rest API correctly in that that object it not in the DiscoveryDappType table.
