### ISSUE TITLE
Issue id: GradleCompatible

### ISSUE THREAD

**Issue by AthinaPap** [parse-community/Parse-SDK-Android#940]
**I am having this issue after I added this: implementation 'com.github.parse-community.parse-sdk-android:fcm:1.19.0' in build.gradle(Module: app). It causes manifest merger to fail. Any ideas how to fix that ?**

All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0, 26.1.0. Examples include com.android.support:animated-vector-drawable:28.0.0 and com.android.support:support-media-compat:26.1.0 less... (Ctrl+F1) 
Inspection info:There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion).

**Comment by Jawnnypoo** [comment]
You need to migrate your project to AndroidX to use the latest depenedency (1.19.0) See the guide here: https://developer.android.com/jetpack/androidx/migrate
