### ISSUE TITLE
error unauthorized: master key is required when trying to send notification with parse to an specefic device Android Parse

### ISSUE THREAD

**Issue by Jawadwithw** [parse-community/Parse-SDK-Android#946]
Hi
I'm trying to send notification to an specefic device using Parse In android.
this is my code for ParseInstallation:
`     ParseInstallation installation = ParseInstallation.getCurrentInstallation();
        installation.put("device_id", "1234567890");
        installation.saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                Log.d(TAG, "done1: "+e);
            }
        });
`
and this is my code for sending the notificaiton to specefic device that i already installed : 

        ParseQuery query = ParseInstallation.getQuery();
        query.whereEqualTo("device_id", "1234567890");
        ParsePush push = new ParsePush();
        push.setQuery(query);
        push.setMessage("salamm");
        push.sendInBackground(new SendCallback() {
            @Override
            public void done(ParseException e) {
                Log.d(TAG, "done: "+e);
            }
        });

and i get this error in log : 
 done: com.parse.ParseRequest$ParseRequestException: unauthorized: master key is required
 
can anyone help me with this?

**Comment by TomWFox** [comment]
Parse Server mo longer supports client push as it is a significant security risk. The best alternative is to put this logic in a cloud code function and call that via the Android SDK.

**Comment by Jawadwithw** [comment]
@TomWFox you mean I can send the notification the specefic device with defining function in /cloud/main.js ?

**Comment by TomWFox** [comment]
Yep, check the JavaScript guide for info about sending notifications - make sure you include `{useMasterKey:true}`

**Comment by ramiro-ciocca** [comment]
The documentation on Android SDK should be updated.  It says client push is possible. Thanks.

**Comment by davimacedo** [comment]
Can you please point out where in the docs it is wrong? Or, even better, send a PR with the correction?

**Comment by ramiro-ciocca** [comment]
https://docs.parseplatform.org/android/guide/#sending-pushes-to-queries

In the snippet:

```// Create our Installation query
ParseQuery pushQuery = ParseInstallation.getQuery();
pushQuery.whereEqualTo("injuryReports", true);

// Send push notification to query
ParsePush push = new ParsePush();
push.setQuery(pushQuery); // Set our Installation query
push.setMessage("Willie Hayes injured by own pop fly.");
push.sendInBackground();
```
sendInBackground() throws ParseException.

Thanks!

**Comment by ramiro-ciocca** [comment]
I think the correction should be to remove all the #sending-pushes-to-queries chapter and replace it as @TomWFox said, it's not longer supported device to device pushes, and a advice to use cloud functions.

Thanks.
