### ISSUE TITLE
Push notification device token not stored with Firebase 18.0.0

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Android#947]
### Issue

The fields `deviceToken` and `pushType` in the `Installation` class are not set after upgrade from 

```
implementation 'com.google.firebase:firebase-messaging:17.3.4'
implementation 'com.google.firebase:firebase-ads:17.1.2'
implementation 'com.google.firebase:firebase-core:16.0.6'
```
to
```
implementation 'com.google.firebase:firebase-messaging:18.0.0'
implementation 'com.google.firebase:firebase-ads:17.2.0'
implementation 'com.google.firebase:firebase-core:16.0.9'
```

The log output with `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);` does not show any entry containing `fcm`.

Has there been a braking change with 18.0.0?

### Environment
Android 9, issue is 100% reproducible and has been observed on Emulator and real device.

Parse libs:
```
implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.18.5'
implementation 'com.github.parse-community.Parse-SDK-Android:fcm:1.18.5'
implementation 'com.github.parse-community:ParseFacebookUtils-Android:1.12.0'
```

**Comment by Jawnnypoo** [comment]
Try switching to `1.20.0`, Firebase changed the way they want you to register for FCM, and we updated to this way within 1.20.0. Please take a look at the FCM README: https://github.com/parse-community/Parse-SDK-Android/tree/master/fcm for more

**Comment by mtrezza** [comment]
That was it! Thank you
