### ISSUE TITLE
No google services / custom device

### ISSUE THREAD

**Issue by TBbusiness** [parse-community/Parse-SDK-Android#950]
Hi,
I am trying to get it to work on custom device that does not connect to google play services (no FCM), because it is not a big brand device(Google blocked FCM to all others).

My app works perfectly on emulator and normal phone, but no luck on this custom device. 

Problem is it does not create installation data with deviceToken, installationId, etc. and when trying to access data I receive i/o failure.

I did manage to get it working at one time in past but after deleting that entry from database no luck anymore.
Is there a way to get it working without FCM/GCM ?

Thank you in advance for any help!
Kind regards

**Comment by Jawnnypoo** [comment]
You are using 1.20.0 and not including the FCM or GCM dependencies? I don't see why there would be any issues with it creating `Installation` objects and sending them to the server. Try watching Logcat and seeing if any logs are output showing what is going on.

**Comment by TBbusiness** [comment]
That is correct. 1.20.0, everything updated. With or without FCM/GCM dependencies is the same.
Logcat unfortunately is giving me no info on the issue. Set to VERBOSE log. 

My initalization code:
`public void onCreate() {
        super.onCreate();
        if (!isParseInitialized) {
            Parse.initialize(new Parse.Configuration.Builder(this)
                    .applicationId(String.valueOf(PARSE_APP_ID))
                    .clientKey(String.valueOf(PARSE_CLIENT_KEY))
                    .server("https://parseapi.back4app.com/")
                    .build()
            );
            Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
            ParseUser.enableAutomaticUser();
            isParseInitialized = true;

        }

        ParseInstallation.getCurrentInstallation().saveInBackground();

    }// end onCreate()`



My Logcat:

`01-26 12:30:35.498 2918-2999/com.domain.irestaurant I/OpenGLRenderer: Initialized EGL, version 1.4
01-26 12:30:35.503 2918-2999/com.domain.irestaurant D/Surface: Surface::final mReqUsage=602
01-26 12:30:36.791 2918-3005/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 2424 milliseconds before attempt #2
01-26 12:30:37.926 2918-3008/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 1618 milliseconds before attempt #1
01-26 12:30:37.942 2918-2999/com.domain.irestaurant D/Surface: Surface::final mReqUsage=602
01-26 12:30:39.361 2918-3010/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 4848 milliseconds before attempt #3
01-26 12:30:39.696 2918-3012/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 3236 milliseconds before attempt #2
01-26 12:30:43.072 2918-3015/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 6472 milliseconds before attempt #3
01-26 12:30:44.354 2918-3017/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 9696 milliseconds before attempt #4
01-26 12:30:49.681 2918-3020/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 12944 milliseconds before attempt #4
01-26 12:30:54.326 2918-3023/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 1253 milliseconds before attempt #1
01-26 12:30:55.724 2918-3030/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 2506 milliseconds before attempt #2
01-26 12:30:58.372 2918-3033/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 5012 milliseconds before attempt #3
01-26 12:31:02.855 2918-2999/com.domain.irestaurant D/Surface: Surface::final mReqUsage=602
01-26 12:31:03.534 2918-3042/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 10024 milliseconds before attempt #4
01-26 12:31:14.278 2918-3045/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 1265 milliseconds before attempt #1
01-26 12:31:15.695 2918-3052/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 2530 milliseconds before attempt #2
01-26 12:31:17.913 2918-2999/com.domain.irestaurant D/OpenGLRenderer: endAllStagingAnimators on 0xa4c6d800 (RippleDrawable) with handle 0xa45bc890
01-26 12:31:18.351 2918-3056/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 5060 milliseconds before attempt #3
01-26 12:31:23.973 2918-3059/com.domain.irestaurant V/com.parse.ParseRequest: Request failed. Waiting 10120 milliseconds before attempt #4`

**Comment by Jawnnypoo** [comment]
Do you see all the logs that say `Request failed. Waiting 9696 milliseconds before attempt #4` etc? That indicates that your calls to save are failing. This means that the app cannot reach your server and really should not be due to FCM or GCM or anything like that. Are you sure this device is properly connected to the internet?

**Comment by TBbusiness** [comment]
Thank you for your help! I was trying for last 3 days to fix this and finally found the issue. For some reason it didn't work because device's date and time where set to 2015. Changing that to current date fixed the issue.
Thank you!

**Comment by Jawnnypoo** [comment]
Glad to hear it!
