### ISSUE TITLE
I/O failure when targeting API 28

### ISSUE THREAD

**Issue by ManasMalla** [parse-community/Parse-SDK-Android#965]
When trying to login or signup a user i am getting parse exception error i/o failure when using the targetSDKVersion as 28. The error doesnt appear when i use targetSDKVersion 27. Please help with this as soon as possible becuase I need to target latest sdk. I originally wanted to targetSDKVersion 29.
With Regards
Hoping for reply ASAP
Manas Malla

**Comment by ManasMalla** [comment]
Please help me as soon as possible. Please need to submit my app to play store which requires targeting latest version of android SDK mostly android Q. So please help me with this as i need to send google play store link to organisation for college project

**Comment by maaeps** [comment]
I think I had this error as weil.
Restarting the parse and database server worked for me.

**Comment by kcprintz** [comment]
I have the same issue. Tried restarting server and database with no joy. Any luck @ManasMalla ?

**Comment by dramirezm** [comment]
> In your AndroidManifest file add to <application this line ... android:usesCleartextTraffic="true" ...

It works

**Comment by Jawnnypoo** [comment]
> In your AndroidManifest file add to <application this line ... android:usesCleartextTraffic="true" ...

While this will fix your failures if you are using `http`, the official recommendation would be to use `https` instead of `http`. 

Thanks for posting the solution @kcprintz 👍
