### ISSUE TITLE
No installation ID on Android X

### ISSUE THREAD

**Issue by RWOverdijk** [parse-community/Parse-SDK-Android#974]
On android 10 our app is crashing because ParseInstallation.getCurrentInstallation().objectId returns null. It works as expected on Android 9 and lower.

There’s no exception as it gets swallowed by the SDK. I don’t even know where to start.

The sdk version we're using is 1.18.6. We haven't made the leap to android X yet.

**Update:** I read somewhere this might occur when the installation isn't saved properly. I tried verifying this but it seems to not make a difference:

```kt
it.saveInBackground() { e ->
  if (e != null) {
    Log.v("DBG", "OH no! " + e.message)
  } else {
    Log.v("DBG", "Why must you hurt me this way. " + it.objectId)
  }
}
```

Output: `Why must you hurt me this way. null`

**Comment by davimacedo** [comment]
Can you please try to update to the latest SDK and also `it.getObjectId()` instead of `it.objectId` ?

**Comment by RWOverdijk** [comment]
We can't because we'd have to migrate the entire codebase over to android X.

I used getObjectId, but kotlin insisted on using objectId. Neither worked.
