### ISSUE TITLE
Parse initialize again

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Android#978]
### Issue

As of Parse SDK 1.21.0 it is not possible to initialize the Parse SDK again.
Ergo it is not possible to change the server URL.

Changing the server URL can be necessary in an architecture that provides for server app and cname failover.

### Suggested solution

I see two scenarios:
a) Connect to a different server instance with same DB.
b) Connect to a different server instance with different DB.

Because scenario b) is possible, it is not enough to only change the URL but also necessary to clear the local cache storage. So it should be possible to deinit the SDK.

There is already a `Parse.destroy()` method that is not exposed.
There is a test case that shows that it can be used to deinit the Parse SDK.

https://github.com/parse-community/Parse-SDK-Android/blob/0cfc67e9a3bcedc714f0041ee60cafb40ed93520/parse/src/test/java/com/parse/ParseUserTest.java#L1637-L1639

I suggest to expose the method.

**Comment by mtrezza** [comment]
Added PR #979

**Comment by mtrezza** [comment]
Merged PR

**Comment by Jawnnypoo** [comment]
Released as 1.22.0

**Comment by mtrezza** [comment]
@Jawnnypoo the new release fails to build on jitpack; do you know why?

https://jitpack.io/#parse-community/Parse-SDK-Android
