### ISSUE TITLE
Failed to resolve: com.github.parse-community:Parse-SDK-Android:1.22.0

### ISSUE THREAD

**Issue by priyashpatil** [parse-community/Parse-SDK-Android#986]
Initially I was unable to install any recent version of dependency. So I tried older version 1.18.6 and it got installed.
But after that I tried increasing version by release one by one til version 1.21.0. So currently I'm able to use 1.21.0 but can't upgrade to 1.22.0.

**Still gradle sync fails if upgrade version to 1.22.0**

build.gradle - project
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```
build.gradle - module
```
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.android.sdkissue"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation "androidx.viewpager2:viewpager2:1.0.0-rc01"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.github.parse-community:Parse-SDK-Android:1.21.0'
}
```

**Comment by bstillitano** [comment]
Same here.

**Comment by bstillitano** [comment]
Anything on this? Can someone tag a maintainer to alert them to this. It looks widespread.

**Comment by Jawnnypoo** [comment]
Re-released as 1.22.1

**Comment by vinchenson** [comment]
I have the same problem

**Comment by Abirul** [comment]
I have same problem

**Comment by Andrewvlad** [comment]
Try this for your build.gradle - project

`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`
