### ISSUE TITLE
ParseUser.requestPasswordResetInBackground() doesn’t throw error.

### ISSUE THREAD

**Issue by priyashpatil** [parse-community/Parse-SDK-Android#990]
`ParseUser.requestPasswordResetInBackground()` doesn't send email to non existed account or I pass normal text instead email. But it doesn't throw error.
```
ParseUser.requestPasswordResetInBackground(forgotUsernameInput.getText().toString(), new RequestPasswordResetCallback() {
    @Override
    public void done(ParseException e) {
        progress.dismiss();
        if (e == null) {
            mAlertDialog.setTitle("Email sent successfully");
            mAlertDialog.setMessage("Email has been sent to your linked account. Open link from that email to continue password reset.");
            mAlertDialog.setPositiveButton("Ok", null);
            mAlertDialog.show();
        } else {
            mAlertDialog.setTitle("Something went wrong");
            mAlertDialog.setMessage("Something went wrong. Contact us to reset your password.");
            mAlertDialog.setPositiveButton("Ok", null);
            mAlertDialog.show();
        }
    }
});
```

**Comment by Jawnnypoo** [comment]
I think this might be by design. Otherwise, you could potentially keep trying addresses to find out if certain people have accounts or not. You should change your messaging to where it says something more like "If you have an account, a reset email has been sent successfully." You will find it is common to see this kind of message.

**Comment by bahaa-ka** [comment]
https://github.com/parse-community/Parse-SDK-Android/blob/29c45f49d0f1aeac4462d2c2a5a29c5b9e599485/parse/src/main/java/com/parse/ParseUser.java#L338
so this line must be updated only to if the server is not accessible? @Jawnnypoo
