### ISSUE TITLE
Add parse user method for re send email verification

### ISSUE THREAD

**Issue by priyashpatil** [parse-community/Parse-SDK-Android#991]
As per [this](https://github.com/parse-community/parse-server/commit/22ba39812be84d39f8d46fbdcb6213aeeb06df6c) link parse has way to re send email verification link but it's not implemented in Android SDK

It could be method requestEmailVerificationInBackground or requestEmailVerification
```
ParseUser.requestEmailVerificationInBackground(email, new RequestEmailVerificationCallback())
```

**Comment by priyashpatil** [comment]
parse project is absolute now.

**Comment by RahulChandrakarr** [comment]
how can i set mail template here
